### ISSUE TITLE
Make the right TOC hidden by choice

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#102]
Currently the right TOC will hide itself when you scroll down the page, but this probably doesn't make sense for Sphinx themes which generally don't use the right margin as much (as opposed to Jupyter Books which may use this more).

We should either:

1. Make the "hiding" functionality of the right toctree and option
2. Only make the right toctree hide on scroll *if* there is margin content on the page

**Comment by choldgraf** [comment]
closed by #103

**Comment by cgarciae** [comment]
Hey @choldgraf! Is there a flag for hiding the TOC completely? A custom directive is generating an element that overlaps and the TOC is not hiding automatically:

![image](https://user-images.githubusercontent.com/5862228/174132982-b0898980-01ba-4e59-90dd-4cbd22c9c9d1.png)
ing:

**Comment by choldgraf** [comment]
Hmmm, there is no built-in configuration to hide the TOC for just a single page. But I wonder if you could get by putting custom CSS _within the page's markdown_. e.g., at the top you could try putting:

```html
<style>
.bd-toc {
  display: none;
}
</style>
```

Does that work?

Also, could you ask this question (and answer it yourself if this works) in the [ebp forum](https://github.com/executablebooks/meta/discussions) so others can find and learn?
