### ISSUE TITLE
Book menu incorrectly displayed in iPad

### ISSUE THREAD

**Issue by miguelusque** [executablebooks/sphinx-book-theme#106]
**Describe the bug**
I have noticed a bug when navigating the following url from an iPad: [https://jupyterbook.org/intro.html](https://jupyterbook.org/intro.html).

The menu is displayed like grayed/transparent on top of the text, and it doesn't look good at all.

**To Reproduce**
You may navigate to the url above from an iPad, or just use chrome developer tools and select iPad.

I have copied below a screenshot showcasing the issue and how to reproduce it.

<img width="1440" alt="Screenshot 2020-05-27 at 16 36 19" src="https://user-images.githubusercontent.com/26169771/83034790-ec391c80-a038-11ea-89aa-c686e19eea09.png">

Hope it helps!

**Comment by miguelusque** [comment]
My pleasure @choldgraf . Also, please notice that the same behaviour happens with any book produced with the latest version of jupyterbook (I noticed it when trying to create my first online book with your technology).

Please, let me congratulate all of you for your awesome work!

**Comment by choldgraf** [comment]
I've played around with this a bit, and I'm really confused about what's going on. In the browser, if I *manually* resize the window, then it works fine (the widths re-work themselves at the same time and there's no sidebar overlap). However, if I *click* the ipad button, then the bug mentioned here shows up. Changing the width of the page at all then fixes the problem.

So, not sure what's up, but here's a GIF of what's going on in case anybody has an idea:

![2020-05-29_09-03-27](https://user-images.githubusercontent.com/1839645/83280307-4cd86e80-a18b-11ea-98f1-26214b03683e.gif)

**Comment by miguelusque** [comment]
Hi @choldgraf , It looks that a Twitter user found a fix!

More info here: https://twitter.com/billgil/status/1267106009778139138?s=20

Copy and paste of his tweet:

```
In your responsive for iPad you have set the opacity to 0.6

@media
 (min-width: 768px)
.bd-sidebar {
    opacity: 0.6;
}

So remove that and you are done. My I also suggest background-color: rgba(255, 255, 255, 0.8) to get a similar effect without making the content transparent
```

**Comment by pradyunsg** [comment]
Another way to solve this issue would be to drop the opacity changing logic entirely -- the theme is equally usable on desktop if we don't set the opacity to 0.6 IMO.

**Comment by pradyunsg** [comment]
Filed #154 for if we wanna go down that route.
