### ISSUE TITLE
How to get the same look and feel than Pandas doc theme?

### ISSUE THREAD

**Issue by miguelusque** [executablebooks/sphinx-book-theme#108]
Hi!

First of all, I would like to congratulate all of you for the great work done with this theme. It looks great!

I have read that, somehow, it is inspired in Pandas theme, used here: https://pandas.pydata.org/pandas-docs/stable/

I personally like a bit more Pandas theme than the current proposal from jupyterbook, and I was wondering how difficult is to have the same theme as Pandas, if possible.

Any guidance about how to get it done would be welcomed!

In the meanwhile, have an awesome day!

Regars,
Miguel

**Comment by choldgraf** [comment]
hey Miguel - if you'd like to use the pandas theme, currently I would recommend just building a Sphinx website with the myst-nb extension activated, and directly use the pydata-sphinx-theme 👍

**Comment by miguelusque** [comment]
Hi @choldgraf ,

Thank you for your swift response. Much appreciated!

I'll do as suggested.

Regards,
Miguel
