### ISSUE TITLE
Collapsible ToC headings

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-book-theme#112]
I propose to allow making some toc sections collapsible and collapsed by default.

While the default works well, collapsible toc sections would be potentially useful for appendices/exercise solutions (my personal use case)/bonus chapters.

Edit: [readme.com](https://docs.readme.com/metrics/docs) has a good example of collapsing entries in the section-pages-tree (left sidebar):

<img src="https://user-images.githubusercontent.com/2997570/89730335-9ff55a00-da35-11ea-938e-cf7246db0a4b.png" width="400px">

**Comment by choldgraf** [comment]
Could you describe a bit more what you're imagining? I think it sounds like a good idea, I'm just not sure exactly what you mean

**Comment by akhmerov** [comment]
e.g. like the left navbar [here](https://solidstate.quantumtinkerer.tudelft.nl/) (that's mkdocs-material)

**Comment by choldgraf** [comment]
ah - and when you say "toc" do you mean the left or the right?

**Comment by akhmerov** [comment]
Indeed, I mean the left one.

**Comment by choldgraf** [comment]
gotcha - +1 from me, though this would require some reconfiguration of how the left sidebar works I think it could be useful

**Comment by pradyunsg** [comment]
readme.com is another documentation-oriented 3-column page design, that allows for collapsing entries in the section-pages-tree (left sidebar).

Screenshow w/ link to page: https://gist.github.com/pradyunsg/eeb74ac5b580d502c3d0e248310f273f#readmecom

**Comment by choldgraf** [comment]
thanks for the link!

also think that this would be easier now that we're using the Sphinx TOCtree object instead of a custom one 👍

**Comment by pradyunsg** [comment]
Hurray! Sorry if I was unnecessary noise in the PR!

**Comment by chrisjsewell** [comment]
> Hurray! Sorry if I was unnecessary noise in the PR!

You should be 😝

**Comment by choldgraf** [comment]
I think what @chrisjsewell means to say is "thanks for providing your perspectives and opinions in these PRs, it is much appreciated even if not directly incorporated into the PR :-)"

**Comment by chrisjsewell** [comment]
No I don't think so 😂
