### ISSUE TITLE
explain in the documentation that the syntax is specified in MyST

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-book-theme#113]
Readers of the documentation searching for a nice sphinx theme and not familiar with MyST may be confused by the MyST code examples and its relation with restructured text. Perhaps it's worth to clarify this.

**Comment by choldgraf** [comment]
Ah yeah I agree, I've been on the fence about whether to use MyST in these documentation pages in examples...but at the end of the day I enjoy writing myst much more than markdown haha. We should definitely explain this in the docs though
