### ISSUE TITLE
Support thebelab's predefined output

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-book-theme#115]
One of the important use cases for incorporating thebelab into a project is to allow tweaking already existing outputs. Out of the box, IIUC the already computed outputs would be duplicated by whatever thebelab produces.

At the same time, thebelab supports specifying predefined arguments, which are made into cell outputs as soon as thebelab is activated, see the required config [here](https://thebelab.readthedocs.io/en/latest/config_reference.html).

This would require modifying thebelab configuration, as well as ensuring that DOM is appropriate (the outputs must be in a div that directly follows the input).

**Comment by choldgraf** [comment]
What *should* happen is that when the thebelab button is clicked, all of the outputs get removed first. Does that not happen?

**Comment by akhmerov** [comment]
That does happen, but jupyter-book could instead keep the existing outputs and make them recognized by thebelab. That makes for a better user experience, since content doesn't just disappear from clicking a button. Not sure what is the best example out there in the wild, but check e.g. [here](https://solidstate.quantumtinkerer.tudelft.nl/1_einstein_model/) (click the "magic wand" icon for thebelab).

**Comment by choldgraf** [comment]
Ah I see - yeah that makes sense, I wonder if we could just do some re-arranging with the DOM when the button is clicked before running thebelab (that's basically what we do now). For some reason (at least for me), I find that much simpler than adding complexity to the doctree nodes of the page

**Comment by akhmerov** [comment]
I think the DOM should be mostly good as it is, thebelab doesn't require anything exotic. But otherwise indeed rearranging it on init makes most sense.

**Comment by choldgraf** [comment]
I believe this is now fixed within `sphinx-thebe` 👍
