### ISSUE TITLE
Relation between sphinx-book-theme and Jupyter Book?

### ISSUE THREAD

**Issue by HTenkanen** [executablebooks/sphinx-book-theme#117]
Hi guys! 

This is very cool what you are building! 🙂 I was wondering that how do you see the future of sphinx-book-theme? I.e. is the idea to eventually support all the same functionalities that Jupyter Book has now or how are these projects related? 

We are writing a [book](https://pythongis.org/) with my colleagues and originally we have been using Sphinx to build all our materials. Then we found Jupyter Book and seriously started thinking switching to that one because of many cool features (such as the interactive code cells with Thebelab). I was already playing around with the JupyterBook a bit and configuring the pages with RTD (not very straightforward..), and then I found this theme! So again I am wondering that should we stick with Sphinx and wait this project to develop.. 😄 

@choldgraf

**Comment by choldgraf** [comment]
Hey there - actually the `sphinx-book-theme` *is* the theme that's used by jupyter book. We are trying to make our tools modular so that they work on their own (e.g., so that people can use the `sphinx-book-theme` from a regular Sphinx site build). They will be developed in a connected manner moving forward as well!

**Comment by HTenkanen** [comment]
@choldgraf Ahaa, okay thanks for the clarification! 👍 I think we then just need to decide which one we decide to go with. We kind of like the idea of having versioning working on the site, and that can be easily achieved with RTD and using the sphinx-book-theme. I actually now got it working as well quite easily: https://python-gis-book.readthedocs.io/en/latest/ 

But still about the versioning: have you tried / succeeded deploying Jupyter Book with ReadTheDocs?

**Comment by choldgraf** [comment]
we're chatting with the RTD team to try and figure out how to make this work. I don't think it should be too tough but just need to figure things out :-)

**Comment by HTenkanen** [comment]
Okay sounds good! That would definitely be a very welcomed addition to RTD 👍 

Thanks a lot for the quick replies, I'm all good now (you can close this unless you want to keep as reference). 🙂

**Comment by choldgraf** [comment]
sounds good! thanks :-)
