### ISSUE TITLE
TypeError("'NoneType' object is not callable")

### ISSUE THREAD

**Issue by henryiii** [executablebooks/sphinx-book-theme#132]
Since yesterday, my documentation has been broken with the following error:

```
writing output... [ 14%] api/modules
Theme error:
An error happened in rendering the page api/modules.
Reason: TypeError("'NoneType' object is not callable")
make: *** [html] Error 2
```

It's in the templated API page, but that used to work and works in RtD's theme. Forcing the version to 0.0.30 solves the issue. It's in boost-histogram.readthedocs.io / GitHub.com/scikit-hep/boost-histogram.

**Comment by henryiii** [comment]
(PS: This looks like an error that MyPy would catch. ;) )

**Comment by choldgraf** [comment]
hmmmm - that's a bummer :-/ sorry it regressed for you! Did you happen to figure out what was going on here? I'll mark it as a bug

**Comment by henryiii** [comment]
Not yet, but haven't had time to investigate properly.

**Comment by choldgraf** [comment]
This may have been fixed, can you upgrade and try again?

**Comment by henryiii** [comment]
Seems to be fixed, thanks!

**Comment by choldgraf** [comment]
hooray! :-)
