### ISSUE TITLE
Suggestion to remove superscript of citations

### ISSUE THREAD

**Issue by najuzilu** [executablebooks/sphinx-book-theme#138]
Currently the theme uses superscripted citations which look like this:

<kbd>
<img width="273" alt="Screen Shot 2020-07-28 at 12 03 22 PM" src="https://user-images.githubusercontent.com/33075058/88651904-739f1c80-d0ca-11ea-9b97-96e25a2c9f2f.png">
</kbd>

@jstac suggested that we remove the superscript. What do folks think about displaying citations inline with text similarly to how they're displayed below?

<kbd>
<img width="324" alt="Screen Shot 2020-07-28 at 12 03 38 PM" src="https://user-images.githubusercontent.com/33075058/88652276-e4463900-d0ca-11ea-97bd-a2cd26f6af63.png">
</kbd>

cc @choldgraf @chrisjsewell @mmcky @AakashGfude in case you have thoughts about this.

**Comment by najuzilu** [comment]
The display of in-text citations in LaTeX is similar to my recommendation ([see examples here](https://www.overleaf.com/learn/latex/Bibliography_management_in_LaTeX)). @jstac might have a specific reason though.

**Comment by choldgraf** [comment]
Sounds good, happy to discuss w the community on this. For reference, here’s one of my old papers in nature communications that I was using to draw design inspiration from https://www.nature.com/articles/ncomms13654

**Comment by jstac** [comment]
Thanks @najuzilu for opening this.

In econ and math I never see that superscript style.  In fact this kind of style is more standard: https://econtheory.org/ojs/index.php/te/article/viewFile/20140383/10813/328.  The same is common in computer science -- e.g., https://www.sciencedirect.com/science/article/pii/S0005109820303307.

It's possible to control the bibliography style in the refs section --- see https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html.  If someone uses a bib style that generates "Holdgraf et al (2019)", is that then also superscripted?

That would be suboptimal...

Note that if superscripting is preferred then we can go our own way and eliminate it in QuantEcon's theme.  CC @DrDrij --- how does that sound?

**Comment by choldgraf** [comment]
I think that the two ways to tackle this are either:

1. Provide documentation for how others can easily over-ride this with a simple CSS rule
2. Provide a flag to make the citations superscripted or not

As a general rule I prefer approach 1 because otherwise we run the risk of having a million knobs to tweak, though if you think this is a common-enough problem then we could consider approach 2

**Comment by jstac** [comment]
Thanks for your suggestions @choldgraf .

Option 1 sounds OK, although  I wonder if superscripting is the best default?  If a bib style is chosen that inserts "Holdgraf et al (2019)" inline in the text (e.g., APA style), that would look a bit weird superscripted.

The 'Science' journals also omit superscripting: https://advances.sciencemag.org/content/6/30/eaba9639

Just my two cents.  @najuzilu Any thoughts?

**Comment by choldgraf** [comment]
To be clear - I'm not saying that we need to keep the default behavior. I think as a general rule we should take the approach of "don't have opinions unless there's a really good reason to do so". Adding superscript is an opinion and I think you've shown that there are lots of reasons not to have that opinion. So the default should be no superscript and the docs should be to show how to apply superscript if folks want it

**Comment by AakashGfude** [comment]
In terms of giving control to the user to add superscript for references,  should we add that in HTML specific settings of jupyte-book config. i.e, in the `html` dict or there is any style specific object as well? @choldgraf

**Comment by najuzilu** [comment]
Now that @jstac mentioned the different styles of `sphinxcontrib-bibtex`, I'm hesitant... It looks like two different styles, `:style: plain` and `:style: unsrt` look almost identical to footnotes when superscripted (see below examples).

`sphinxcontrib-bibtex` supports four types of style (not entirely sure why the last two types look identical to the first two):

* alpha
    * JB
        <kbd>
        <img width="810" alt="alpha" src="https://user-images.githubusercontent.com/33075058/88791097-761c7780-d199-11ea-9999-fbaf4b64db00.png">
        </kbd>
    * Sphinx
        <kbd>
        <img width="673" alt="rst_alpha" src="https://user-images.githubusercontent.com/33075058/88794662-188b2980-d19f-11ea-92e7-17a47e960361.png">
        </kbd>
* plain
    * JB
        <kbd>
        <img width="817" alt="plain" src="https://user-images.githubusercontent.com/33075058/88791108-7b79c200-d199-11ea-9fbe-e977464e3a5e.png">
        </kbd>
    * Sphinx
        <kbd>
        <img width="641" alt="rst_plain" src="https://user-images.githubusercontent.com/33075058/88794833-58eaa780-d19f-11ea-9978-20434b16600d.png">
        </kbd>
* unsrt
    * JB
        <kbd>
        <img width="808" alt="unsrt" src="https://user-images.githubusercontent.com/33075058/88791119-80d70c80-d199-11ea-9c97-dbf1e153930b.png">
        </kbd>
    * Sphinx
        <kbd>
        <img width="626" alt="rst_unsrt" src="https://user-images.githubusercontent.com/33075058/88794860-630ca600-d19f-11ea-8bf1-3bed6ca049a3.png">
        </kbd>
* unsrtalpha
    * JB
        <kbd>
        <img width="810" alt="unsrtalpha" src="https://user-images.githubusercontent.com/33075058/88791138-86cced80-d199-11ea-8ce6-b1a8618297ac.png">
        </kbd>
    * Sphinx
        <kbd>
        <img width="660" alt="rst_unsrtalpha" src="https://user-images.githubusercontent.com/33075058/88794885-6b64e100-d19f-11ea-8287-9d0cec668f42.png">
        </kbd>

Here's an example of a JB footnote:
<kbd>
<img width="797" alt="Screen Shot 2020-07-29 at 1 42 24 PM" src="https://user-images.githubusercontent.com/33075058/88796050-57ba7a00-d1a1-11ea-8a31-8f4b1b1b0afa.png">
</kbd>

**Comment by DrDrij** [comment]
I agree with @choldgraf, lets choose a default that we all agree on, and then use CSS to adjust.
This is a styling issue so CSS is the best option and the issue doesn't earn enough weight to be an option/setting in Book.

**Comment by choldgraf** [comment]
I think that we should take the following steps:

1. Make the default behavior to *not* use superscript by changing the CSS in sphinx-book-theme
2. Document how to update the citations to a new style if people wish
3. See if people open up issues with confusion or requests that it be easier
4. If we get enough issues that aren't resolvable by docs improvements, then add a flag for it

Does that make sense?

**Comment by AakashGfude** [comment]
The PR for this:-  https://github.com/executablebooks/sphinx-book-theme/pull/140 . 
Let me know if we need any other functionalities.

**Comment by choldgraf** [comment]
@AakashGfude I'm a bit confused - I thought we converged here on "don't add a new feature, just make the default a non-superscript style and document how to add the CSS to make them superscripted"...

**Comment by AakashGfude** [comment]
aah ok. worked based on previous comments. So. in the above PR 
> 
> 1. Make the default behavior to _not_ use superscript by changing the CSS in sphinx-book-theme

This is done

> 2. Document how to update the citations to a new style if people wish
> 3. See if people open up issues with confusion or requests that it be easier
> 4. If we get enough issues that aren't resolvable by docs improvements, then add a flag for it

Ohh I see, we don't want a flag to update the style yet? how do you envision people would want to update it?

**Comment by choldgraf** [comment]
Right now I'd imagine we'd just document how to manually add the proper CSS to your book to make them superscripted. I think we may want to add a configuration option for this in the future, but I'm always hesitant to add another knob for people to twist lest the documentation / API / etc become too complex

**Comment by AakashGfude** [comment]
@choldgraf hmm, probably you are right. Actually I had imagined, if we had a lot of tweaks like this, then there should be another object like `css_theme_options` somewhere in the depths of the documentation, available for people who are curious.

True this can make the API complicated. But we are anyways adding information about tweaking it in the CSS, so that contributes the same complexity, if not more, to the documentation as changing a flag?

I agree with your point that probably we should see the feedback for it. 

So, should I remove the code for the flag from that PR?

**Comment by choldgraf** [comment]
Well the thing is that it increases the complexity for a user that is determined to get this feature, but doesn't increase the complexity for anybody that is happy with the default, and also doesn't increase it for the maintainers because we don't have to worry about an extra configuration value to test, document, maintain, etc. That's why my approach is usually "document it first, and if enough people complain about it being too hard, then make it a configuration value"

What do others think?

**Comment by choldgraf** [comment]
fixed by @AakashGfude in #140
