### ISSUE TITLE
Design: (right sidebar) Change "On this page" to "Contents" (or "Table of Contents")

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-book-theme#145]
**Describe the changes you'd like**

Title says it all.

**Describe alternatives you've considered**

None. Status quo is OK. Suggested change is nicer, but I'm *obviously* biased. :)

**Additional context**

This seems to be the phrasing for the in-page-navigation-tree on all 3-column documentation-oriented themes that I know of (except this theme and the pydata theme). Sample Screenshots: https://gist.github.com/pradyunsg/eeb74ac5b580d502c3d0e248310f273f

I'm happy to file a PR for this, if there's interest in this idea. :)

**Comment by choldgraf** [comment]
I think it's a reasonable idea. My question is what those themes call the left sidebar, in that case. I just wanna make sure that our naming is consistent so we don't confuse the mental model that folks have.

**Comment by pradyunsg** [comment]
Navigation is what I've seen most often (the default Sphinx theme, and the entire lineage of themes that led to it, uses that).

**Comment by choldgraf** [comment]
Cool - then we should just make sure it's consistent in our docs etc, and I'm +1 on making it "contents" or "table of contents", whichever you think makes most sense.

**Comment by chrisjsewell** [comment]
not table of contents (that confuses it with the left side bar)

**Comment by pradyunsg** [comment]
"Contents" it is. :)

**Comment by chrisjsewell** [comment]
yeh or "Page Contents", no strong opinion though

**Comment by jorisvandenbossche** [comment]
BTW, feel free to also propose such changes in the pydata-sphinx-theme!
