### ISSUE TITLE
Design: Move topbar icons into the right sidebar

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-book-theme#146]
**Describe the change you'd like**

The change would be to move topbar icons into the right sidebar, similar to [how GitBook handles the "Edit on GitHub"](https://gist.github.com/pradyunsg/eeb74ac5b580d502c3d0e248310f273f#gitbookio) button.

IMO, the right sidebar and left sidebar feel a little asymmetric in terms of the amount of content they hold. This would allow for balancing the amount of content on top of both the sidebars, while still providing the same functionality (with potentially text descriptions, if we decide to add them as an annotated list instead of as-is icons).

**Describe alternatives you've considered**

Maintain status quo. Or, add full-width top bar or something similar that's visually distinct from the rest of the content.

**Additional context**

I'm happy to try implementing this myself, if there's interest in this idea. :)

**Comment by pradyunsg** [comment]
OOOh. I just landed on https://sphinx-book-theme.readthedocs.io/en/latest/reference/demo.html#sidebar, and I now realize why the top bar structured the way that it is. It's not a "right sidebar" as much as it is a top bar element containing the ToC that overflows out of it. :)

I *think* that invalidates this design suggestion, so I'll close this issue. Let me know if someone thinks that there's still some merit to this idea though. :)

**Comment by choldgraf** [comment]
Indeed that's how I think of it as well "topbar element that's always to the right". This is what allows users to hover-over to see the TOC if there is sidebar content on a page.
