### ISSUE TITLE
Design: Tweaking bottom-of-page content/structure

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-book-theme#147]
This is intended to initiate a discussion, to gauge whether there's anyone else who feels such a change would be useful as well as figure out what we'd change *to*. :) 

**Describe the change you'd like**

Multiple changes to the design of the bottom-of-page in this theme:

- Add a bit of space to separate "content" from "footer"
- Change the content in the footer (making it similar to the left half of mkdocs-material's bottom-of-page)
  - Move "Theme by the Executable Book Project" out of the left sidebar, into the footer
    - This is a more visible spot, and it's still out-of-the-way enough :)
  - Tweak the copyright line to match what most other documentations themes do
    - "Copyright © 2020 \<project name>"
- Change how the next/previous links look
  - Swap "<<" and ">>" for proper arrows
  - Limit width to the content (instead of overflowing into right sidebar's region)
  - Tweak style to be a middle-ground between what GitBook and mkdocs-material do
    - 50% width for both "next and prev" (like GitBook)
    - Align text to be closer to the arrows (like mkdocs-material, maybe?)
    - No visual border around the element, but a general region around the text works (like mkdocs-material, maybe?)

**Additional Context**

(screenshot of current bottom of page)
<img width="1074" alt="Screenshot 2020-08-06 at 10 28 11 AM" src="https://user-images.githubusercontent.com/3275593/89492609-a2567a80-d7cf-11ea-9538-fd2edb61bb22.png">

(screenshot) GitBook's bottom-of-page:
<img width="1074" alt="Screenshot 2020-08-06 at 10 27 35 AM" src="https://user-images.githubusercontent.com/3275593/89492606-9ff42080-d7cf-11ea-9298-ab55f319bdf0.png">

(screenshot) mkdocs-material's bottom-of-page:
<img width="1074" alt="Screenshot 2020-08-06 at 10 30 42 AM" src="https://user-images.githubusercontent.com/3275593/89492752-efd2e780-d7cf-11ea-8c03-979fecb09fe3.png">

<details>
<summary>readme.com's bottom-of-page (screenshot, click to view)</summary>
<img width="1074" alt="Screenshot 2020-08-06 at 10 31 41 AM" src="https://user-images.githubusercontent.com/3275593/89492805-1133d380-d7d0-11ea-8045-278c783eff19.png">
</details>

Top-of-page screenshots and links to the corresponding pages: https://gist.github.com/pradyunsg/eeb74ac5b580d502c3d0e248310f273f

**Comment by choldgraf** [comment]
I promise I am not just blindly saying yes to things, but these all sound like great improvements to me 👍
