### ISSUE TITLE
Make left sidebar into an off-canvas drawer on mobile/tablet

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-book-theme#148]
**Is your feature request related to a problem? Please describe.**

- The (left) sidebar "comes in from the top" of the page, through resizing of the corresponding element. This implementation requires JS to work [^1] and shows up in a different place than the desktop sidebar.
- The (left) sidebar does not degrade gracefully when JS is disabled. A user who has JS disabled for some reason (*ahem* like me) cannot view documentation built with this theme on mobile, since the sidebar cannot be collapsed and covers regular content. And they can't access the navigation either.

**A link to the documentation page where you see an issue.**

Any page works TBH. Here's the page I have open right now: https://sphinx-book-theme.readthedocs.io/en/latest/index.html

**Describe the solution you'd like**

I suggest we switch to the same mechanism+design for providing the sidebar as the mkdocs-material theme: https://squidfunk.github.io/mkdocs-material/getting-started/. Try it on ~1024px wide windows, which shows how it works best IMO. That mechanism works without needing JS (it's pure-CSS) and, thus, degrades gracefully.

Note that I'm not suggesting we change the contents/design of what's in the sidebar in this issue, but only how it is handled in terms of being visible/not visible.

FWIW, I have experience with implementing this style of a sidebar, from when I was working on re-implementing mkdocs-material for Sphinx [here](https://github.com/pradyunsg/materialism). I'm happy to try re-implementing it in the context of this theme, if there's interest in making this switch.

**Comment by pradyunsg** [comment]
Oops, I used the wrong template.

**Comment by choldgraf** [comment]
Totally I agree, I think this is a more common and probably better pattern here. To be brutally honest the only reason that the sidebar comes down from the top is because I spent two days trying to figure out how to do it from the left and couldn't find the right CSS / JS incantation to do it in bootstrap 🤦‍♂️

**Comment by chrisjsewell** [comment]
Yep definitely. You're beating me to features I wanted to look into @pradyunsg, which I absolutely have no problem with 😄

**Comment by mmcky** [comment]
@DrDrij would you be able o take a look at this `feature` request?

**Comment by choldgraf** [comment]
I believe that in the mock-up that @DrDrij showed a few months back he had some nice modifications made to the left sidebar, would love to see some of those in code form as well if you’re thinking of tackling this one too!

**Comment by DrDrij** [comment]
Added a PR for tidying animations as discussed above, including tidying the SCSS so element and media query stylings are together. Added one new variable `$leftbar-width`.

**Comment by choldgraf** [comment]
closed by #298  many thanks @DrDrij !

**Comment by danstramer** [comment]
How do we have the primary sidebar move in  from the left on mobile view? it's currently showing up from the top on mobile

**Comment by choldgraf** [comment]
hmmm - I think that you might be using a different theme, can you share a screenshot of the theme you're using?

**Comment by danstramer** [comment]
this is the screenshot:
![image](https://user-images.githubusercontent.com/1552408/170552264-5f22a3a3-5a67-4c0f-b4af-6d0e8f31840d.png)

it's based on the 'Book' theme:
https://sphinx-book-theme.readthedocs.io/en/stable/
@sdaher@habana.ai

**Comment by choldgraf** [comment]
that does not look like the latest version of the sphinx-book-theme (look at the behavior of the left sidebar in the link you shared: https://sphinx-book-theme.readthedocs.io/en/stable/)

If you are using Jupyter Book, then this will be available in the next release of Jupyter Book - or you could install jupyter book from the github repository for the latest version

**Comment by danstramer** [comment]
Thanks, I'll check and get back to you.
For the book theme, are there settings to control the sidebar behavior on mobile devices?

**Comment by choldgraf** [comment]
Nope - the sidebar behavior is baked into the theme
