### ISSUE TITLE
Add a shadow to the top bar on scroll

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-book-theme#153]
**Is your feature request related to a problem? Please describe.**

Content at the top of the page gets cropped, seemingly for no reason.

**Describe the solution you'd like**

A shadow underneath the top bar would make it easier to perceive that there is an element that's supposed to be on top, making it clearer why content is getting cropped (there's something above it!).

**Describe alternatives you've considered**

None.

**Additional context**

See https://squidfunk.github.io/mkdocs-material/getting-started/ for a decent+subtle implementation of this.

**Comment by choldgraf** [comment]
very cool - I like that idea 👍

**Comment by pradyunsg** [comment]
The top bar is... interestingly styled. Would anyone mind if I rework that element's HTML?

**Comment by choldgraf** [comment]
Ummm, depends on what your plastic surgery looks like when it's done :-)

**Comment by choldgraf** [comment]
If the end result behaves the same then in general I'm +1 though

**Comment by pradyunsg** [comment]
How do folks feel about me taking this and #148 down in one big PR?

I'm gonna need to make changes to the sidebar for this, and vice versa, so I'm thinking to kill 2 issues with one PR.

**Comment by chrisjsewell** [comment]
yep if its easier. we can always split it later if its looking too unruly

**Comment by choldgraf** [comment]
go for it (with the caveat that the more time goes on, the greater chance I will drop off the face of the earth for a bit)
