### ISSUE TITLE
No CSS for general definition (dl,dt,dd) tags

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-book-theme#158]
See https://www.w3schools.com/tags/tag_dl.asp

This means, for example, sphinx API documentation looks rubbish, because there is no delineation between components, e.g.

- RTD theme: https://ipypublish.readthedocs.io/en/latest/api/ipypublish.convert.main.html
- book theme: https://markdown-it-py.readthedocs.io/en/latest/api/markdown_it.main.html

**Comment by choldgraf** [comment]
agree we should definitely add rules for these. Ideally this would be at the pydata-sphinx-theme level but I think we can get them here faster and then upstream later
