### ISSUE TITLE
Discuss spacing / crowding issues

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#160]
We've made a few changes lately that I think make the theme more a11y-friendly, which is good. Though they also seem to have crowded things a bit when there is a lot of text on the screen. For example, here's what the EBP contributing page looks like in this theme:

New version
![image](https://user-images.githubusercontent.com/1839645/89611604-7d472380-d832-11ea-8e35-3ce42d6d7997.png)

Old version
![image](https://user-images.githubusercontent.com/1839645/89611867-1a09c100-d833-11ea-81a1-66bb61ab493b.png)

Maybe this is just me, but it feels more "crowded" and text-heavy now. I'm not sure what's the best way to improve this 🤔 maybe @pradyunsg has thoughts

**Comment by pradyunsg** [comment]
Q: How does the new version look with the sidebar scrolled to where the old screenshot has it?

My first guess is that #112 would be the most beneficial change toward feeling less crowded. Gotta go fix some stuff at home, so I'll come back say more (if I have anything else to say) later today or over the weekend. :)

**Comment by choldgraf** [comment]
hmm - so I just noticed that we now have two different font sizes used in our sidebars after the latest two PRs:

* the left sidebar items have font-size `0.9em`
* the right `contents` sidebar items have font-size `1.0em`

@pradyunsg you had changed the right sidebar items up to `1em` I believe in your latest PR because they were hard to read, but then also changed the left-sidebar items to be `0.9em` too...I feel like we should choose one-or-the-other here for both, no? Or is there a particular reason to keep them different?

**Comment by pradyunsg** [comment]
I don't recall why I made it 0.9em - that might've been unintentional.

**Comment by choldgraf** [comment]
haha bummer I kinda like the 0.9em better 😅 but if it's hard to read for some, then I think that should take precedence

**Comment by choldgraf** [comment]
@pradyunsg can you take a look at the current sphinx-book-theme site: https://sphinx-book-theme.readthedocs.io/en/latest/? Is the left sidebar font size acceptable to you?

**Comment by pradyunsg** [comment]
> Is the left sidebar font size acceptable to you?

Yea, it is. :)

**Comment by choldgraf** [comment]
Maybe we can make the right sidebar the same font size as the left sidebar then?

**Comment by choldgraf** [comment]
Also just FYI, gonna head to bed soon!

**Comment by choldgraf** [comment]
I opened up #168 which I think would make this no longer an issue for me

**Comment by choldgraf** [comment]
ok gonna close this, I think with the latest PRs on font sizes this is OK again
