### ISSUE TITLE
Add default LaTeX theme support

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-book-theme#161]
**Is your feature request related to a problem? Please describe.**

@AakashGfude is doing some work on developing a default LaTeX theme with the addition of a `cls` file. We feel the best place for this would be in this repository which would be the home for both `html` and `latex` default themes. 

**Describe the solution you'd like**

The proposal would be the add `html` and `latex` folders that contain the various components. 

**Describe alternatives you've considered**

Alternatives would be to setup separate `sphinx-book-theme.html` and `sphinx-book-theme.latex` repos.

**Additional context**

Given this is a **book** theme -- including both themes in the one project puts an emphasis on supporting both `html` and `latex` output.

**Comment by chrisjsewell** [comment]
I tend to disagree I'm afraid, I think the alternative solution is better. 
HTML/CSS & LaTeX are two very different beasts, requiring different expertise, tooling and development/testing environments, and attracting different contributors. 
I think it may over complicate the package, with minimal benefits (e.g. I don't think they would share any code/resources?)

**Comment by chrisjsewell** [comment]
But still definitely +1 on making the latex theme a prominent member of the EBP family 😀

**Comment by AakashGfude** [comment]
@chrisjsewell good point. I think the latex repo might also grow with time having extra stuff like pluggable package files, and lots of tests, etc. Separate repo makes sense in that way as well.

**Comment by choldgraf** [comment]
I think that's a good point @chrisjsewell - we should keep the Latex theme and the HTML theme "semantically linked" but not technically linked in order to make the maintenance a bit easier. As an example I have no idea how Latex works and if I showed up at a repository that I _thought_ was HTML, and found a buncha latex stuff, I'd probably be scared away lol.

The other thing is that the Latex theme might be complex-enough that it warrants its own testing infrastructure which would be very different from testing HTML, so 👍 from me.

**Comment by mmcky** [comment]
OK - Roger that.

My main reasoning on this suggestion was that there will be quite a few users wanting to build both `html` and `pdf` outputs and this will mean they will have to install two themes. But I guess both themes will be distributed with `jupyter-book` so shouldn't have to mess around with `config`. 

Should we make the target explicit in the names?

`sphinx-book-theme` -> `sphinx-book-html`

or leave `html` theme name as it is and use

`sphinx-book-theme-latex` for `latex`

**Comment by pradyunsg** [comment]
> sphinx-book-theme-latex

In case we're looking for more opinions, I like this. :3

**Comment by mmcky** [comment]
@AakashGfude let's transfer your theme work into a new repo `sphinx-book-theme-latex` that will support a default `latex` theme.

**Comment by AakashGfude** [comment]
Sure @mmcky . Will setup a repo.

**Comment by pradyunsg** [comment]
Looks like this issue can be closed now, given that we have a resolution. :)
