### ISSUE TITLE
Investigate why folders weren't being created in some build contexts

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#164]
In https://github.com/executablebooks/sphinx-book-theme/pull/152 @pradyunsg discovered that under some conditions, files would attempt to be placed in `_sources` before its parent folders were created. We fixed it by automatically creating those parent folders, but this may be an underlying bug in our build logic. 

Here's where we define the sources dir:

https://github.com/executablebooks/sphinx-book-theme/blob/c98448c5dfe78e8cd42e61a6c6eabe231827026d/sphinx_book_theme/launch.py#L27

it could be that we are making incorrect assumptions about the existence of that dir

**Comment by choldgraf** [comment]
Closing this as we haven't run into any bugs related to this since it was opened 1.5 years ago, we can re-open something if a problem pops up again

**Comment by pradyunsg** [comment]
Woah, it's been 1.5 years?!

**Comment by choldgraf** [comment]
I had the same thought lol
