### ISSUE TITLE
Set "readthedocs" ad placement explicitly

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#169]
Right now, if people host their documentation on readthedocs, it will automatically put an advertisement at the bottom of the page:

![image](https://user-images.githubusercontent.com/1839645/89735327-8c86c680-da16-11ea-9fb4-59aa3f3db9a4.png)

It's not too obtrusive, though it clashes a bit with our CSS and overlaps with some elements.

I believe that we can include some HTML that will instead tell RTD to put the add there instead of at the bottom, and so we can control how it looks etc a bit better. What do folks think about that?

I believe we need to add: https://github.com/pradyunsg/furo/blob/main/src/furo/theme/furo/sidebar/ethical-ads.html?rgh-link-date=2021-03-20T19%3A15%3A02Z

**Comment by chrisjsewell** [comment]
While your mentioning RTD, I would also link https://github.com/pandas-dev/pydata-sphinx-theme/issues/194

**Comment by 12rambau** [comment]
@chrisjsewell I've actually open an issue for this very purpose: https://github.com/pydata/pydata-sphinx-theme/issues/345

I'm just jumping here, Ware there any evolution on this matter since August ?

**Comment by choldgraf** [comment]
@12rambau nope - we'd still like it to happen - if anyone would like to give a shot at a PR I am happy to review!

**Comment by 12rambau** [comment]
I was looking on how you handling the ad placement in RDT and Google lead me here.

> if anyone would like to give a shot at a PR I am happy to review!

If only, I was good enough in HTML/CSS 😄, It's just that I was asking in my other issue to add the ad placement in there template but if the scruture is about to change it's better to wait...
