### ISSUE TITLE
Document or remove z-index hacks

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-book-theme#180]
**Describe the bug**

There are areas in the codebase where z-index values are set *really* high, which makes it difficult to position/stylize the components hierarchically (by overriding the stacking order).

Some of this stems from pydata-sphinx-theme, which is also setting z-index values of 2000 and similar (usually, a single digit z-index value is sufficient).

**To Reproduce**

1. Search "z-index" in the codebase.
2. Gasp at the large numbers. :P

**Expected behavior**

Title says it all. :)

Another thing we should do is set the z-index to be as low as possible.

**Additional context**

- https://css-tricks.com/rational-z-index-values/
- https://philipwalton.com/articles/what-no-one-told-you-about-z-index/

**Comment by choldgraf** [comment]
Usually this was done totally ad hoc to get something to always be on top, usually in a fit of CSS-induced frustration. Am all for making more sensible choices here

**Comment by pradyunsg** [comment]
What is this "CSS-induced frustration" you talk of? 🙃
