### ISSUE TITLE
Allow for header customization

### ISSUE THREAD

**Issue by lwasser** [executablebooks/sphinx-book-theme#182]
This related to [a discussion here](https://github.com/executablebooks/jupyter-book/issues/718#issuecomment-673578962)

**Is your feature request related to a problem? Please describe.**

I'd love to use jupyter book for my textbooks. [i have 3 currently on our learning portal](https://www.earthdatascience.org/). the problem is that because we have multiple books and a portal that is SEO optimized, we want to maintain visual branding of all of our content. This means that ideally we'd like to have the ability to add a header to the book with links back to our main site and to customize the css /colors potentially to better match our existing theme. The site currently is being redesigned btw.

As i'm considering this a footer element would be nice to have too - at CU we have to acknowedge certain things in the footer. 

**Describe the solution you'd like**

I'd like a simple way to adding a header with HTML to all book html pages.
This will likely mean we also need to be able to add stuff to the header (above the `<body>` tag in the `<head>` section - which might include css and also js.

**Describe alternatives you've considered**

i've considered creating our own theme but that seems like a lot of work to add a header and css to a page! i'd also have to learn a lot of new things to customize sphinx. 

**Additional context**

have a look at our website and you will see on the home page links to three textbooks. in the site they retain the site skin. they are not separate websites. 

thank you for considering this!

**Comment by ghutchis** [comment]
Yes, please. If a header + w/ adaptable CSS, I'd adopt this in a heartbeat for several projects.

**Comment by chrisjsewell** [comment]
Sounds reasonable 😄 
On the case of adaptable CSS, maybe I'm missing something, but can you not just use https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_css_files to add your own CSS?
(this is also mentioned in https://jupyterbook.org/advanced/sphinx.html?highlight=css#custom-css-or-javascript)

**Comment by ghutchis** [comment]
I _just_ found that part of the documentation - for me, that feature (loading additional CSS and JS) should be enough, although it's sometimes helpful to insert a `<script>` tag to a CDN, e.g.

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/3Dmol/1.4.0/3Dmol-min.js"></script>
```

The biggest thing would be to add HTML for a header / masthead, similar to the `extra_footer`:

```
html:
    extra_header: |
     <div class="masthead__menu">
       ..
     </div>
```

**Comment by lwasser** [comment]
@chrisjsewell it is very possible that i've forgotten about some of the docs associated with customization of the book! yes 

https://jupyterbook.org/advanced/sphinx.html?highlight=css#custom-css-or-javascript

the approach above would work for CSS and javascript... so i'm just back to wanting a header option!! sounds like @ghutchis  is also in a similar situation! :) thank you for the positive feedback.  

branding is so important to us.

**Comment by ghutchis** [comment]
Is there anything I can do to help on this?

**Comment by pradyunsg** [comment]
>  `<script>` tag to a CDN, e.g.

IIRC, you can "just" add `https://cdnjs.cloudflare.com/ajax/libs/3Dmol/1.4.0/3Dmol-min.js` as the path to the file, and Sphinx should do the right thing for it.

> would be willing to write some code if I can get some pointers.

All the HTML for the top bar is in: https://github.com/executablebooks/sphinx-book-theme/blob/master/sphinx_book_theme/topbar.html

I *think* we could get away by merely adding a few "strategically placed" Jinja2 blocks in topbar.html, and that can serve as an extension point for someone that wants to customize it.

In case, you wanna fiddle around with the styling... Most of the relevant SCSS is here: https://github.com/executablebooks/sphinx-book-theme/blob/master/sphinx_book_theme/scss/sphinx-book-theme.scss#L570. Be warned: there's a lot of... uhm... not-so-straightforward-to-understand things happening with the layouting of the top bar. :)

**Comment by choldgraf** [comment]
Yep - my guess is that the trickiest part of this will be making sure that the CSS behaves expectedly (because I believe right now we're hard-coding some rules that expect elements to be at the top of the viewport). Would love to see improvements to the CSS that do this more reasonably 👍

**Comment by ghutchis** [comment]
CSS may be beyond my ability, but I'll take a stab with some strategic Jinja2 and report back tomorrow.

**Comment by AllenDowney** [comment]
I would also like to be able to add a custom header and/or footer to the pages generated by JupyterBook. Has anyone figured out a good way to do this, and would you be able to write up the steps? Thank you!

**Comment by ghutchis** [comment]
I ended up adapting the pydata-sphinx theme.

**Comment by AllenDowney** [comment]
@ghutchis Would you be able to provide a brief step-by-step?

**Comment by jackgerrits** [comment]
+1 to this, would really like to be able to use a custom header

**Comment by lwasser** [comment]
@ghutchis i'd love to see your approach to doing this. @choldgraf had mentioned making a new theme that suits our needs but i'm not sure how that would get implemented when using jupyter book to build the book.

**Comment by choldgraf** [comment]
The most straightforward way to play around with other themes with Jupyter Book is to use the custom Sphinx configuration as documented here:

https://jupyterbook.org/advanced/sphinx.html#manual-sphinx-configuration

Basically you'd use something like:

```
...
sphinx:
  config:
    html_theme: pydata_sphinx_theme
```

This might be a bit unpredictable, but should work!

**Comment by choldgraf** [comment]
I added some documentation about this here: https://github.com/executablebooks/jupyter-book/pull/1369

**Comment by ghutchis** [comment]
Sorry, I've been a bit busy - I edited the sphinx configuration as indicated by @choldgraf  At the moment, I don't have the execute 🚀 , download, etc. button / menus. but I found it to be the easiest way to add a header. 

I found it was pretty easy to hack the `pydata-sphinx` theme .. particularly since Bokeh, Fairlearn, etc. have examples you can examine. (e.g., https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/sections.html .. edit the navbar to put the 🚀 back.)

**Comment by AllenDowney** [comment]
Thanks to everyone who worked on this!

**Comment by casperdcl** [comment]
Can this issue be re-opened?

- It's not actually fixed. Some other theme (`pydata-sphinx-theme`) implementing this has nothing to do with this theme (`sphinx-book-theme`)... unless I'm missing something?
- I think https://github.com/executablebooks/sphinx-book-theme/pull/559 is a "proper" fix, but it's still in draft. Any ETA?

**Comment by RobinChen121** [comment]
Can somebody help adding a google translation widget in the header bar?
This is my jupyter book site: [https://robinchen121.github.io/book-Python-Data-Science/intro.html](https://robinchen121.github.io/book-Python-Data-Science/intro.html)

I want to move the google translation widget to the header bar.
