### ISSUE TITLE
Code-cell toggle seems not working when Thebe live code triggered on

### ISSUE THREAD

**Issue by ajz34** [executablebooks/sphinx-book-theme#185]
**Describe the bug and Reproduce**

In ipynb-generated notebooks, if the code-cell metadata sets to `"type": ["hide-cell"]` or `"type": ["hide-output"]`, then Thebe live code triggered on, one may find toggling the hidden/expanded cell is not working.
If these code-cells are not expanded before Thebe live code is not triggered on, these cells may never be expanded again afterwards.

This problem may be on [jupyter book document](https://jupyterbook.org/interactive/hiding.html), section [Hide cell outputs](https://jupyterbook.org/interactive/hiding.html#hide-cell-outputs) and [Hide entire code cells](https://jupyterbook.org/interactive/hiding.html#hide-cell-outputs).

**Expected behavior**

I think situation of `hide-cell` should be working just the same as Thebe live code is not triggered on.

Situation `hide-output` may become an open question, since after Thebe triggered, code cell should be either toggled or expanded, but not input-expanded togethered with output-toggled.

**Environment**

- sphinx-book-theme version: 0.0.35

**Additional context**

This problem was first seen in [my own works](https://pycrawfordprogproj.readthedocs.io/en/latest/Project_01/Project_01.html).

I think this problem is somehow related to connection of sphinx configuration and thebe, so raise this issue in sphinx-book-theme 😂

**Comment by choldgraf** [comment]
Ah yep this is definitely a bug. Thanks for catching!

**Comment by choldgraf** [comment]
I believe that this one is now resolved, the "hide" buttons still work when thebe is toggled on (ref: https://sphinx-book-theme.readthedocs.io/en/latest/reference/notebooks.html). The "output" button behaves a bit strangely, because `thebe` clobbers the output, but I suspect this is an edge case that isn't a big problem
