### ISSUE TITLE
Main content section extra scroll-bar appears sometimes

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#186]
In https://github.com/executablebooks/meta/discussions/103 @ajz34 described some strange behavior where an "extra" scroll bar appears to the right. See the link below for an example:

https://pycrawfordprogproj.readthedocs.io/en/latest/Project_01/Project_01.html

I think this is probably dependent to certain code outputs, and is likely a CSS bug within the Sphinx Book Theme.

**Comment by pradyunsg** [comment]
The solution is to remove the "overflow-auto" from the `main` tag.

**Comment by pradyunsg** [comment]
Oh, that actually surfaces a different bug -- WHY IS THE PAGE SO TALL?

**Comment by choldgraf** [comment]
This should be resolved on the main branch! Please re-open if it persists

**Comment by ajz34** [comment]
Great! The recent commit is tested and works fine :smile: 
Seems that this fix is after v0.2.0. Look forwards to next release :laughing:
