### ISSUE TITLE
Max content width changed in 0.0.35 to 0.0.36?

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-book-theme#194]
@choldgraf @pradyunsg I note that moving to 0.0.36, the content does not expand as wide as before.
Is this expected/desired?

https://myst-parser.readthedocs.io/en/stable/ (0.0.35)

![image](https://user-images.githubusercontent.com/2997570/91227134-edecac00-e71d-11ea-8880-ae3ee5ada43d.png)

https://myst-parser.readthedocs.io/en/latest/ (0.0.36)

![image](https://user-images.githubusercontent.com/2997570/91227184-fe048b80-e71d-11ea-9f33-27719199b8ed.png)

**Comment by choldgraf** [comment]
I don't think it was intentional... Maybe it changed in the pydata theme?

**Comment by jorisvandenbossche** [comment]
This wasn't changed recently in the pydata theme, AFAIK ?

**Comment by chrisjsewell** [comment]
just turned out I hadn't used `panels_add_bootstrap_css` 🤦

**Comment by quantitative-technologies** [comment]
@chrisjsewell This is the exact effect I am trying to get: The expansion to the width of the screen. Can you explain how to use this `panels_add_bootstrap_css`?

I am using `jupyter-book` which uses this theme by default, btw.
