### ISSUE TITLE
Replace libsass with pure python implementation

### ISSUE THREAD

**Issue by hason** [executablebooks/sphinx-book-theme#195]
I want to create a docker image based on alpine linux for sphinx and this awesome theme. Libsass package is too complicated, it must be compiled and it is too heavy (~60MB) also. Would it be possible to replace it with another written in pure python? For example https://github.com/Kronuz/pyScss?

**Comment by chrisjsewell** [comment]
Thanks @hason, well @pradyunsg this is the pro for trying to make our previous setup work; whereby the SCSS is pre-compiled in the released package (and checked to be up-to-date with pre-commit)

**Comment by pradyunsg** [comment]
Any compliant SCSS compiler works TBH.

I don't remember if we compile the SCSS prior to release, but if we do, we could theoretically make the runtime SCSS compilation an optional feature?

**Comment by chrisjsewell** [comment]
> I don't remember if we compile the SCSS prior to release

You removed it in fbb8b18d03c95966639e3d3482c5a30d03684bd5 😉

**Comment by chrisjsewell** [comment]
Or yeh change the package, I don't see an issue with that
