### ISSUE TITLE
Support Sphinx language for some menu options

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#197]
In Sphinx, we are able to detect the language being used at build time:

https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language

We could use this along with a dictionary that chooses the right words/phrases for certain UI elements in the documentation (e.g. "search" and "contents"). Even if these are customizable it would be better to use the same internationalization mechanisms that Sphinx has to use reasonable defaults.

**Comment by pradyunsg** [comment]
We'd need a bank of terms we use in the theme + translations for the same.

**Comment by chrisjsewell** [comment]
See https://github.com/executablebooks/sphinx-book-theme/issues/188#issuecomment-697045582
