### ISSUE TITLE
Update mathjax to v3

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-book-theme#199]
**Is your feature request related to a problem? Please describe.**

Mathjax v3 is [60%–80% faster](https://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html#improved-speed), and has other advantages over mathjax v2, which is used by the sphinx-book-theme.

**Describe the solution you'd like**

Update mathjax to v3

**Comment by chrisjsewell** [comment]
This is not set by sphinx-book-theme. It is a sphinx option which is already updated in sphinx v4: https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjax
