### ISSUE TITLE
Javascript error in sphinx-book-theme.js

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-book-theme#202]
**Describe the bug**

Index page emits this js error:

```
sphinx-book-theme.js:15 Uncaught TypeError: Cannot read property 'offsetTop' of undefined
    at HTMLDocument.scrollToActive (VM375 sphinx-book-theme.js:15)
```

**To Reproduce**

1. Go to https://sphinx-book-theme.readthedocs.io/en/latest/index.html
2. Open js console
3. See error

**Expected behavior**

No error. :stuck_out_tongue:

**Comment by pradyunsg** [comment]
Which browser and OS are you on?

**Comment by pradyunsg** [comment]
And what is the documentation that this occurs on? Seems to me that the code isn't robust to empty pages / pages not in the toctree. :)

**Comment by akhmerov** [comment]
I observe the error on both latest chrome and firefox, the page is linked in the issue description (it occurs in your docs), and I agree with your assessment.

**Comment by pradyunsg** [comment]
> the page is linked in the issue description

Huh. Not sure how I missed that! Whoops! 😅

**Comment by chrisjsewell** [comment]
Fixed in https://github.com/executablebooks/sphinx-book-theme/commit/4a94b9272b5010b70683b92bdd597ecaa52651da
