### ISSUE TITLE
CSS updates are not visible sometimes in a browser

### ISSUE THREAD

**Issue by AakashGfude** [executablebooks/sphinx-book-theme#204]
**Describe the bug**

The updates to CSS are sometimes not visible in a browser, probably because of browser caching the old CSS file. @jstac and @choldgraf have encountered this problem in the past.

**To Reproduce**

1. Publish a change in the CSS file
2. verify in a browser which already has `sphinx-book-theme` assets cached

**Expected behavior**

The browser should load the latest style assets everytime. 

**Possible solution**

Generate a hashed CSS file from SCSS in the pipeline https://github.com/executablebooks/sphinx-book-theme/blob/master/sphinx_book_theme/__init__.py#L28. Hence, every time there is a diff, the filenames are different and the browser takes the newer one.

**Comment by chrisjsewell** [comment]
> Generate a hashed CSS file from SCSS

That doesn't sound like a very standard practice? How to other website generators deal with this?

Surely you can disable caching in your browser e.g. for firefox

<img width="1407" alt="Screenshot 2020-09-01 at 03 52 24" src="https://user-images.githubusercontent.com/2997570/91789573-d07c7e00-ec06-11ea-8b59-f0e731fc0a33.png">

**Comment by AakashGfude** [comment]
@chrisjsewell yes, you can disable cache in your browser, but someone who is not technical won't do it usually. And it will be like an additional step for users.

**Comment by AakashGfude** [comment]
@chrisjsewell hashing of static files, is standard practice for production builds in the web development world.  For example https://create-react-app.dev/docs/production-build/

**Comment by chrisjsewell** [comment]
Thanks for the link, well if it is common/good practice, then I'm certainly not adverse to it. Someone just has to get it working with sphinx.

As an addendum, we should also look into adding source maps to sass: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

**Comment by AakashGfude** [comment]
@chrisjsewell +1 for adding source maps.

**Comment by chrisjsewell** [comment]
fixed in ef8815fb4a793747fd259098002da7117eabd2e6
