### ISSUE TITLE
Build doesn't work when using symbolic links to external content

### ISSUE THREAD

**Issue by ocayrol** [executablebooks/sphinx-book-theme#206]
For some of our documents, we are using textual contents that are shared between several documents. In order to achieve this with the Sphinx infrastructure, in the source directory, we are inserting symbolic links towards directories located elsewhere on the file system (in a "shared library").

When building with the sphinx-book-theme, Sphinx stops and displays this error:

```console
$ make html
[...]
Theme error:
An error occured while generating the page: contents.
The reason is: ValueError("'/home/user/shared-doc-modules/Python/intro' does not start with '/home/user/my-doc'")
```

A quick look at the `sphinx_book_theme/__init__.py` file shows at line 53 and 54:

```python
path_from_page_dir = path_rel_from_page_dir.resolve()
page_rel_root = path_from_page_dir.relative_to(source_dir).joinpath(path_rel.name)
```

The `Path.resolve` call resolves the symbolic link and thus, after, the file path is not relative to the source directory anymore and the `Path.relative_to` call raises the exception.

Is there any reason to use `Path.resolve` at line 53 instead of `Path.absolute`? Should it be possible to make this change so the build will work in our use case?

**Environment**

Python: 3.8.2
Sphinx: 3.2.1
sphinx-book-theme: 0.0.36

**Comment by choldgraf** [comment]
interesting - can you try making a PR with `absolute()` and see if that fixes this? I don't think there's a strong reason to use `resolve()` over it

**Comment by ocayrol** [comment]
It definitely works.

**Comment by pradyunsg** [comment]
> I don't think there's a strong reason to use `resolve()` over it

There is -- absolute is not a documented attribute on `pathlib`. :)

**Comment by ocayrol** [comment]
You're right! Sorry, I didn't check the documentation. But nevertheless, someone has coded the method in the Path class... And it makes sense to have something to build an absolute path without resolving the symbolic links.

Strictly sticking to the documentation, we could go with:

`pathlib.Path(os.path.abspath(path_rel_from_page_dir))`

and it will work for our use case. Should this be conceivable?

**Comment by choldgraf** [comment]
@pradyunsg is there a reason `absolute` isn't documented?

@ocayrol I'm fine using `os.path` if we want to avoid `absolute` in pathlib

**Comment by pradyunsg** [comment]
https://discuss.python.org/t/2573/ has the discussion pertaining to pathlib's absolute method. There's a CPython bug pertaining to it, linked from the first post in that thread.

I feel like I'm responsible for sending triple digit numner of people there. 🙈

**Comment by ocayrol** [comment]
Thanks for the link to the Python discussion. Indeed, computing the absolute path can be quite difficult in the *exotic* cases.

I'm creating a new merge request using os.path to circumvent the problem until a consensus emerges on the pathlib side.
