### ISSUE TITLE
What elements/styling do we want to bring over from Furo?

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-book-theme#217]
As I'm completing my side-quest of writing a [new Sphinx theme from scratch](https://github.com/pradyunsg/furo), now, I should be able to make a  decently sized chunk of time in a few weeks to work on the bazillion issues I filed in this repository on that fateful day.

Before I do that, I figured it'd be a good idea to have a discussion about what stuff we might want to bring over from Furo's design and implementation into this theme. :)

- [x] #112 
- [x] #147
- [ ] #148 
- [x] #153 
- [x] #219

**Comment by pradyunsg** [comment]
#219 is one that I can think of. :)

**Comment by chrisjsewell** [comment]
Just #148 and #112 are the priority changes that I was starting to think about implementing in your hiatus 😜

**Comment by choldgraf** [comment]
those are precisely the two things I was going to mention as well @chrisjsewell 

I also like some of the design aspects a little bit more (nothing major, but stuff like your "previous/next" page buttons I like a bit more)

![image](https://user-images.githubusercontent.com/1839645/94075796-ac006580-fdb0-11ea-8b40-a82204d37287.png)

another one is the right drawer "contents" when the screen is narrow enough:

![2020-09-23_15-22-41](https://user-images.githubusercontent.com/1839645/94075779-a571ee00-fdb0-11ea-915e-9e0d0065f69e.gif)

**Comment by choldgraf** [comment]
ah I also like your `search` page more:

![image](https://user-images.githubusercontent.com/1839645/94075997-08638500-fdb1-11ea-9c08-0ddd730feb3f.png)

**Comment by chrisjsewell** [comment]
Yep Furo looking good by the way

> ah I also like your search page more

for this, I've also already mentioned about a search-as-you-type UI: https://github.com/pandas-dev/pydata-sphinx-theme/issues/202

**Comment by choldgraf** [comment]
@pradyunsg out of curiosity, when do you think you'll have some cycles to work towards this? I've added this issue to the v0.1 milestone (https://github.com/executablebooks/sphinx-book-theme/milestone/1), so trying to get an idea for what kind of timetable to expect :-)

**Comment by pradyunsg** [comment]
Not 100% sure TBH -- depends on how the upcoming 20.3 release of pip goes. If it goes *really* well, should be able to get to these in ~15 days from now?

#219 and #112 should be easier, relatively. #148 might need reworking the HTML skeleton, soooo I'll do that last, I think?

**Comment by choldgraf** [comment]
OK - well any improvements that you can make at any time would be appreciated :-)

**Comment by pradyunsg** [comment]
FTR: #112 got a PR (and it's not me :P) -- #226.

**Comment by choldgraf** [comment]
@pradyunsg nice! Perhaps we should collect a short to-do list at the top-level comment of this issue in case others find the time and want to contribute on those as well?

**Comment by pradyunsg** [comment]
#219 is also done (via #237). That leaves us with only #147, #148 and #153 I think.

**Comment by pradyunsg** [comment]
> Perhaps we should collect a short to-do list at the top-level comment of this issue in case others find the time and want to contribute on those as well?

Added! :)

**Comment by pradyunsg** [comment]
*pulls head out of sand*

So what was I doing again? Oh, right. #147 coming up soon-ish. :3

> depends on how the upcoming 20.3 release of pip goes.

Yea, this has been interesting. Go look at https://github.com/pypa/pip/issues/ 8936 (yes, the space is intentional) if you're wondering what the heck I was upto.

**Comment by choldgraf** [comment]
+1 to your reasoning in that thread @pradyunsg 👍 this is gonna be a stressful week for a lot of the open source community for a variety of reasons

**Comment by pradyunsg** [comment]
#255 fixes #153. #257 fixes #147. 🌈

**Comment by choldgraf** [comment]
Can I assume from this that your work on getting out a new pip is complete?! If so, congratulations!!!

**Comment by pradyunsg** [comment]
Not yet, but I expect this week to be a productive one! Next week, I'll be moving countries and I'll cut the big-fish right before that. :)

**Comment by pradyunsg** [comment]
Only #148 is left. Closing since. I think we have sufficient ways to track work on that. :)

**Comment by choldgraf** [comment]
Many thanks to you @pradyunsg for following through and making these improvements, it's much appreciated and really exciting to see the energy in the Sphinx world these days :-)
