### ISSUE TITLE
Breaking up main.scss into modular bits?

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-book-theme#219]
The title says it all really.

Sass does support import statements, allowing you to break up a single CSS file across multiple modules that can be relatively-easily referenced and reasoned about.

[I've been doing this in Furo](https://github.com/pradyunsg/furo/tree/master/src/furo/assets/styles) and it makes it *really* nice to be able to navigate through the codebase, knowing which file will have the bits for the component I wanna tweak. :)

**Comment by choldgraf** [comment]
+1 from me

**Comment by chrisjsewell** [comment]
Yeh this and adding customisable CSS variables, I was already planning to implement anyway, as per sphinx-panels 👍

**Comment by pradyunsg** [comment]
This is done now, with #237. :tada:

**Comment by choldgraf** [comment]
thanks for this @chrisjsewell - it makes it much easier to quickly navigate to the CSS you want
