### ISSUE TITLE
Auto-add custom 404 page

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-book-theme#221]
I've noticed now a few sphinx docs provide their own 404 page, e.g. https://github.com/wpilibsuite/frc-docs/blob/master/source/404.rst, which is not something I'd previously considered

It might be nice to have a default one be added by the theme?

**Comment by chrisjsewell** [comment]
perhaps with an option to toggle it off

**Comment by choldgraf** [comment]
I think it's a nice idea 👍

**Comment by chrisjsewell** [comment]
Given that the `sphinx-notfound-extension` is maintained by the RTD organisation, it probably makes sense to get that working with sphinx-book-theme (see #227) and recommend it in the documentation
