### ISSUE TITLE
Design: more space before text that follows code blocks

### ISSUE THREAD

**Issue by fmaussion** [executablebooks/sphinx-book-theme#223]
**Disclaimer:** I am not a web designer

I find that the looks of text following code blocks is a bit awkward and misleading:

![image](https://user-images.githubusercontent.com/10050469/94447343-f0717400-01a9-11eb-8d23-419ef84ee97a.png)

For me the "For example" comes too close to the preceding code block. I would prefer to have the same space before and after the block.

**Comment by choldgraf** [comment]
Yep I think this is probably a bug, thanks for noticing 👍 I agree we should have at least the same amount of space before/after by default
