### ISSUE TITLE
Support custom 404 page

### ISSUE THREAD

**Issue by melaniewalsh** [executablebooks/sphinx-book-theme#227]
**Describe the bug**

I know that Jupyter Book will not work predictably with custom Sphinx extensions, but I've been trying to integrate this [Sphinx Not Found Page](https://github.com/readthedocs/sphinx-notfound-page) extension into my Jupyter Book so that I can have a custom 404 page. And I think this could be potentially useful for all Jupyter Book users.

Anyway, when I use this extension, I get the following error:

```
An error happened in rendering the page 404.
Reason: ValueError("'/' does not start with '/Users/melaniewalsh/mybookname'")
```

@humitos has been helping me [debug this issue](https://github.com/readthedocs/sphinx-notfound-page/issues/114#issuecomment-704182017) and usefully identified that there seems to be a problem in `sphinx-book-theme` in the function [`find_url_relative_to_root`](https://github.com/executablebooks/sphinx-book-theme/blob/master/sphinx_book_theme/__init__.py#L78_), which is called from [`generate_nav_html`](https://github.com/executablebooks/sphinx-book-theme/blob/master/sphinx_book_theme/__init__.py#L101).

So I was wondering if there were any suggestions about how to make the Sphinx Not Found extension work with the Sphinx Book Theme. Thanks!

**To Reproduce**

1. Add Sphinx Not Found Page extension to `_config.yml`

```
sphinx:
  extra_extensions: 
  - notfound.extension  
  config:
    notfound_context:
        body: "<h1>Page not found.</h1>"
    notfound_no_urls_prefix: True
```
2. Build Jupyter Book
3. See error

```
An error happened in rendering the page 404.
Reason: ValueError("'/' does not start with '/Users/melaniewalsh/mybookname'")
```

**Expected behavior**

Custom 404 page is built that preserves CSS and JavaScript from Sphinx Book Theme

**Environment**

- Python Version [e.g. 3.7.1]: 3.8
- Package versions or output of `jupyter-book --version`:
Jupyter Book: 0.8.2
MyST-NB: 0.10.1
Sphinx Book Theme: 0.0.36
MyST-Parser: 0.12.10
Jupyter-Cache: 0.4.1
NbClient: 0.4.0
- Operating System: Mac OS

**Comment by melaniewalsh** [comment]
Sorry I just realized that a custom 404 page was previously mentioned by @chrisjsewell #221! The Sphinx Not Found Page extension wouldn't be necessary if a custom 404 page was integrated in a different way

**Comment by chrisjsewell** [comment]
Oh yeh was going mention. 
I didn't know about this extension though so thanks for pointing it out 😀
Will have at look to see if any of it's implementation should be incorporated here, or we just allow for comparability with it

**Comment by humitos** [comment]
I'm the author of the `[sphinx-notfound-extension`](https://github.com/readthedocs/sphinx-notfound-page/). Let me know if I can be useful in some way here.

I don't see specific needs in #221 that won't allow people using sphinx-book-theme to use the extension. In fact, in the description of the issue, the linked project using a custom 404 page is using the sphinx-notfound-page :smile: 

If there is anything needed to be added to the extension to make it compatible with the sphinx-book-theme, I'd be happy to incorporate it.

**Comment by chrisjsewell** [comment]
thanks @humitos!
Yeh I'm sure we can work out the issue to support this extension and will let you know 😄

**Comment by melaniewalsh** [comment]
Hey! I just wanted to share that I was finally able to get the [sphinx-notfound-extension](https://github.com/readthedocs/sphinx-notfound-page/) working and create a custom 404 page in my Jupyter Book.

I needed to add a "url prefix" to my own repository, which I did in the [config_.yml file here](https://github.com/melaniewalsh/Intro-Cultural-Analytics/blob/master/book/_config.yml#L78-L83).

You can see an example of the[ custom 404 page here](https://melaniewalsh.github.io/Intro-Cultural-Analytics/05-Text-Analysis/blah).

Thanks for the great extension, @humitos!

**Comment by choldgraf** [comment]
ah that's very cool! Thanks for sharing your solution!

**Comment by choldgraf** [comment]
@melaniewalsh - any interest in making a quick post to the [jupyter book discussions board](https://github.com/executablebooks/meta/discussions) that shows off this pattern? Maybe others would find it useful!

**Comment by humitos** [comment]
Thanks @melaniewalsh for sharing the solution!

> any interest in making a quick post to the [jupyter book discussions board](https://github.com/executablebooks/meta/discussions) that shows off this pattern? Maybe others would find it useful!

Hehe, I was about to suggest adding an entry in the FAQ of the sphinx-notfound-page project at https://sphinx-notfound-page.readthedocs.io/en/latest/faq.html

Either work to me. So, happy to have it documented somewhere.

**Comment by melaniewalsh** [comment]
@choldgraf Sure, I'd be happy to write a quick post for the Jupyter Book discussion board! Also @humitos I could add an entry to the sphinx-notfound-page FAQ, too.

But yes I think this issue is closed 🎉

**Comment by choldgraf** [comment]
amazing! thanks for being so helpful @melaniewalsh :-)
