### ISSUE TITLE
Make images display at the left by default

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#239]
Right now, we are causing _all_ images to be centered on the page by default:

https://github.com/executablebooks/sphinx-book-theme/blob/master/src/scss/_page.scss#L80

This is actually a departure from what most sphinx themes do by default, and also results in some wacky-looking behavior like this:

![image](https://user-images.githubusercontent.com/1839645/97120691-e7ab8980-16e6-11eb-84e4-9ad8941f803b.png)

What do folks think about changing our default image behavior to be the same as what other Sphinx themes do, and then using a `center` class for when users want to explicitly center an image.

@pradyunsg what does Furo do w/ images?

**Comment by chrisjsewell** [comment]
Yeh was gonna bring this up. Left would be better I think (didn't @najuzilu have an issue/PR about this?)

With these badges actually it would be ideal if they actually mirrored the Markdown and were inline. But not sure what this would require in markdown-it-py/myst-parser (without messing up normal images)

**Comment by pradyunsg** [comment]
https://pradyunsg.me/furo/reference/images/

No custom layout CSS for the default. There's a bit of CSS for alignment, but nothing specific for img's with align-default.

**Comment by choldgraf** [comment]
OK cool - I am +1 on:

- No opinionated styling added for images (beyond maybe whitespace above/below)
- Figure directives result in centered images by default

**Comment by pradyunsg** [comment]
Awesome! ^>^
