### ISSUE TITLE
Disable 'Download this page...' dropdown menu

### ISSUE THREAD

**Issue by bknaepen** [executablebooks/sphinx-book-theme#244]
**Is your feature request related to a problem? Please describe.**

I would like to be able to disable the download dropdown menu from the topbar.

**Describe the solution you'd like**

An extra option in the _config_yml similar to:

```
use_issues_button: false
```

**Describe alternatives you've considered**

Currently I have added this to my css file to hide the menu:

```
[aria-label="Download this page"] {
display: none;
}
```

Cheers,
Bernard.

**Comment by choldgraf** [comment]
closed by #245 !
