### ISSUE TITLE
TOC not showing in versions newer than 0.0.36

### ISSUE THREAD

**Issue by HTenkanen** [executablebooks/sphinx-book-theme#247]
Hi guys,

I was building my docs with sphinx-book-theme and noticed that with the newest versions of the theme the TOC is not showing on the left panel. The last version that seems to work normally is 0.0.36.  

Found one reference to this issue but not sure if related: https://github.com/executablebooks/sphinx-book-theme/pull/91#issuecomment-629728686

Using `sphinx==3.3.0`

**Comment by choldgraf** [comment]
Hmm - does this work differently with Sphinx 3.2? Also please provide a link to your documentation / repo / etc if possible, it's hard to debug otherwise!

**Comment by pradyunsg** [comment]
Thanks for filing this @HTenkanen! If you could share the exact reproduction steps for this issue, that's be a big in trying to diagnose what's happening here.

**Comment by HTenkanen** [comment]
Hi @choldgraf @pradyunsg, Thanks for your quick replies, and sorry for being a bit slow on my side.

But here are the docs in ReadTheDocs which I am using to build the docs:
https://pyrosm.readthedocs.io/en/latest/

And here you can check the project and my configuration (latest in the develop branch):
https://github.com/HTenkanen/pyrosm/tree/develop

**Comment by HTenkanen** [comment]
It also seems that the right panel is going on top of ReadTheDocs selection panel:
![image](https://user-images.githubusercontent.com/6659534/98660496-0bf5a000-234e-11eb-9165-f931d9cc38cb.png)

**Comment by HTenkanen** [comment]
These kind of errors can be found from the console. Most of them relate to thebelab which is probably not related to this issue but the `querySelectorAll` of null might be something relevant:

![image](https://user-images.githubusercontent.com/6659534/98660833-6bec4680-234e-11eb-88fd-671089a6e9a3.png)

**Comment by HTenkanen** [comment]
@choldgraf @pradyunsg 

Sorry, nevermind, I figured out what is going on. These mysterious issues were due to template that I used previously with `pydata_sphinx_theme` to customize the look and forgot to drop those out when updating my sphinx to use `sphinx-book-theme`. 🤦 Now things are working normally. Sorry for bothering!

**Comment by pradyunsg** [comment]
No worries! Glad you figured it out! ^>^

**Comment by choldgraf** [comment]
Ah those pesky templates, i have done this many times as well, glad you got it sorted!
