### ISSUE TITLE
Issue on page /configure.html

### ISSUE THREAD

**Issue by maartenbreddels** [executablebooks/sphinx-book-theme#251]
Hi,

great template. I'm trying out the various options, but I get the impression that `extra_sidebar` does not seem to do anything.

cheers,

Maarten

**Comment by choldgraf** [comment]
Hey @maartenbreddels 👋 - ah I think this one is a mismatch between the docs and `master`...it has been a little while since we released. Can you try with master and we'll get a new release soon? (need to wait for the pydata theme to make a release first)

**Comment by maartenbreddels** [comment]
Hi ✋ . Yeah, I tried master and also that didn't do much. I don't need the feature, but the 'report issue' was so easy to click 👍

**Comment by choldgraf** [comment]
dang it! what did you try? could you share the `conf.py` config that didn't work?

**Comment by choldgraf** [comment]
yep - was a docs bug. Use `extra_navbar` instead of `extra_sidebar` and see if that works
