### ISSUE TITLE
line numbers misaligned for literalinclude

### ISSUE THREAD

**Issue by rscohn2** [executablebooks/sphinx-book-theme#258]
line numbers are misaligned for literalinclude

Tried 0.39 and master

Add this to a document:

```
.. literalinclude:: code.cpp
   :linenos:
```

Where code.cpp is:

```
a
b
c
d
```

and

`make html`

See the attached screenshot where the line numbers are half a line lower than the code.

<img width="568" alt="lineno" src="https://user-images.githubusercontent.com/1936730/98670782-3846f780-2321-11eb-8f9a-930daf0e2109.png">

This might be related: https://github.com/readthedocs/readthedocs.org/issues/3470

**Comment by rscohn2** [comment]
Here is an online example. If someone could diagnose the css in it, I could find the problem in the source code

https://sycl.readthedocs.io/en/latest/iface/platform.html

**Comment by choldgraf** [comment]
huh that is weird - setting `padding-top` to 0 doesn't seem to fix it, even though it looks like the padding on the top is the issue here. @AakashGfude have you run into something like this before where the padding and the CSS rule don't match correctly?

**Comment by AakashGfude** [comment]
@choldgraf , it was a `vertical-align` property issue here actually. making it `baseline` or `top` fixes the issue. I will open a PR for this.

**Comment by rscohn2** [comment]
Thanks for the quick resolution.
