### ISSUE TITLE
Code blocks with captions have a different line width

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-book-theme#261]
**Describe the bug**

Code blocks with a caption have a different width from regular code blocks

![image](https://user-images.githubusercontent.com/2069677/98972608-f087c200-2512-11eb-9260-fa190e1c831f.png)

**To Reproduce**

1. Go to https://sphinx-book-theme.readthedocs.io/en/latest/reference/demo.html#code-blocks
2. View the result.

**Expected behavior**

Same width of code blocks regardless of caption

**Environment**

This repository :)

**Comment by choldgraf** [comment]
@akhmerov think you could re-title this to be only about the first issue you bring up, since #258 covers your second point? :-)

**Comment by fmaussion** [comment]
:scream: OMG and there is still a python 2 snippet in the docs!

**Comment by fmaussion** [comment]
https://github.com/executablebooks/sphinx-book-theme/pull/262

**Comment by akhmerov** [comment]
Thanks, I fixed the issue description to avoid duplication.

**Comment by choldgraf** [comment]
This is now fixed!

![chrome_NvQJRi5cx8](https://user-images.githubusercontent.com/1839645/155575953-189ebea3-834d-4e5e-a9ba-0399a6f9f577.png)
