### ISSUE TITLE
"use_download_button" argument is not working

### ISSUE THREAD

**Issue by Ankur-singh** [executablebooks/sphinx-book-theme#264]
the docs shows, that you can use "use_download_button" to turn on/off the download button on page. But for some reason its not working. 

The error says, that the config value "use_download_button" is unknown. 
![image](https://user-images.githubusercontent.com/14893062/99078112-cfdb6d00-25e3-11eb-9f00-3fea720f6d9b.png)

**Comment by choldgraf** [comment]
ah - this is because we haven't yet released a new version of the Sphinx Book theme...if you use the `master` branch of that theme then it should work, and in general this should work once a new version is released! Does it work for you on master?

**Comment by dbausch-rea** [comment]
I think there's also missing that key in jupyter-book's config.py
https://github.com/executablebooks/jupyter-book/blob/edae9e5e815c2d88c03b6e34737759bffbdcdff1/jupyter_book/config.py#L219

**Comment by dbausch-rea** [comment]
And the config scheme also needs to be updated
https://github.com/executablebooks/jupyter-book/blob/edae9e5e815c2d88c03b6e34737759bffbdcdff1/jupyter_book/config_schema.json#L89

**Comment by choldgraf** [comment]
Is this documented in Jupyter Book? I don't think it should be (since as you mention the config hasnt' been added to it yet...)

**Comment by choldgraf** [comment]
Closing this one as I believe it is now resolved
