### ISSUE TITLE
Support Numpy Style Docstrings

### ISSUE THREAD

**Issue by dustindall** [executablebooks/sphinx-book-theme#266]
I use numpy style docstrings and when testing this theme I noticed it was concatenating the type and the parameter in docstrings.

I then ran a small test using a clean sphinx build (only modification being the addition  of the numpydoc extension in conf.py) and the following docstrings -

```python
def test_standard(a: int, b: int):
    """Test standard docstring.
    
    :param int a: This is a.
    :param b: This is b.

    """

def test_numpy(a: int, b: int):
    """Test numpy docstrings.
    
    Parameters
    ----------
    a : int
        This is a.
    b : int
        This is b.
    """
```

The sphinx_book_theme produced -
![image](https://user-images.githubusercontent.com/8218382/99658521-3cf86380-2a25-11eb-829a-e934184c77c6.png)

The pydata_sphinx_theme produced -
![image](https://user-images.githubusercontent.com/8218382/99658716-80eb6880-2a25-11eb-8267-befcde276891.png)

I'm using -

- sphinx 3.2.1
- numpydoc 1.0.0
- sphinx-book-theme 0.0.39
- pydata-sphinx-theme 0.4.1

Let me know if I need to provide any more information.

Thanks,
Dustin

**Comment by chrisjsewell** [comment]
thanks @dustindall can you also show the expected outcome, e.g. the results from the default sphinx theme (alabaster) or the `sphinx-rtd-theme`.

I actually pretty much copy-pasted the CSS from `sphinx-rtd-theme`, so it should in principle be very similar and may be a bug there.

**Comment by pradyunsg** [comment]
*puts on speculation hat*

This is likely due to a .classifier inside the dl for the API documentation.

**Comment by choldgraf** [comment]
note that this might be a fix that would be best-made in the [pydata sphinx theme](https://pydata-sphinx-theme.readthedocs.io/) since I believe we inherit this kinda CSS from there

**Comment by chrisjsewell** [comment]
> since I believe we inherit this kinda CSS from there

No we don't: 16efec349d0435f0a10828cc3493a8014915fb8d

and I don't want to use their implementation 😛: https://github.com/pandas-dev/pydata-sphinx-theme/issues/193

**Comment by choldgraf** [comment]
hmmm - well my more general point was that if something is broken in SBT that the PST would benefit from, we might as well kill two birds with one stone and improve it in PST unless there's some technical blocker

**Comment by dustindall** [comment]
@chrisjsewell, both alabaster and sphinx-rtd-theme correctly show the separation. 

Below are the results from alabaster -
![image](https://user-images.githubusercontent.com/8218382/99748971-33addc00-2aa3-11eb-8a05-4cf3ba848928.png)

And the results from sphinx-rtd-theme -
![image](https://user-images.githubusercontent.com/8218382/99749093-72439680-2aa3-11eb-8a1b-d1731d9f839d.png)

Sorry I'm no help on the CSS front.

**Comment by chrisjsewell** [comment]
Thanks that's helpful

**Comment by raphaeltimbo** [comment]
In my case I have just added the following to my custom.css:
```css
.classifier::before {
    content: " : ";
}
```
