### ISSUE TITLE
Table of Contents overlaps with sidebar content

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#267]
I just noticed that our table of contents now overlaps with the sidebar even when it is closed:

![image](https://user-images.githubusercontent.com/1839645/100819945-03026680-3402-11eb-93a4-84d8598d0fef.png)

could this be related to the recent topbar rework that @pradyunsg did?

**Comment by pradyunsg** [comment]
👀

I swear I tested this.

**Comment by pradyunsg** [comment]
> could this be related to the recent topbar rework that @pradyunsg did?

Pretty sure, yea.

**Comment by choldgraf** [comment]
@pradyunsg any intuition for what happened? :-)

**Comment by pradyunsg** [comment]
Yea... Based on a quick look -- removing `.bd-toc { background: white; }` should fix this.
