### ISSUE TITLE
Right 'contents' toc overlaps margin content 🐛.

### ISSUE THREAD

**Issue by MantiMantilla** [executablebooks/sphinx-book-theme#269]
**Describe the bug**

Following up on trying out the latest _SBT_ changes ([discussion here](https://github.com/executablebooks/jupyter-book/issues/1101)), I realized that the 'contents' table covers the right margin content with a transparent box (Most likely traceable to #268 🐛). This usually wouldn't be an issue, except when you need that content to be interactive, say, with code to copy or dropdown admonitions.

This transparent box also causes a weird behavior wherein the _toc_'s contents fade away when expecting a collision with margin content WAY early (Earlier than before, see comparison).

Proper behavior: (From regular `pip install`)

![GIF 06-Dec-20 10-54-15 PM](https://user-images.githubusercontent.com/28278569/101307654-ffae1700-3815-11eb-8583-56592afd5891.gif)

Current behavior: (`git clone` and `install`)

![GIF 06-Dec-20 11-18-29 PM](https://user-images.githubusercontent.com/28278569/101309054-65e86900-3819-11eb-9dc7-073228d899f8.gif)

Notice how in the current behavior, the contents box disappears when the cursor is not in the margin, this happens even when margin content is coming up (when scrolling down) but is still not on the screen.

**To Reproduce**

1. Create a long .md file with dropdown class, margin admonitions,
2. add it to a book or build a book around it,
3. navigate to the page in the built book from your web browser,
4. scroll down,
5. notice the margin content can't be interacted with and that the _toc_'s contents disappear when scrolling down and margin content is coming up but not there yet.

**Some Info**

The working [repo](https://github.com/copa-uniandes/optimizacion)

The broken [repo](https://github.com/MantiMantilla/optimizacion).

Specifically, visit [here](https://mantimantilla.github.io/optimizacion/Guias/MS%20Office/MS%20Office.html).

I also built a book specifically to showcase this issue. A minimal working example, if you will (see [repo](https://github.com/mantimantilla/jb-margin-issue) or visit the [site](https://mantimantilla.github.io/jb-margin-issue/intro.html)).

**Environment**

Built on Ubuntu Latest (Github Actions)

```console
Jupyter Book: 0.8.3
MyST-NB: 0.10.1
Sphinx Book Theme: 0.0.39
MyST-Parser: 0.12.10
Jupyter-Cache: 0.4.1
NbClient: 0.5.1
```

**Comment by fmaussion** [comment]
This has been solved yesterday on master: https://github.com/executablebooks/sphinx-book-theme/pull/268 

If you can, try to install master and see if solves your problem?

**Comment by MantiMantilla** [comment]
The last [repo](https://github.com/mantimantilla/jb-margin-issue) I provided builds from the _SBT_ master branch which gets cloned on a Github Actions workflow, meaning it is already using the latest changes. There WAS a slight improvement on this recently in that the box that covers the right margin used to be white. It is now transparent.

**Comment by choldgraf** [comment]
Ah right, so there are two issues - one is that the box is too vertically-big, the other is that the box was white. #268 improved the "background is white" issue but not the box itself. @MantiMantilla have you been able to figure out a CSS rule to make the box properly-sized? I think that'll be the fix to this

**Comment by MantiMantilla** [comment]
I'll give this a try! Will report back in a few hours.

**Comment by pradyunsg** [comment]
Setting height: auto seems to make things work as expected. I'm not a 100% familiar with the CSS, so IDK why there's a height set and a z-index of 999, but setting height: auto prevent the overlap/overlay behaviour.

We can also likely remove the transparent background stuff, because that's "hiding" the underlying issue; of a mis-managed height.

**Comment by DrDrij** [comment]
I [have a PR](https://github.com/executablebooks/sphinx-book-theme/pull/300) which sets an `auto` height for the right column. I couldn't find any reason for the right column to use full vertical browser height. The solves the issue when hovering over the right side of the window when the TOC is hidden.
The TOC will now only show when hovering over the "Contents" title in the top bar.


https://user-images.githubusercontent.com/5886045/110885848-aa653280-833b-11eb-9f3e-eefb0b258cbb.mov

**Comment by choldgraf** [comment]
Closing this one as I think that @DrDrij nailed it!
