### ISSUE TITLE
Reduce the spacing around the display math element.

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-book-theme#272]
**Is your feature request related to a problem? Please describe.**

Check out the spacing below and above a display math element embedded in text:

- Example from the theme docs:

---

![image](https://user-images.githubusercontent.com/2069677/103489879-08473c80-4e18-11eb-95eb-7b3d9ddf8549.png)

---
- Example with more text:

---
![image](https://user-images.githubusercontent.com/2069677/103489887-15642b80-4e18-11eb-9b9b-67bada5df90c.png)

---
I think the spacing between the equation and the text around does not look good—the top margin is way larger than the bottom one.

**Describe the solution you'd like**

Not the best CSS expert here, but I imagine adjusting bottom margin on a `<p>` followed by a mathjax div would do.

**Describe alternatives you've considered**

...some other CSS adjustments.

**Comment by choldgraf** [comment]
+1 from me, I agree it should be symmetric around both. If anybody wants to try a PR I'm happy to review!

**Comment by akhmerov** [comment]
One tricky thing here is that we're dealing with a semantically incorrect DOM here regardless since display math is a part of the paragraph to which it belongs (see also https://github.com/sphinx-doc/sphinx/issues/8166).

**Comment by choldgraf** [comment]
closed via https://github.com/executablebooks/sphinx-book-theme/pull/369
