### ISSUE TITLE
footnote/citation reference and definition as jump targets overlapped with top bar

### ISSUE THREAD

**Issue by madjxatw** [executablebooks/sphinx-book-theme#275]
When jumping from a footnote reference to a definition or vice versa, the target jumped to is scrolled to the top of the screen, being covered by top bar.

I've noticed that a height (80px ) and minus margin-top (-80px) are set to all headings' `:before` pseudo-element so that they are placed right below the top bar when being jumped to. I think any element that is likely to a jump target should be placed at the right place.

**Comment by choldgraf** [comment]
This is now resolved - for example see https://sphinx-book-theme.readthedocs.io/en/latest/reference/kitchen-sink/paragraph-markup.html#id2
