### ISSUE TITLE
Merge (or better: collapse) logger output 

### ISSUE THREAD

**Issue by fmaussion** [executablebooks/sphinx-book-theme#281]
I write tutorials for a model which is quite ... verbose with logging. Here is how it looks like below cells that do model stuff:

https://oggm.org/tutorials/notebooks/working_with_rgi.html#use-the-rgi-files-to-start-an-oggm-run

I know that I could suppress logs entirely, but I think they are useful (and the tutorial readers should learn from them). 

What I wonder is if sphinx could remove the spaces between each log line, so that it doesn't look so bulky? I don't know if its even possible, or if this is an issue for sphinx-pydata-theme... 

![image](https://user-images.githubusercontent.com/10050469/106819301-e391ef00-6679-11eb-9226-19c596c17a8b.png)

**Comment by chrisjsewell** [comment]
This is actually an issue for myst-nb (merging consecutive stdout/stderr), which is already open 👍

**Comment by choldgraf** [comment]
@chrisjsewell are you thinking of this one: https://github.com/executablebooks/MyST-NB/issues/264 ?

**Comment by chrisjsewell** [comment]
No https://github.com/executablebooks/jupyter-book/issues/973

**Comment by choldgraf** [comment]
Ahh gotcha, I was looking in the myst nb repo. I'm gonna close this one as a dupe, but if @fmaussion thinks it's different from #973 please re open!

**Comment by fmaussion** [comment]
Thanks for the quick answer and the pointers! I'll wait for a fix then - the proposed workaround on the original issue (copying the notebooks manually) seems very unsustainable!
