### ISSUE TITLE
Single content option

### ISSUE THREAD

**Issue by svenkreiss** [executablebooks/sphinx-book-theme#290]
I am using this theme via jupyterbook here: https://vita-epfl.github.io/openpifpaf/dev/intro.html

One feedback that I got is that the two navigation bars on the left and right are confusing and whether it would be possible to just have a single one.

Alternatively, it would be nice to change or customize the title of the right navigation bar: "Contents" seems more appropriate for the left navigation bar. I would like to name the right one "On this page".

**Comment by choldgraf** [comment]
Thanks @svenkreiss for this feedback - I opened up #293 to track making this configurable. I think for now we won't change the default because we've already gone in the opposite direction in in another PR :-)

**Comment by choldgraf** [comment]
oh and re: two navigation bars, maybe we can track that one here: https://github.com/executablebooks/sphinx-book-theme/issues/296 ? Feel free to add your thoughts there.
