### ISSUE TITLE
Update to PyData Sphinx Theme v0.5 (or wait for a different shared theme before switching)

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#301]
# Background

I just cut a new release of this theme in order to start playing around with updating to v0.5 of the PyData Sphinx theme, and a bunch of stuff now seems to be broken. I'm not sure how much effort it'll take to update to the latest version of the pydata theme, but this is now how things look:

![image](https://user-images.githubusercontent.com/1839645/111040358-83643a80-83e7-11eb-9c3a-8d2464bed2e3.png)

# Options

I think we have three options:

- Update to the latest PyData Sphinx Theme, which will entail
  - Figuring out what CSS rules have changed
  - Understanding how the HTML structure / templates have changed
  - Removing our custom "navigation bar generation code" and using the upstream code instead since we added it to the PyData Theme
- Using this update cycle as an excuse to re-work the Sphinx Book Theme's HTML / CSS structure, perhaps to be closer in general structure to the [QuantEcon theme](https://python-programming.quantecon.org/oop_intro.html) 
- Wait for [some shared theme to emerge from this discussion](https://github.com/executablebooks/meta/issues/279)
  - Once it's ready, prototype swapping the Sphinx Book Theme to inherit from that theme and see how much extra work it'd be

If it is a significant amount of work to get the theme updated, it might be a better use of our time to make more fundamental improvements to the HTML/CSS structure. I'm curious if @DrDrij or @chrisjsewell have any thoughts there?

**Comment by jorisvandenbossche** [comment]
Seeing https://github.com/executablebooks/sphinx-book-theme/pull/312, it went more smoothly as expected? (it doesn't seem to have those CSS styling issues as the above screenshot?)

**Comment by choldgraf** [comment]
Indeed it did! I think the first problem was because i hadn't cleared out my local build folder. I have it another shot and all worked ok after some fiddling 🎉
