### ISSUE TITLE
Right sidebar shows the "Next" item from the bottom right.

### ISSUE THREAD

**Issue by rajk-cerebras** [executablebooks/sphinx-book-theme#306]
**Describe the bug**

So, we use Read the Docs hosting service, and use the wonderful Sphinx Book theme. I call the theme in my `conf.py` with this:

`html_theme = "sphinx_book_theme"`

This problem didn't exist until now. All of a sudden my right side bar started showing the "Next" item. See the screenshot below:
![image](https://user-images.githubusercontent.com/74557030/111700033-17723f80-87f6-11eb-8ca1-57bd66b37e26.png)

It looks like this is a new bug? My local builds use the same Sphinx Book theme but it is at least 3 months old (I downloaded to my Mac) and it does not show this problem. See the screenshot from my local build:
![image](https://user-images.githubusercontent.com/74557030/111700483-b1d28300-87f6-11eb-8c1a-5f7d83a25725.png)

Does anyone have a suggestion how I can fix this? Thanks!

**Comment by chrisjsewell** [comment]
Hey @rajk-cerebras just to clarify, what version of sphinx-book-theme does this occur for, I assume the newest v0.0.42?
Also do you have a link to the page where it occurs?

@choldgraf, @DrDrij possibly another side-effect of https://github.com/executablebooks/sphinx-book-theme/commit/76fe7e77883d8029f8f253387b92f28d202fb59e 😬 ?

**Comment by rajk-cerebras** [comment]
Hey @chrisjsewell ahh, actually not sure what the version number is. But my guess is it is the newest? I say that because I am thinking when I did the build just a few minutes ago on Read The Docs, it fetched the newest version of the theme, because I do not have that theme placed in my docs repo. So RTD must've gotten it from the latest version repo. 

I was afraid you'd ask for the page link. This is a private page and we are a bit paranoid about not sharing private docs pages links. Can I send you that link privately instead of posting it here?

**Comment by chrisjsewell** [comment]
Yeh no problem, I'm at chrisj_sewell@hotmail.com

**Comment by rajk-cerebras** [comment]
Awesome, just sent it.

**Comment by chrisjsewell** [comment]
Yep thanks, so this appears to be only an issue on a page with sphinx-panels (I guessing thats what you are using for the panels?)
sphinx-panels uses bootstrap which I imagine is conflicting with https://github.com/executablebooks/sphinx-book-theme/commit/76fe7e77883d8029f8f253387b92f28d202fb59e.

It is what I thought was the reason for #303, although @DrDrij thought it was due to the lack of a right ToC, but maybe a mix of the two.

**Comment by rajk-cerebras** [comment]
Nah, I am not using sphinx-panels. I am using a raw html code like this in my index.rst file:

```
.. raw:: html

  <div class="card-deck">

    <div class="card">

      <div class="card-body">
...

```

**Comment by chrisjsewell** [comment]
> Nah, I am not using sphinx-panels. I am using a raw html code like this in my index.rst file:

Ah fair, well its HTML very reminiscent of what [sphinx-panels](https://sphinx-panels.readthedocs.io/en/latest/) creates anyhow, so would probably generate a similar issue.
In fact, I created a page for another of my projects with sphinx-panels, very similar to yours: https://aiida.readthedocs.io/projects/aiida-core/en/latest/ 😄

**Comment by rajk-cerebras** [comment]
> In fact, I created a page for another of my projects with sphinx-panels, very similar to yours: https://aiida.readthedocs.io/projects/aiida-core/en/latest/ 😄

Looks awesome! So you don't have the problem I am facing, woe is me, why? :- ( I guess you don't use the latest version of the theme?

**Comment by chrisjsewell** [comment]
Ah well I'm currently using the pydata-sphinx-theme, which this theme derives from. Was planning to switch once @choldgraf releases a v0.1.0 😜

**Comment by rajk-cerebras** [comment]
Is there a way I can set some variable in `conf.py` to use a specific version of the theme? I am sure this is not the first time I will run into a situation like this.

**Comment by choldgraf** [comment]
@chrisjsewell I keep wanting to release v0.1.0 but we keeping finding (or introducing 😬) bugs!

**Comment by chrisjsewell** [comment]
You would pin the install version in your `requirements.txt` (`sphinx-book-theme==0.0.41`) or however you are installing the packages to use for RTD

**Comment by rajk-cerebras** [comment]
thanks, let me try that, that's a way to stay one version behind :- )

**Comment by rajk-cerebras** [comment]
So I pinned the version to 0.0.39 and the problem went away. Thanks a lot, @chrisjsewell, any such quick help is a ton of help!

**Comment by rajk-cerebras** [comment]
I don't know the protocol, should I close this issue, or one of you will do it? Either way is fine with me.

**Comment by chrisjsewell** [comment]
thats fine thanks @rajk-cerebras we will close it once we've found a fix 👍

**Comment by DrDrij** [comment]
I can't seem to replicate or find an occurrence of this bug. 

I don't think there should be any changes from the mobile-menu PR effecting the next button (it sits in the main content div).

@chrisjsewell Happy to attack/troubleshoot the bug if I can find an example

**Comment by choldgraf** [comment]
I believe this is now resolved but please ping here if the error persists on the latest book theme
