### ISSUE TITLE
Add navbar collapsible sections to the PyData Sphinx Theme

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#313]
Now that the PyData theme is using the Sphinx `{ toc }` directly, we can start to migrate our implementation to instead use the PyData theme. I think that we can keep our `home_page_in_sidebar` functionality here, but we should port over the "collapsible list" functionality to the PyData theme, and then just re-use that.

I think that this is where we add the collapse list functionality: https://github.com/executablebooks/sphinx-book-theme/blob/master/sphinx_book_theme/__init__.py#L161

I wonder if @AakashGfude would be interested in upstreaming this to the PyData theme? :-) I assume that @jorisvandenbossche would +1 the feature?

**Comment by jorisvandenbossche** [comment]
Yes, very much +1 on the feature! ;)

Now, good that you start the conversation about this. In January, when I was experimenting with the [Arrow docs](https://jorisvandenbossche.github.io/arrow-docs-preview/html-option-1/python/install.html), I actually implemented a collapse functionality in a local (messy) branch of the pydata-sphinx-theme. 

Originally, I tried to copy the implementation from the sphinx-book-theme, but for some reason I didn't get it to work (the javascript code gave some error, although I just basically copied it from here ..). Probably it was just a small oversight / fix for someone more experienced with javascript. But I couldn't directly figure it out, and I wanted to get something working, I then tried the pure-CSS-approach from Furo, which I got working on a basic level. 
I now quickly extracted that part from my local experimental branch, and put it in a PR to look at: https://github.com/pydata/pydata-sphinx-theme/pull/349

Now, the question is then: do we have a preference for which approach to eventually use? (in assumption we can get either approach working) 
The approach of Furo has the advantage to not use javascript (without being more complex, I think. The python code is different, but similar in that it's inserting some extra html with `new_tag`). On the other hand, it (currently) doesn't support the collapsing of captions (and I would need to check to know if that would be possible as well).

**Comment by jorisvandenbossche** [comment]
In light of https://github.com/executablebooks/meta/issues/279, it might be useful to converge to a common approach, as I can imagine this to be a shared component.

**Comment by choldgraf** [comment]
I think in general I'm a fan of CSS-only approaches if they are `<=` as complex 👍. @AakashGfude do you have strong opinions?

**Comment by choldgraf** [comment]
this is done!
