### ISSUE TITLE
Remove our custom sidebar collapsing code

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#319]
@jorisvandenbossche just added sidebar collapsing code to our parent theme (https://github.com/pydata/pydata-sphinx-theme/pull/349) so we should remove our own code and just use the upstream!

**Comment by jorisvandenbossche** [comment]
One important note: I didn't yet include "caption collapsing", which the sphinx-book-theme also does

**Comment by choldgraf** [comment]
@jorisvandenbossche ah good point, is your intention to do this?

**Comment by jorisvandenbossche** [comment]
I didn't yet investigate whether it would be easy/possible with the CSS approach (as opposed to the approach in sphinx book theme).  
But in the end, for the subsections, it puts a `<input>` before the list of items in the subsection, so I suppose that for a caption it should also be possible to put a similar input before the full list of sections.

**Comment by choldgraf** [comment]
forgot we had opened this 😆 closing in favor of #323
