### ISSUE TITLE
docutils version

### ISSUE THREAD

**Issue by spolanski** [executablebooks/sphinx-book-theme#320]
Hello.
At first, I would like to thank you for creating such a great sphinx theme. It looks great.

I am using sphinx book theme and readthedocs to host the website. The problem I have got at the moment is that when sphinx is compiling the docs, it is using docutils==0.17, while my project seems to work fine only with docutils==0.16. By working fine I mean the images are positioned correctly etc. Did you experience any issues with latest version of docutils?

I have created a stackoverflow topic which contains more details about the problem
https://stackoverflow.com/questions/66949028/docutils-dependecy-of-sphinx-theme-on-readthedocs

Thank you for any comments

**Comment by choldgraf** [comment]
@spolanski sorry for missing this one - I believe that the docutils issues should be resolved on the main branch now! I'll close this, but if the problem persists after we're made a new release and after you've updated, feel free to re-open.
