### ISSUE TITLE
'Next page' button cutoff when right-hand contents takes entire window

### ISSUE THREAD

**Issue by kn0wmad** [executablebooks/sphinx-book-theme#321]
**Describe the bug**

 The 'next page' button is cutoff by the contents on the right-hand frame, if there is not enough window space - for example, on zoomed window, or window that is not full screen

**To Reproduce**

Create a contents frame long enough to cover the button

**Expected behavior**

 The button to move to the left of the contents, or for the contents to hide to make space for the button

github.com/start9labs/documentation
https://docs.start9labs.com/support/FAQ/general-faq.html

**Environment**

- Python Version [e.g. 3.7.1]: 3.9.2
- Package versions or output of `jupyter-book --version`: 0.0.42
- Operating System: Linux
 
Screenshot - https://user-images.githubusercontent.com/39687477/113523907-44e61980-9568-11eb-8dbb-c94aedfb20f1.png

**Comment by choldgraf** [comment]
can you try manually updating to the latest sphinx book theme? I think that should fix it...

**Comment by kn0wmad** [comment]
How is this done?  I'm on the latest available via PIP, which is 0.42

**Comment by choldgraf** [comment]
could you try:

```
pip install -U git+https://github.com/executablebooks/sphinx-book-theme
```

?

**Comment by kn0wmad** [comment]
That seems to have done the trick, thank you
