### ISSUE TITLE
Refactor sidebar logic to use the PyData Sphinx Theme

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#323]
Now that the PyData Sphinx Theme has collapsible sections, I think that we can start to use it for our sidebar logic instead of our own custom code.

Here is where the pydata theme generates the nav html:

https://github.com/pydata/pydata-sphinx-theme/blob/master/pydata_sphinx_theme/__init__.py#L61

I think that we can remove some of our custom nav HTML code and use this instead. This is the function to update:

https://github.com/executablebooks/sphinx-book-theme/blob/master/sphinx_book_theme/__init__.py#L80

I think that we'll need to keep some functionality, in particular the "external link" CSS and the "add home page to sidebar" logic. So we may need to re-parse w/ beautifulsoup what the pydata theme outputs, and then modify the toctree as needed.

**Comment by jorisvandenbossche** [comment]
>  the "external link" CSS

That's something I added to pydata-sphinx-theme as well, I think? -> https://github.com/pydata/pydata-sphinx-theme/pull/365
