### ISSUE TITLE
Extract margin directive to separate repository

### ISSUE THREAD

**Issue by jpmckinney** [executablebooks/sphinx-book-theme#327]
I'm using the PyData theme, but it would be nice to be able to use the margin directive. Would it be possible to extract it?

**Comment by choldgraf** [comment]
The main challenge is that it'd conflict with the elements on another theme, and is kind of context dependent. Eg, how would you deal with the overlap between the margin and the in-page TOC?

**Comment by jpmckinney** [comment]
The Python code seems to have nothing specific to this theme, besides adding the `margin` CSS class: https://github.com/executablebooks/sphinx-book-theme/blob/master/sphinx_book_theme/__init__.py#L257-L273

Obviously, like any directive, I'd have to style it myself, using the CSS in:

https://github.com/executablebooks/sphinx-book-theme/blob/d34858003df2c582e91f9528efade676e1cc434f/src/scss/_page.scss
https://github.com/executablebooks/sphinx-book-theme/blob/7239788bc1fb4b02b4442be53c6e17f38e843a63/src/scss/_print.scss

**Comment by jpmckinney** [comment]
But, yeah, I guess it is basically the same as the `sidebar` directive from docutils?

**Comment by choldgraf** [comment]
Ah interesting - we certainly could just add a super lightweight python package that added a margin directive. Would that help? Or maybe it'd be easier just to add your own margin directive?

**Comment by jpmckinney** [comment]
I'm going to try out the plain `sidebar` and see how far i get :)
