### ISSUE TITLE
Nested admonitions are CSS styled incorrectly

### ISSUE THREAD

**Issue by leifp** [executablebooks/sphinx-book-theme#331]
I don't know if this is a MyST problem or a Sphinx problem, I just noticed it while reading your docs. I can try to figure out exactly where the CSS is being generated if you need me to.

**Describe the bug**

Nested admonitions are CSS styled incorrectly.

**To Reproduce**

1. Go to https://myst-parser.readthedocs.io/en/latest/using/syntax.html#nesting-directives
2. The nested "Warning" admonition inherits some of the surrounding "Note" styling, specifically the title bg
    and icon are blue, and the icon is an info-circle.

**Expected behavior**

The nested "Warning" admonition is styled correctly, specifically the title bg and icon are yellow, and the icon
is an exclamation-triangle.

**Environment**

Whatever environment generated https://myst-parser.readthedocs.io/en/latest/

I am viewing it with Mozilla Firefox 88.0 (64-bit), on Ubuntu 20.

**Towards a Fix**

The problem is fixed if the generated CSS is more strict and specifies that the title is a direct child of the 
admonition div:

```css
.admonition.warning .admonition-title { /* current, bug */ }
.admonition.warning > .admonition-title { /* seems to fix */ }
```

**Comment by pradyunsg** [comment]
Equivalent fix in Furo: https://github.com/pradyunsg/furo/commit/75d2eef1f962875c013bc8d744cad02f1b621c70#diff-94166aebc814a825b614b598b2e74ce0d969be1326710ba9ce599370d889be69

**Comment by choldgraf** [comment]
thanks for the pointer @pradyunsg - I realized this is actually also a bug in the PyData theme, so I upstreamed a fix here: https://github.com/pydata/pydata-sphinx-theme/pull/407 which will close this issue as well
