### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by vitorsr** [executablebooks/sphinx-book-theme#332]
I know it’s early to point out but I figured it’d be interesting to open an issue to track upcoming development on supporting or not Bootstrap 5 [1, 2].

[1] https://blog.getbootstrap.com/2021/05/05/bootstrap-5  
[2] https://getbootstrap.com/docs/5.0/migration

**Comment by vitorsr** [comment]
Thanks for the prompt response - I wasn’t aware of this dependency. (I thought the book theme was just _inspired_ by pydata’s.)

On a side note I am primarily concerned with properly displaying math content on both mobile and desktop. The pydata theme lends itself to some - in my opinion - questionable practices that reverberate on math elements (e.g., overflow). I was happy to see that it was not the case in the book theme.

|                                                      pydata                                                      |                                                      book                                                      |
| :--------------------------------------------------------------------------------------------------------------: | :------------------------------------------------------------------------------------------------------------: |
| ![pydata](https://user-images.githubusercontent.com/40741601/117473095-f98ca580-af2f-11eb-8a97-0e9043450426.png) | ![book](https://user-images.githubusercontent.com/40741601/117473089-f85b7880-af2f-11eb-8b62-c73297b079d0.png) |

However there are still some minor issues such as word wrap (e.g., see [1] on mobile) that I believe are amenable to being solved by Bootstrap [2].

[1] https://sphinx-book-theme.readthedocs.io/en/latest/reference/demo.html#id10  
[2] https://getbootstrap.com/docs/5.0/utilities/text/#word-break

**Comment by pradyunsg** [comment]
> The pydata theme lends itself to some - in my opinion - questionable practices that reverberate on math elements (e.g., overflow).

I'm pretty sure this would be considered a bug that they'd like to fix. :)

**Comment by pradyunsg** [comment]
> However there are still some minor issues such as word wrap (e.g., see [1] on mobile) that I believe are amenable to being solved by Bootstrap [2].

FWIW, you don't need to upgrade to Bootstrap 5 for this.

It's literally setting:

```
.text-wrap {
    word-wrap: break-word;
    word-break: break-word;
}
```

Which, we can do here as well. I'm pretty sure the main thing that'll have these issues is links.

**Comment by choldgraf** [comment]
Indeed it would be great to see this overflow fizz on the pydata theme and the reword fix here or in the pydata theme 🙂
