### ISSUE TITLE
Theme CSS update is needed for Sphinx 4.0.1

### ISSUE THREAD

**Issue by outoftardis** [executablebooks/sphinx-book-theme#335]
**Describe the bug**

After upgrading Sphinx to version 4.0.1, I've noticed a change in styles. In [this issue in `michaeljones/breathe` repository](https://github.com/michaeljones/breathe/issues/700) I was told that it is not a bug on Sphinx/breathe side but rather an intentional change in the new version of Sphinx, and that css should be fixed on the theme side.

Here's what the breathe output looks like with `Sphinx 4.0.1` and `sphinx-book-theme 0.1.0`. If you compare it with the output produced with the earlier version of Sphinx, you'll see that all the code highlighting is missing:

![image](https://user-images.githubusercontent.com/17865025/118640075-3f275900-b7e1-11eb-97c7-f5b596cc560b.png)

**Expected behavior**

With ``Sphinx==3.5.4`` and `sphinx-book-theme 0.1.0` the output looks like this:

![image](https://user-images.githubusercontent.com/17865025/118640133-4d757500-b7e1-11eb-89bc-8177ea8977e9.png)

**To reproduce**

The example (rst/header) is taken [directly from the breathe documentation](https://breathe.readthedocs.io/en/latest/#in-a-nutshell).

**Environment**

- Python Version: 3.6.9
- Operating System: Ubuntu
- ``breathe==4.30.0``
- ``sphinx-book-theme==0.1.0``

**Comment by choldgraf** [comment]
this one is resolved!
