### ISSUE TITLE
Allow removal of next/previous button

### ISSUE THREAD

**Issue by alpha-X-omega** [executablebooks/sphinx-book-theme#336]
Is it possible to expose a parameter to `html_theme_options` like `prev_next_buttons_location: None`?

I would like to disable the next/previous buttons that show up at the bottom of the page.

I can use JS to remove `prev-link` and `next-link` since it's unique.  Was hoping there was something I missed in the docs at https://sphinx-book-theme.readthedocs.io/en/latest/configure.html.

Thank you for the amazing theme!
Phi

**Comment by choldgraf** [comment]
Hmm, it's not currently an option in the theme, but could you just add this CSS:

```
a.right-next, a.left-prev {
    display: none;
}
```

?

**Comment by alpha-X-omega** [comment]
Totally overlooked that solution.  I'll take it since I didn't realize the option I mentioned is specific to a few themes.

Thank you for the snippet.
