### ISSUE TITLE
support logo_only

### ISSUE THREAD

**Issue by djangoliv** [executablebooks/sphinx-book-theme#342]
It would be nice to support the logo_only option: 

```
html_theme_options = {
    "logo_only": True,
}
```

https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-logo_only

Regards

**Comment by djangoliv** [comment]
PR: https://github.com/executablebooks/sphinx-book-theme/pull/349

**Comment by choldgraf** [comment]
I believe you could accomplish this by setting `html_title = ""`. Does that work for you?

**Comment by djangoliv** [comment]
@choldgraf This is not the same.
with `html_title = ""` the title of the project also disappears from the title of the tab in the browser.
I want to keep the title in the browser tab but my logo already contains my project title.
So, I don't want to repeat the title below the logo but I want the title in the tab browser.

Regards

**Comment by choldgraf** [comment]
Makes sense to me, let me check out your PR later today

**Comment by choldgraf** [comment]
closed by #349
