### ISSUE TITLE
Make our admonitions / code blocks a bit softer

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#351]
In some earlier mockups from @DrDrij he showed off some simple ways to make our admonitions and code blocks a bit "softer", and to use a bit less color/"ink" to differentiate elements. Here are two things that stood out to me:

1. Removing the sharp edges + drop shadow from admonitions, and instead using a rounded edge with a faint grey line to differentiate:

   
   <img width="707" alt="Screen Shot 2021-07-03 at 3 39 04 PM" src="https://user-images.githubusercontent.com/1839645/124368370-61502b80-dc15-11eb-8acd-58ec51bc591c.png">

   and

   <img width="690" alt="Screen Shot 2021-07-03 at 3 39 34 PM" src="https://user-images.githubusercontent.com/1839645/124368373-66ad7600-dc15-11eb-96ab-2a3ae881c53b.png">

2. Removing the bounding boxes from the "previous and next" buttons and instead using some bolded text to make them more noticeable.

   <img width="762" alt="Screen Shot 2021-07-03 at 3 40 40 PM" src="https://user-images.githubusercontent.com/1839645/124368375-6ad99380-dc15-11eb-88ce-7e6a15ad8b32.png">

I feel like both of these would be fairly easy to implement, and may be a nice way to soften/flatten some of our content, while also removing the amount of ink and visual elements the user must pay attention to (e.g. the bold vertical line to the left of admonitions).

Curious what folks think about this, I may try whipping together a PR to see what this looks like.

**Comment by choldgraf** [comment]
Another option is that we could **just** set the border radius slightly above 0, so that admonitions and code blocks have a similar rounding to our `sphinx-panels` cards, e.g.:

<img width="823" alt="Screen Shot 2021-07-03 at 5 29 42 PM" src="https://user-images.githubusercontent.com/1839645/124369769-5b157b80-dc24-11eb-94f3-360a919023e9.png">

**Comment by pradyunsg** [comment]
Rounding out the border radius to the same amount as the left border is the approach I took in Furo: https://pradyunsg.me/furo/reference/admonitions/#supported-types

IIRC, I also reduced the shadow on the admonition in Furo; to make things look a little more "tight".

**Comment by pradyunsg** [comment]
Relevant code: https://github.com/pradyunsg/furo/blob/fe0088363a163cd9d6ffaf274560533501e935b5/src/furo/assets/styles/content/_admonitions.sass#L9-L10


```\

**Comment by choldgraf** [comment]
@pradyunsg ah that's really nice. I will try that and see how it looks here :-) 

A quick thought - I love the way Furo has some nicely laid out "reference" pages so that the theme can show off how all the elements look. I wonder if there's a way that the community could have a standardized set of such pages to **re-use** across projects (e.g., for this theme, I could tell it to download the latest set of those pages at build time rather than maintain my own separate copy)

**Comment by pradyunsg** [comment]
Hmm... I guess we could make something like that on https://sphinx-themes.org/.

Or at you thinking in terms of having that in this themes' own documentation?

**Comment by choldgraf** [comment]
Well for now i may just try to download your reference folder using the github API haha :-) but I'm just thinking of anything that could make that easier to reuse across sites

**Comment by choldgraf** [comment]
Actually sphinx-themes might be good for this, if those reference pages are a part of the docs site that it uses to preview, maybe that could be a standard for themes that wish to reuse those pages?

**Comment by choldgraf** [comment]
I took some of your tips in the PR: https://github.com/executablebooks/sphinx-book-theme/pull/352#issuecomment-873623582 :-)

**Comment by choldgraf** [comment]
I think this one was closed by https://github.com/executablebooks/sphinx-book-theme/pull/352
