### ISSUE TITLE
Include explicit support for videos.

### ISSUE THREAD

**Issue by dmwyatt** [executablebooks/sphinx-book-theme#354]
**Is your feature request related to a problem? Please describe.**

AFAIK, there's not a good and recommended way to embed a video.  What I currently do is this:

```rst
.. raw:: html

  <video
    draggable="false"
    playsinline=""
    autoplay=""
    loop=""
    style="width: 960px; height: 306px;"
  >
    <source type="video/mp4" src="https://i.imgur.com/MHtMxZq.mp4">
  </video>
```

Unfortunately, the video is pulled out of the main content of the page as seen here
[here](https://dmwyatt.github.io/systa/events.html#lol-decorators).  Screenshot for posterity:

![image](https://user-images.githubusercontent.com/163359/125208801-4c4d4b00-e25a-11eb-87c0-f0dab2bc2dd9.png)

**Describe the solution you'd like**

Some sort of "official" support for videos.  Ideally a directive, but even just a documented way of setting up raw HTML to make it work correctly would be great. (Queue someone pointing out that this already exists and I missed it!)

**Alternatives**
There's [sphinxcontrib-video](https://github.com/sphinx-contrib/video), but it has no support, hasn't been updated in years, isn't on PyPi, I can't get it to work, and even if I did `sphinx-book-theme` probably wouldn't style it correctly.

**Comment by dmwyatt** [comment]
It looks like the video gets pulled to the right if the width is more than ~550px.  If you keep the size below that, it stays to the left.

**Comment by choldgraf** [comment]
I believe that the width behavior should be a bit more predictable on the main branch now, I also added a PR to document using `sphinxcontrib.youtube` as one example. Please re-comment here if this behavior is still broken
