### ISSUE TITLE
Left ToC open on mobile during page load

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-book-theme#366]
### Description

When the book theme is loaded on narrow screens, the left navigation bar is briefly visible, and then collapses.

<img src="https://user-images.githubusercontent.com/1839645/135732855-3f01025e-2565-4794-9cc0-6e7f70fe595a.gif" width=300 />

Instead, it should automatically be invisible on narrow screens, and pressing the "show navbar" button should show it. Basically, similar to how Furo works:

<img src="https://user-images.githubusercontent.com/1839645/135732801-f320a0cc-30a1-4f2b-9eef-2a7dd0fa87c5.gif" width=300 />)

### Why does this happen

This happens because we are currently using [Bootstrap Collapse](https://getbootstrap.com/docs/4.3/components/collapse/) functionality to toggle the left navigation bar. Clicking the button will use the bootstrap classes `.collapse`, `.collapsing`, and `.show` to trigger two things:

- the visibility of the sidebar
- the icon that's displayed in the hamburger menu

The problem with this is that we want a different default behavior on wide vs. narrow screens. On wide screens, the sidebar should be visible by default, with the option to hide. On narrow screens we want it hidden by default, with option to show (and ideally, hiding can be done by clicking _anywhere_ outside the sidebar, not just on the toggle button).

### How could we solve this?

I think the easiest way to solve this would be to do a few things:

- Stop relying on Bootstrap for this
- Use one of these approaches to showing the sidebar:
  - a simple class like `.show-toggle` and a simple `onclick` function like `getElementById('site-navigation').classList.toggle("show-toggle")`
- The visibility of the sidebar can then be made different with `@media` queries in our CSS (so that `checked` means "show it" on mobile, but means "hide it" on wide screens)

**Comment by chrisjsewell** [comment]
Yeh the JS is here: https://github.com/executablebooks/sphinx-book-theme/blob/4b65bc18d5b8a3c46cec3f877c2b6cec4c77066f/src/js/sphinx-book-theme.js#L2

this could, and should, be achieved by CSS `@media`

**Comment by choldgraf** [comment]
Yeah it's always been like this, and agreed it is definitely sub optimal. I feel like part of the answer is finding a more graceful way to handle the opening and closing logic (IMO it would be great if we could avoid JS altogether)

**Comment by choldgraf** [comment]
I tried to see if this would be a simple fix, but I got bogged down in the bootstrap JS/CSS stuff and ran out of time, so instead I've updated the top comment with some more explanation of what I think is going on here so it's easier to pick back up (myself or others) in the future

**Comment by pradyunsg** [comment]
FWIW, another option would be to have JS inline at the top of body / relevant tag, that adds the relevant class to it, to trigger the hiding (if the hiding worked that way)
