### ISSUE TITLE
Hash our CSS/JS assets with `digest` requests instead of in filenames

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#376]
# Summary

In https://github.com/executablebooks/sphinx-book-theme/issues/373 we learned that it is difficult to sub-theme this theme because of the hashes in the CSS / JS assets. @pradyunsg shared a solution that has worked for Furo, which uses [Digest headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest) to specify a _specific version_ of the JS/CSS assets. Here's the commit that added it in Furo:

https://github.com/pradyunsg/furo/commit/11dc2eebe65a64cfdecbabbfaa7f75c66fce5a21

We could follow a similar pattern in this theme, which would make it easier for sub-themes to depend on it since they won't need to know the hash ahead of time, they can just specify a CSS file.

# Implementation

We currently use a pre-commit hook to generate hashed CSS, JS, and a `theme.conf` file that addresses these hashed assets. [Here's the asset compilation configuration for our pre-commit hook](https://github.com/executablebooks/sphinx-book-theme/blob/master/web-compile-config.yml). Instead of specifying the hashes in filenames, we could create / append the hashes at Sphinx build time, following a similar pattern to what Furo does in the commit above.

**Comment by pradyunsg** [comment]
> [Digest headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest) t

Furo isn't using the digest headers -- it's putting the hash as `furo.css?digest=[hash]` instead of `furo.[hash].css`.

**Comment by choldgraf** [comment]
@pradyunsg ah that is just me not really understanding what `?digest=` really means...I just googled "HTML Digest" and that's what came up. Do you have a link to a resource that explains what this is?

**Comment by pradyunsg** [comment]
It's basically using the hash of the CSS file's contents for cache busting. A good link on cache busting would be https://css-tricks.com/strategies-for-cache-busting-css/.

A good link on what "digest" means in this context would be https://developer.mozilla.org/en-US/docs/Glossary/Digest (although, we don't care about the integrity; just that it changes when the contents change).

SBT is already doing cache busting, by changing the filename and including a hash in it. Furo is doing in a _slightly_ different way, by having a query parameter with the hash instead.

**Comment by choldgraf** [comment]
This is very helpful for me to understand, thanks for sharing those links 🙂
