### ISSUE TITLE
Right/secondary sidebar: configurable default header expansion

### ISSUE THREAD

**Issue by ajfriend** [executablebooks/sphinx-book-theme#383]
### Describe the enhancement you'd like

Right now, the sidebar on the right lists only the top-level headers, with lower-level headers appearing only as a user scrolls down the page. Often, I'd like to automatically/statically display up through the 2nd- or 3rd-level headers, with the remainder having the existing dynamic behavior.

It doesn't seem like that is currently possible. If so, could we add an option for that?

### Does this solve a specific problem?

I like to structure a page's `Contents` in a way that a user can understand the document structure at a glance. By only revealing the headers dynamically, much of that information is hidden from the user up front.

### What alternatives exist?

I suppose I could add a `Contents` at the top of each page, but the right sidebar seems like the more natural place to put things.

**Comment by choldgraf** [comment]
this is now possible! https://sphinx-book-theme.readthedocs.io/en/latest/customize/sidebar-secondary.html#show-more-levels-of-the-in-page-toc-by-default
