### ISSUE TITLE
Click left sidebar folder to only expand/collapse

### ISSUE THREAD

**Issue by jayjaywg** [executablebooks/sphinx-book-theme#390]
### Description / Summary

add a custom conf to: click left sidebar folder to only expand/collapse, example is Microsoft docs:  https://docs.microsoft.com/en-us/dotnet/core/introduction

### Value / benefit

A folder page may not have concrete content. So adding a feature of "when clicking on the left sidebar folder, only expand/collapse" would be more agile.

**Comment by choldgraf** [comment]
ah I missed this one - we have another issue open to track this here: https://github.com/executablebooks/sphinx-book-theme/issues/460

will close this one and use 460 to track
