### ISSUE TITLE
Add $ in code-block without being copied

### ISSUE THREAD

**Issue by dimitraka** [executablebooks/sphinx-book-theme#411]
### Describe the problem

I would like to add a $ inside my code blocks to separate code from output of code, but I don't want the $ to be copied when someone copies the command. Is that possible?

So far, I've tried the following, but none of the worked:

- code-block
- highlight
- codecell

 with options:

- shell-session
- sh
- console
- bash

Thank you for your help!

### Steps to reproduce

1. Just try the following in any rst file

.. code-block:: shell-session

    $ ./my_program
    Hello World!
2. You will see that you can copy the $ when copying the command ./my_program

**Comment by choldgraf** [comment]
I think this is doable with configuration of the sphinx-copybutton extension, which is the thing that adds this functionality. See https://sphinx-copybutton.readthedocs.io/en/latest/#strip-and-configure-input-prompts-for-code-cells

closing this but please re-open if you think there's a bug in this theme specifically!

**Comment by dimitraka** [comment]
Hello, still facing the same problem with the copy button. The copy button appears very big, after the code-block and not in the top right. Any updates on how to solve it?

**Comment by lukashergt** [comment]
@dimitraka, [`sphinx-copybutton`](https://sphinx-copybutton.readthedocs.io) works like a charm for me (I can copy code blocks omitting the leading `$ `). I found [this section](https://sphinx-copybutton.readthedocs.io/en/latest/use.html#using-regexp-prompt-identifiers) particularly useful for the bash prompt case, which suggests the following configuration in the `conf.py` file:

```python
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
```
