### ISSUE TITLE
Newer version of pydata-sphinx-theme could be used

### ISSUE THREAD

**Issue by erogluorhan** [executablebooks/sphinx-book-theme#423]
### Description / Summary

Hi all,

The `pydata-sphinx-theme` dependency in `setup.py` is constrained  as follows:

`"pydata-sphinx-theme~=0.6.0"`

pydata-sphinx-theme fixed significant bugs (e.g. Google analytics code snippet etc.) in their v0.7.0 and v0.7.1 recently, so this constraint here prevents us from taking advantage of those bug-fixes.

Is there a release coming soon? IF so, could you please consider revising this constraint in it?

Thanks!

### Value / benefit

This would facilitate usage of the later/latest versions of pydata-sphinx-theme.

### Implementation details

Something like following could be written in `setup.py`:

`"pydata-sphinx-theme>=0.7.0"`

instead of `"pydata-sphinx-theme~=0.6.0"`.

**Comment by kousu** [comment]
There's another motivation for this, that sphinx 4.3 just came out and broke this and its sibling themes: https://github.com/pydata/pydata-sphinx-theme/pull/509

**Comment by kousu** [comment]
Is this done now? https://github.com/executablebooks/sphinx-book-theme/pull/406 got merged. It's just not released to pypi yet.

**Comment by chrisjsewell** [comment]
I don't see any reason why this can't be released @choldgraf ?

**Comment by choldgraf** [comment]
+1 from me
