### ISSUE TITLE
Bump click dependency

### ISSUE THREAD

**Issue by rdbisme** [executablebooks/sphinx-book-theme#424]
### Description / Summary

Click 7.x is not supported anymore and I'm [hitting a problem](https://github.com/pallets/click/issues/2123#issuecomment-957917980) with that version. Would it be possible to bump or unpin the dep on click?

### Value / benefit

- This will allow to depend on more recent versions of click

### Tasks to complete

- [ ] Bump version in `setup.py`
- [ ] Make sure that tests still work

**Comment by chrisjsewell** [comment]
Heya, yep I'm already aware of click v8. It should be a problem to update, but needs to be synchronised with an update in other packages, including jupyter-book and sphinx-external-toc

**Comment by rubendibattista** [comment]
Ehi @chrisjsewell, thanks. Maybe just unpinning it allowing also future versions? If the code still works with 8.x, that would let other project their time to adapt, still allowing people needing more modern versions to use them, wouldn't it?

**Comment by rubendibattista** [comment]
Also, why is explicitly listed? I fasly searched here on Github and click does not seem to be used in this project, isn't it?

**Comment by choldgraf** [comment]
I was wondering the same thing - is there a reason that we're depending on `click` in the book theme? I would have imagined this is only necessary for the command-line-based tools.

If we can't think of a good reason, I'm +1 on removing Click as a dependency

**Comment by choldgraf** [comment]
this was closed in https://github.com/executablebooks/sphinx-book-theme/pull/457
