### ISSUE TITLE
Improvements to PDF printing CSS

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#435]
### Description / Summary

Currently the CSS that is applied when we print a page to PDF is a little bit hacky. It doesn't quite match the design principles you'd want with a printed PDF, and there is likely some low-hanging fruit that we can tackle to improve this.

### Value / benefit

The most common way for a person to get a single-page PDF is likely by printing it directly, so this would be a good way to make some quick improvements to this workflow.

### Implementation details

Here's the CSS that gets applied when the "print" action is triggered, this is where we'd need to make changes to make the output look nicer:

https://github.com/executablebooks/sphinx-book-theme/blob/39aaaa3e4d908fe7be8b7378ad474d8c6b86aa16/src/scss/_print.scss

**Comment by choldgraf** [comment]
cc @AakashGfude - I believe you said you were interested in making some minor improvements on this before tackling the more complex `jtex` stuff? I'll add you to this issue but feel free to drop yourself if you don't plan to work on this

**Comment by AakashGfude** [comment]
Thanks, @choldgraf for opening this issue. I had created a similar issue in `jb` https://github.com/executablebooks/jupyter-book/issues/1551 .  Will close that one as well, if we can solve it in `sphinx-book-theme` alone.

**Comment by choldgraf** [comment]
@AakashGfude I'm +1 on leaving both open, since as you and @chrisjsewell mentioned in the meeting, just making the PDF CSS nicer may not necessarily solve the general problem of "nice single-page PDFs fit for publishing". How about we try giving this one a shot, and re-assess when it is done whether we still want to also tackle https://github.com/executablebooks/jupyter-book/issues/1551 ?

**Comment by choldgraf** [comment]
I believe we've taken a few stabs at this since it was open, so closing this one. If there are more specific things to improve lets open issues with clear next steps for them.
