### ISSUE TITLE
Secondary Sidebar Navigation Not Working in v0.1.8

### ISSUE THREAD

**Issue by VinithKrishnan** [executablebooks/sphinx-book-theme#451]
### Describe the problem

Clicking on the 2nd level headers displayed under the secondary sidebar does not take one to the appropriate section of the page.

### Steps to reproduce

1. Go to https://sphinx-book-theme.readthedocs.io/en/stable/index.html#
2. Click on "Reference Pages" in secondary sidebar(or contents bar).
3. In page navigation isn't observed.

### What's going wrong

In #435 we added a second `super()` call, which generates all of the page's content a second time. This means we have duplicated IDs and links for anchors, which is why this isn't working. We need to call `super()` only once per page. Here are the links:

https://github.com/executablebooks/sphinx-book-theme/blob/1f2c69fbae20dfbc18abab6c794e5b0a5f558fe4/sphinx_book_theme/layout.html#L38-L48

**Comment by choldgraf** [comment]
Good catch - I believe that this is somehow linked to #435 . If I checkout the commit just before that, then clicking anchor links scrolls fine. If I checkout the commit from that PR getting merged, it no longer works.

@AakashGfude can you take a look at your PR and see if anything in there caused this to break?

**Comment by zmoon** [comment]
I noticed this as well, and also that search is not working anymore: no results get shown. Possibly related?

**Comment by zmoon** [comment]
In v0.1.9 it seems search is fixed too btw

**Comment by choldgraf** [comment]
@zmoon I had a hunch it was the same issue, thanks for confirming :-)
