### ISSUE TITLE
Reduce our maintenance burden associated with supporting multiple major Sphinx versions

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#465]
### Description

**background**
Right now we are testing for the latest two versions of Sphinx, but we don't generally have an official policy around Sphinx versions to support.

Because major versions of Sphinx are spitting out different HTML, we currently have regression tests for **both** major versions of Sphinx.

**problem**
This means that any time we update a regression test, we have to run pytest with two different versions of sphinx to generate the updated tests to compare against.

This is a cumbersome workflow because it means you must re-run `tox` with two different environments, or find some other way to run the test suite locally w/ two different versions of Sphinx.

**proposed solution**

Edit: see comment below for a potentially better solution 😅

What do others think about softening our official support of the 2nd-to-last version of Sphinx. We will include it in our testing, but we will *not* include it in our regression tests. So our regression tests will stop including `foo.sphinx3.bar`, it will just be `foo.bar` and be assumed we're using Sphinx 4.

So our language would be something like "This theme provides strong support for the latest major release of Sphinx, and softer support for the release that came just before this". We would not test against major releases older than this.

I think that this would reduce the number of manual and finnicky steps needed to update our regression tests, which should boost maintainability and make the developer workflow a bit smoother.

### Guide for implementation

We could do this by using the [`skipif` decorator in pytest](https://docs.pytest.org/en/latest/how-to/skipping.html#id1).

We should also look at how much test coverage this would reduce if we implemented it - if we'd stop testing like 80% of our tests on Sphinx 3, then we probably want to re-think our language about "strong vs soft" support since then we'd basically not be testing it at all.

### Alternatives

I think there are two obvious alternatives with pros and cons each:

- Continue doing what we're doing, and have different tests for different Sphinx versions, in order to say we "fully support" both of them.
- Adopt a more aggressive policy for dropping older Sphinx versions. And say "We only support the latest major release of Sphinx".

But I thought I'd lead with the proposal above because it is the most complicated to describe :-) 

### Thoughts?

Does anybody have strong opinions on this one way or another? I think that I am in favor of this as long as we don't reduce our test coverage by *too much*, but wanted to know if others differ in their thinking

**Comment by choldgraf** [comment]
I just realized that we might be able to solve this issue in a better way, by doing an audit of our testing infrastructure and targeting our regression tests a bit more specifically for the thing we want to be testing. Then we could only use two different regression tests for the tests where we know there's a difference between sphinx 3 and 4.

**Comment by pradyunsg** [comment]
Hi. I'd like to pile onto reducing maintainance workload, and dropping support for n-1 (Sphinx 3) after some $period of support for Sphinx 4. Personally, I'd keep $period at 0, but you can pick whatever works for y'all. :)

**Comment by choldgraf** [comment]
I think I'm on board with that idea as well, with a reasonable grace period. Sphinx shifts more quickly than Python and is more of a pain to support across multiple versions in my experience.

The PyData community has an informal community practice in Python of supporting versions of Python that are <36 months at the time of a package's release (so if NumPy released on Jan 1st 2022, then it'd commit to supporting all major/minor Python versions that we were released in the 36 months prior to that day.

Maybe we could do the same, but shorten the windows considerably. Something like:

- Upon book theme release, always support the latest major Sphinx version, and support the previous major sphinx version if it was released less than 12 months since the latest major release.

**Comment by chrisjsewell** [comment]
sphinx-book-theme's primary goal is to be a component of [jupyter-book](https://github.com/executablebooks/jupyter-book).
It's great if people also want to use it independently but, at the end of the day, it should support whatever jupyter-book needs it to support (i.e. that it is compatible with the rest of the jupyter-book components)

(I would also note that it is probably the only component currently blocking the use of docutils v0.17: https://github.com/executablebooks/sphinx-book-theme/issues/392)

**Comment by choldgraf** [comment]
@chrisjsewell agreed that this would need to be a conversation at the EBP-level before we ever changed dependency rules on something as core as Sphinx - just spitballing ideas right now.

**Comment by choldgraf** [comment]
ok closing this one as we've simplified our testing infrastructure a bit so that this isn't as much of an issue any more
