### ISSUE TITLE
sphinx-book-theme.css imported twice, can't override styles

### ISSUE THREAD

**Issue by patrickmineault** [executablebooks/sphinx-book-theme#496]
### Describe the bug

**context**
It should be possible to override css rules using extra css, as outlined in: https://sphinx-book-theme.readthedocs.io/en/latest/customize/custom-css.html

**expectation**
In the generated html, I expect that sphinx-book-theme.css should be linked before any further static css files. This allows the static css files to override any css in sphinx-book-theme.

**bug**
Instead, in the `latest` version, `sphinx-book-theme.css` is imported once *before* the overrides, and once *after* the overrides. The second import overrides the overrides and so it's impossible to override the css.

e.g. the source of https://sphinx-book-theme.readthedocs.io/en/latest/customize/custom-css.html has this double import:

```
    <link rel="stylesheet" type="text/css" href="../_static/pygments.css" />
    <link rel="stylesheet" type="text/css" href="../_static/styles/sphinx-book-theme.css" />
    <link rel="stylesheet" type="text/css" href="../_static/togglebutton.css" />
...
  <link href="../_static/styles/sphinx-book-theme.css?digest=d39d74a9f498dbb5016c" rel="stylesheet">
```

### Reproduce the bug

Look at the current source of https://sphinx-book-theme.readthedocs.io/en/latest/customize/custom-css.html or any of the other pages on the latest docs.

### List your environment

Can be reproduced in the environment currently used to generate the docs.

**Comment by choldgraf** [comment]
good catch - fixed in https://github.com/executablebooks/sphinx-book-theme/pull/506
