### ISSUE TITLE
Colab button oversized image in 0.3.0rc1

### ISSUE THREAD

**Issue by PhilipVinc** [executablebooks/sphinx-book-theme#514]
### Describe the bug

**context**
In the documentation of [netket](https://github.com/netket/netket/tree/master/docs), we have some notebook pages and we use the colab launch button.

```
html_theme_options = {
    "path_to_docs": "docs",
    "launch_buttons": {"colab_url": "https://colab.research.google.com"},
    ...
}
```

with sphinx-book-theme commit 910e26be00e74cafbaaaff274de26b95cab1f7a8
```
git+https://github.com/executablebooks/sphinx-book-theme@910e26be00e74cafbaaaff274de26b95cab1f7a8
```

this builds correctly (see for example https://netket.readthedocs.io/en/latest/tutorials/gs-ising.html )

However, I just tried the recently released `0.3.0rc1`  (and current master) and instead i get the following wrong styling of the button.

![screen](https://user-images.githubusercontent.com/2407108/156039531-c31d3233-bb3e-4727-9d9c-aeb28af6ff6d.png)

We have customized the theme a bit by adding a top navbar.
It is entirely possible that this is caused by our custom navbar and styling, though i'd be surprised.

### Reproduce the bug

build our documentation using the latest version of sphinx-book-theme.
The commands below should do it for you (note: this will install jax too, because it installs netket).
```sh
git clone https://github.com/netket/netket.git
cd netket
pip install --upgrade pip
pip install -r docs/requirements.txt
pip install --upgrade sphinx-book-theme==0.3.0rc1
cd docs
make html
open _build/html/tutorials/gs-ising.html
```

### List your environment

Sphinx==4.4.0
sphinx-autodoc-typehints==1.17.0
sphinx-markdown-parser~=0.2.4
sphinxcontrib-fulltoc~=1.2.0
sphinxcontrib-jsmath~=1.0.1
sphinxcontrib-napoleon~=0.7
myst-parser~=0.15.2
nbsphinx~=0.8.7
myst-nb==0.13.2
jaxlib>=0.1.59
sphinx-book-theme==0.3.0rc1

**Comment by choldgraf** [comment]
ahhh I see what's going on - you've *only* got a `colab` launch button, and that's what is breaking this. Good catch.

**Comment by choldgraf** [comment]
I believe that https://github.com/executablebooks/sphinx-book-theme/pull/516 should fix this - want to give it a shot?

**Comment by PhilipVinc** [comment]
I will tomorrow morning!
thanks for the quick response!

**Comment by choldgraf** [comment]
@PhilipVinc any feedback on whether this is fixed? :-)

**Comment by PhilipVinc** [comment]
It does, see my answer in #516
