### ISSUE TITLE
Instructions for adding a header did not work

### ISSUE THREAD

**Issue by rabernat** [executablebooks/sphinx-book-theme#515]
### Describe the bug

**context**
I wanted to add a header to an existing sphinx-book-themed site: https://github.com/pangeo-forge/pangeo-forge-recipes
I read the docs at  https://sphinx-book-theme.readthedocs.io/en/latest/customize/header.html and followed the directions exactly. The header did not show up.

Then I backed up and created a fresh project to confirm that it was not something weird with my config. (See full reproduction steps below)

**expectation**
I expected to see my header with HELLO WORLD at the top of the site...

**bug**
...but it was not there. I confirmed it is not just a CSS issue by viewing the page source and searching for HELLO WORLD.

**problem**
I am using the latest release of sphinx-book-theme and following the directions on the documentation exactly, with zero customizations. This indicates that the documentation is incomplete or the feature is broken somehow.

I also read #182 carefully; that issue suggests that custom headers are not actually supported. This seems to be in contradiction with what the documentation says.

### Reproduce the bug

- `pip install sphinx-book-theme==0.2.0`
- create a fresh sphinx site using `sphinx-quickstart`
- edit conf.py to use `html_theme = 'sphinx_book_theme'`
- confirm that `templates_path = ['_templates']` os present in conf.py
- created a file called `_templates/sections/header.html` with some html in it: ``<p>HELLO WORLD</p>``
- build the site with `make html`
- view the site with ` cd _build/html; python -m http.server`

### List your environment

I don't have jupyter-book installed in my env so I can't run that command. Some relevant packages are

- sphinx-book-theme: 0.2.0
- myst-parser: 0.13.6
- sphinx: 3.5.4

**Comment by choldgraf** [comment]
Good catch - this is actually because our docs are slightly ahead of our latest release. To try out the current docs, run:

```
pip install -U sphinx-book-theme --pre
```

I've also updated our documentation to use `stable/` rather than `latest/` as a default, so this won't be a problem in the future. Will close this one!
