### ISSUE TITLE
html_logo in left sidebar pushes site title to the right behind main content

### ISSUE THREAD

**Issue by ngulden** [executablebooks/sphinx-book-theme#525]
### Describe the bug

**context**
I had a look at the version 0.3.0rc1 of the theme to see what I need to change with my own theme that is based on it.

**expectation**
I expected the site title to show up below the logo as it was in version 0.2.0 of the theme.

**bug**
When I use version 0.3.0rc1 of the theme and configure a `html_logo` the site title is not visible and pushed to the right behind the main content. See the screenshot:

![sphinx_book_theme_0 3 0rc1_html_logo_issue](https://user-images.githubusercontent.com/55257/158612949-dd2f5ca0-9d6a-4b83-afe9-ab104be65470.png)

I tested with Firefox 91.7.0esr (64-bit) on Debian 11.

**problem**
This is a problem for people doing using the `html_logo` setting in their conf.py, because the site title does not show up anymore.

### Reproduce the bug

1. Create an empty Sphinx documentation project.
2. Configure Sphinx Book Theme in `html_theme`.
3. Copy the sphinx book theme logo from https://sphinx-book-theme.readthedocs.io/en/latest/index.html to your project's `_static/logo-wide.svg`
4. Add `html_logo = "_static/logo-wide.svg"` to the conf.py
5. Build the HTML and view the result in the browser.

### List your environment

* Python 3.9.2
* sphinx-book-theme==0.3.0rc1
* pydata-sphinx-theme==0.8.0
* Sphinx==4.4.0
* Firefox 91.7.0esr (64-bit)

**Comment by choldgraf** [comment]
good catch - I believe this is fixed in https://github.com/executablebooks/sphinx-book-theme/pull/526 - will cut a new release candidate so you can check that this fixes it!

**Comment by ngulden** [comment]
Thanks for the quick additional release candidate. I just tested it and it resolved the problem for me. See the screenshot attached.
![sphinx_book_theme_0 3 0rc2_html_logo_issue](https://user-images.githubusercontent.com/55257/158780290-06216e0e-6e56-40c6-99fb-8deb6b90e135.png)
