### ISSUE TITLE
Is it possible to also make the meta tags in the theme pluggable as well?

### ISSUE THREAD

**Issue by simkimsia** [executablebooks/sphinx-book-theme#530]
### Describe the problem/need and solution

**Context**
I need to add a different HTML meta head element because i am not using google analytics. I want to use [plausible](https://plausible.io/)

**Problem / Idea**
Allow theme user to plugin custom meta head element as and when they need it?

**Solution**
Perhaps follow #470 and make it more pluggable?

**Benefit**
There are several options available for people to do this:

1. make their own theme (very drastic)
2. fork this theme and add their own hardcoded meta element (less drastic than 1 but still pretty drastic)
3. allow [tailoring](https://en.wikipedia.org/wiki/Method_engineering#:~:text=Method%20tailoring%20is%20defined%20as,for%20a%20specific%20project%20situation.) of this theme via a pluggable design (i prefer this)

This would benefit the people trying to have more tailoring within the chosen sphinx-book-theme. 

1. requires maintenance
2. also require maintenance to at least make sure fork keeps pace with upstream
3. least intrusive and keeps flexibility scoped to just meta head elements

### Guide for implementation

Just allow users to write their own html meta and the theme just inserts it. that way, minimum effort on dev and maximum flexibility

**Comment by choldgraf** [comment]
Would [sphinxext-opengraph](https://github.com/wpilibsuite/sphinxext-opengraph) work for you? That's how I've done custom metadata before...

**Comment by pradyunsg** [comment]
You can also explicitly set metadata using `.. meta::` on each page.

**Comment by simkimsia** [comment]
Thank you @choldgraf and @pradyunsg I will start with pradyunsg suggestion because it seems less intrusive. so the meta:: is in the frontmatter of each .md page? assume i am using jupyter-book.

Any documentation on this? I. tried to search by metadata but don't find it. https://jupyterbook.org/start/create.html?highlight=metadata

## separately i realized my question was wrongly phrased

I now realized the desire to swap out google analytics with plausible means i need to insert a script tag not a meta tag in head. Apologies. Directionally, my question is the same. How do i insert custom elements in the head such as a different analytics provider script tag?

**Comment by pradyunsg** [comment]
What exactly do you want to inject?

See https://pradyunsg.me/furo/customisation/injecting/, which is from the documentation of a different theme but it discusses the mechanisms that Sphinx provides for injecting code into any arbitrary theme.

**Comment by choldgraf** [comment]
Also if you're using jupyter book, you can inject scripts via these docs too https://jupyterbook.org/advanced/html.html#custom-css-or-javascript

**Comment by simkimsia** [comment]
i need to insert a javascript snippet in the head. Not to add new javascript code per se. So the injecting custom-css-or-javascript doesn't seem to be applicable. i might be wrong of course

Also I read the custom code injecting for furo, I'm sorry to say I'm at a loss as to how I can use that for my case.

![image](https://user-images.githubusercontent.com/245021/160230822-0cb8ce30-4fa1-4447-8c86-b68fd28992cf.png)

**Comment by simkimsia** [comment]
According to this https://www.sphinx-doc.org/en/master/templating.html#working-with-the-builtin-templates there's this thing called `extrahead` which appears to be how sphinx allows additional stuff into the head element.

I know sphinx-book-theme inherits (?) from pydata so i found this https://github.com/pydata/pydata-sphinx-theme/blob/3c11db8b4e4b764a5bdb2460a44a7f68cb54e26b/src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html#L11

Is there a way to add more script tags  into the extrahead?

**Comment by simkimsia** [comment]
Would it be better if i fork this theme to add the javascript snippet?

**Comment by simkimsia** [comment]
Closing this to consolidate under https://github.com/executablebooks/meta/discussions/726
