### ISSUE TITLE
 conda-forge package seems to be lagging behind

### ISSUE THREAD

**Issue by leroyvn** [executablebooks/sphinx-book-theme#544]
### Describe the bug

I'm using a Conda environment to develop one of my projects and I use the conda-forge channel by default.

The `sphinx-book-theme` package is available there, but only v0.2.0.

I don't know if Conda packaging is done by you, sorry if this question is irrelevant; but is it something expected, or is there something wrong with the Conda package build?

### Reproduce the bug

Simply go to https://anaconda.org/conda-forge/sphinx-book-theme

or search for the package
```
conda search --channel conda-forge sphinx-book-theme
```

**Comment by bollwyvl** [comment]
This is handled over in the conda-forge repo https://github.com/conda-forge/sphinx-book-theme-feedstock.

This PR has been opened to update: https://github.com/conda-forge/sphinx-book-theme-feedstock/pull/25

They get out of sync when certain packaging details change substantially, in this case the new build backend which is ... complicated for conda to consume.

**Comment by pradyunsg** [comment]
@-mention me, if you see issues around sphinx-theme-builder! I see that the PR has been merged,  so I guess you figured it out?

**Comment by leroyvn** [comment]
@bollwyvl I just updated to v0.3.2 using Conda, so I think it's solved. Thanks a lot!

**Comment by choldgraf** [comment]
I'm closing this one as I think it's resolved! If others are interested in helping us make releases on `conda-forge`, please do reach out because we'd love the help!
