### ISSUE TITLE
Broken format when upgrading sphinx version

### ISSUE THREAD

**Issue by dimitraka** [executablebooks/sphinx-book-theme#563]
### Describe the bug

I am using sphinx-book-theme with the following versions sphinx==3.5.4 and breathe==4.16.0. However, when I try to upgrade sphinx version, I am getting a broken format. The docs are built successfully, but it is just the format that is broken.

The problem is that the buttons on top of the page (issues button, full page button, download page button, repository button) are misplaced in the page. Hence, one cannot navigate properly and cannot click on specific areas of the page.

This happens for every newer version for sphinx or breathe.

### Reproduce the bug

Here is a screenshot of the produced docs. 

![Screenshot from 2022-05-26 13-21-30](https://user-images.githubusercontent.com/46675081/170478378-854cdd3f-aa44-4385-9551-c9f6284469b3.png)

Apart from the buttons, one cannot click on the menu on the side i.e. on the Quick Start or Examples as seen in the figure above.

### List your environment

```
sphinx                                 4.5.0
breathe                               4.33.1
sphinx-book-theme                     0.1.7 
docutils                               0.16
```

**Comment by choldgraf** [comment]
this should be fixed with the new update to the pydata theme in #677 !
