### ISSUE TITLE
Unable to customize footer and header 

### ISSUE THREAD

**Issue by Sdaher21** [executablebooks/sphinx-book-theme#565]
### Describe the bug

I'm switching over from sphinx-rtd-theme to sphinx-book-theme and would like to keep some of the same behavior.
I am trying to add a header.html and footer.html under _templates folder but for some reason it's not working:

### Reproduce the bug
In the footer.html, I added the attached:
![image](https://user-images.githubusercontent.com/66412207/171136657-6bc8ed8e-92aa-476c-b805-bd53aaf21ed6.png)

And in the custom.css, I added:
/*Footer*/
.feedback-link {
    display: inline-block;
    float: left;
    font-size: 16px;
}

I couldn't find any documentation either.

**Comment by choldgraf** [comment]
this is getting resolved in #677 !
