### ISSUE TITLE
Update pydata theme to 0.10

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-book-theme#575]
### Context

The PyData Sphinx Theme has made a bunch of improvements and modifications in their latest release, and it has a release candidate out for v0.10 (two minor version bumps from our current pin). Here's the rough changelog:

- https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.10.0rc1

### Things to update / change

Here are some of the big things that have changed, and which we should figure out how to incorporate here:

- We upstreamed a bunch of CSS for extensions, fixing bugs, etc. I suspect that we can reduce a lot of the custom CSS in this theme now.
- We standardized several sections using the `basic-ng` naming. E.g. `bd-sidebar` became `bd-sidebar-primary`. We might need to re-work some of our CSS rules accordingly. I think we might also want to just re-use the same class prefix for this theme (`bd-`) so that we can inherit some of the same CSS behavior.
- New theme sections were added. In particular there's now an `announcements.html` so we might be able to use that instead of re-inventing our own here.
- There is now a Dark Mode in the pydata theme and we need to find ways to inherit it
- There is new search bar functionality via a pop-up instead of a field. We could either make our current field "behave" like a pop-up, which would make it easier to extend to other search services. Or we could just re-use the button
- We need a place for the theme toggle. I think the easiest thing would be to support the `icon-links` component in our sidebar. People could also put site-wide links there if they wished (ref #285)

### Proposal

We can use this PR to make the version bumps. I started it, but **anybody should feel free to take it over and/or push to it**. I think @AakashGfude might be interested in working on this?

- #574

edit: Issue hijacked by Chris to have more detail in it

**Comment by SilverRainZ** [comment]
wow! Looking forward to a new release.
