### ISSUE TITLE
Support Sphinx 5 / docutils >= .18

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#592]
### Context

We should ensure that this theme is compatible with Sphinx 5. See the issue below for a list of helpful links and a checklist:

- https://github.com/executablebooks/meta/issues/750#issue-1255974848

Other issues we should tackle as part of this:

- #590 
- #591

**Comment by ivirshup** [comment]
Just trying to figure out what the status of this is. 

Should #644 have closed this and the referenced issues?

**Comment by choldgraf** [comment]
Yes! good point. Closed by:

- https://github.com/executablebooks/sphinx-book-theme/pull/644

**Comment by ivirshup** [comment]
Great! Thanks for the fast response and looking forward to a release!

**Comment by drupol** [comment]
Looking forward for the new tag as well!
