### ISSUE TITLE
Support additional sidebar customisation in pydata-sphinx-theme

### ISSUE THREAD

**Issue by gilbertbw** [executablebooks/sphinx-book-theme#603]
### Context

The version of pydata-sphinx-theme version currently used, 0.8.0, has the following customisation for the sidebar:

- `show_nav_level` (sets `show_nav_level`, this theme supports it as `show_navbar_depth`)
- `navigation_depth` (sets `maxdepth`)
- `collapse_navigation` (sets `collapse`)

https://github.com/pydata/pydata-sphinx-theme/blob/v0.8.0/src/pydata_sphinx_theme/theme/pydata_sphinx_theme/_templates/sidebar-nav-bs.html

in the `main` branch the same options are available but in a new file https://github.com/pydata/pydata-sphinx-theme/blob/e2b274ae842eccdb3e6a605ce5f2389a27a43550/src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html

I need to customise the `maxdepth` parameter, as our help has 5 levels of help topics, and the hardcoded value currently is 4. My employer may want to set `collapse` as well. It seems to make sense to surface these configuration options together.

### Proposal

Add support for customising the  `navigation_depth` and `collapse_navigation` options.

This requires using the `theme_navigation_depth` and `theme_collapse_navigation` here https://github.com/executablebooks/sphinx-book-theme/blob/f425732ea1c2dd2f1a1ddaf0a89413a14b981baa/src/sphinx_book_theme/theme/sphinx_book_theme/components/sbt-sidebar-nav.html rather than hard coded values.

This is assuming we are happy using the same names for these option as in pydata-sphinx-theme. I suggest this is a good idea as it simplifies understanding these options when e.g. reading the pydata-sphinx-theme documentation. Although we have not done this with `show_nav_level`/`show_navbar_depth`, so maybe keeping consistant with that is more important.

### Tasks and updates

- [ ] Decide on theme option names
- [ ] Possibly add options to `theme.conf`, and support them in `sbt-sidebar-nav.html`
- [ ] Update documentation

**Comment by bradbell** [comment]
I am not sure if the problem below is related to the request above or perhaps I should post this as a separate bug ?

I have been using sphinx_book_theme and found that if you start with sphinx-quickstart :

1. use sphinx_book_theme
2. use :maxdepth: 1 in all the toctree directives
3. put one in the toctree directive in index.rst
4. put two in the toctree directive in one.rst
5. ...
6. put six in the toctree directive in five.rst

The left side bar does not contain any titles below the title or four.rst. If I change from sphinx_book_theme to furo, the left side bar contains the title for all the *.rst files.

**Comment by bradbell** [comment]
@choldgraf  I verified that the current master branch works with the test case mentioned above.
Thanks
