### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#611]
### Context

We've had a number of improvements and bugfixes over the last few months, and a few updates to the pydata theme that will break things, so we should bump our minor version.

[**Milestone for the release is here**](https://github.com/executablebooks/sphinx-book-theme/milestone/2)
We should cut a release to push out these improvements before that update is done. Here's a milestone of issues to add to it:

- https://github.com/executablebooks/sphinx-book-theme/milestone/3

The process of creating a release is here:

- https://executablebooks.org/en/latest/contributing.html#the-process-of-creating-a-release

**Comment by ksuess** [comment]
Hi @choldgraf, @AakashGfude, a release cut v0.3.4 before v.4 would be very welcome. 
'Show active item of main navigation' https://github.com/executablebooks/sphinx-book-theme/issues/608 is fixed and PR is merged. And we miss it desperatly in our [documentation](https://6.dev-docs.plone.org/plone.restapi/docs/source/endpoints/users.html) and [training](https://training.plone.org/5/mastering-plone/index.html).
Thank you!

**Comment by ngulden** [comment]
v0.3.1 is already released, see https://github.com/executablebooks/sphinx-book-theme/releases/tag/v0.3.2. I guess this is a naming mistake. Could it be that you mean v0.3.4?

If yes, can you please update the title of this issue and the milestone to avoid confusion? Thank you.

**Comment by AakashGfude** [comment]
I have updated the title and added an issue in the top comment from pydata-sphinx-theme, which should also be fixed for the release.

**Comment by choldgraf** [comment]
closing this in favor of #686
