### ISSUE TITLE
contributing link

### ISSUE THREAD

**Issue by da5nsy** [executablebooks/sphinx-book-theme#619]
### Context

https://github.com/executablebooks/sphinx-book-theme/blob/master/CONTRIBUTING.md
points to
https://github.com/executablebooks/sphinx-book-theme/blob/master/docs/contributing/index.md

### Proposal

Instead, I think it would be better to point to:
https://sphinx-book-theme.readthedocs.io/en/stable/contributing/index.html

**Comment by choldgraf** [comment]
good catch!
