### ISSUE TITLE
Time for 1.0.0?

### ISSUE THREAD

**Issue by consideRatio** [executablebooks/sphinx-book-theme#622]
First of all, thank you everyone involved for providing a great Sphinx Theme!!! :heart: :tada:!

I write this issue because I see great value in the ability to communicate changes via the version numbers according to a semver2 practice, but those pracices are only defined for when the major version is set. What do you think about going for 1.0.0 as next release, or next non-patch release?

This project's first tagged release was on Apr 23, 2020 - [v0.0.1](https://github.com/executablebooks/sphinx-book-theme/releases/tag/v0.0.1). Following that there was many patch releases and even a pre-release of a patch release such as [v0.0.39b1](https://github.com/executablebooks/sphinx-book-theme/releases/tag/v0.0.39b1). The project is now at 0.3.3. I see an opportunity to let the version number semantics help communicate what changes in between versions going onwards, but it would require an initial bump to 1.0.0.

I'm influenced greatly by reading on https://semver.org, where they suggest one should quickly arrive at 1.0.0. Here is experpt from the section of [__How do I know when to release 1.0.0?__](https://semver.org/#how-do-i-know-when-to-release-100).

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

It seems to me that this project is mature enough, already worrying itself about users experience if introducing breaking changes.

![image](https://user-images.githubusercontent.com/3837114/196157073-18c2cac6-c064-454f-8db2-7171702fbcf7.png)

Thanks for all your work into this project!!!!

**Comment by choldgraf** [comment]
I've got a specific proposal about this here, what do you think?

- https://github.com/executablebooks/sphinx-book-theme/issues/670
