### ISSUE TITLE
Long sidebar title names do not wrap

### ISSUE THREAD

**Issue by adamgayoso** [executablebooks/sphinx-book-theme#624]
### Describe the bug

**context**
When using the sidebar for function names, they can sometimes be quite long and do no properly get wrapped.

**expectation**
Long names to wrap

### Reproduce the bug

<img width="307" alt="Screen Shot 2022-10-20 at 9 56 54 AM" src="https://user-images.githubusercontent.com/10859440/197011685-e5f449d5-d392-4815-bfc7-958dff27824a.png">

https://infercnvpy.readthedocs.io/en/latest/api.html

**Comment by choldgraf** [comment]
This one is now resolved by the latest inheritance from the pydata theme!
