### ISSUE TITLE
Remove as much as we can from this theme and instead inherit from the pydata theme

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#630]
### Context

Now that we've got this theme based on the latest PyData theme, we should see what we can "inherit" from that theme rather than re-creating the wheel here as well. This will help boost the maintainability of this theme, and make it easier for us to inherit upstream improvements when they are made.

### Proposal

I propose that we do an audit of the following areas of this theme, and try to remove as much as we can while retaining the same end experience more or less:

- CSS rules and variables
- JavaScript functionality
- HTML template structure
- Python sphinx build infrastructure

There are probably a few places where we'll need to keep our own customizations (like margin content and the drop-down table of contents) but if we can cut out all of the stuff that's already done well in the pydata theme, this would help minimize confusion and unnecessary differences between them.

**Comment by choldgraf** [comment]
@AakashGfude I think that I have the most context about what we _could_ try to remove, but I also have very little time to develop this theme right now, and also need to be focusing my efforts on the governance work for the project.

What do you think about this plan:

1. I take a stab at removing everything that I think I can remove. This will likely result in a slightly-broken version of the theme where some things are off.
2. I hand-off to you to make the necessary tweaks to get the theme back to where it was before in functionality

Would that work?

**Comment by AakashGfude** [comment]
Hi @choldgraf , yes that will work for sure. Let me know when you are done with step 1.

**Comment by choldgraf** [comment]
I spent a bit of time this weekend doing as much as I could - check out this PR for you to take over and/or commit to directly:

- https://github.com/executablebooks/sphinx-book-theme/pull/640
