### ISSUE TITLE
Unable to set footer.html template

### ISSUE THREAD

**Issue by Sdaher21** [executablebooks/sphinx-book-theme#638]
I want to use my own footer.html template using sphinx-book-theme. I created it like this (not sure it's right) and then used the extra_footer in the html_theme_options:
![image](https://user-images.githubusercontent.com/66412207/199543019-4c56c4d9-7508-48d8-a0c9-8beac3c22c71.png)

For some reason, the output just says footer at the bottom and not the content of the .html file.

**Comment by choldgraf** [comment]
I'm adding footer support in #677 - I'll close this once that is merged!
