### ISSUE TITLE
Improve documentation of "Add download page button"

### ISSUE THREAD

**Issue by KKJSP** [executablebooks/sphinx-book-theme#639]
### Context

The [Add download page button](https://sphinx-book-theme.readthedocs.io/en/stable/customize/download.html) states how the download button can be added to the page. However, with default settings, the behaviour of that button is unexpected. For example, an `.ipynb` is displayed in the browser as an `.ipynb.txt` file when the download button is clicked, while the objective of the user was most likely to download the Jupyter notebook itself.

This happens because by default `html_sourcelink_suffix=".txt"` and the `.ipynb` files are saved as `.ipynb.txt`. If the `html_sourcelink_suffix=""` then `.ipynb` file is downloadable as expected.

### Proposal

Add a note about setting `html_sourcelink_suffix=""` in the `conf.py` file on the [Add download page button](https://sphinx-book-theme.readthedocs.io/en/stable/customize/download.html) documentation to clarify the behaviour of the button.

**Comment by afeld** [comment]
Seems like this may have been fixed in https://github.com/executablebooks/sphinx-book-theme/pull/683, see mentions of `html_source_suffix`.

**Comment by KKJSP** [comment]
Thanks. Closing the issue as done.
