### ISSUE TITLE
Make line numbers a different color in code blocks

### ISSUE THREAD

**Issue by nathan-hess** [executablebooks/sphinx-book-theme#656]
### Context

Suppose a code block is created with the following content:
```
.. code-block:: text
    :linenos:

    Line 1
    Line 2
    Line 3
```

The result in the HTML page is rendered as:
![image](https://user-images.githubusercontent.com/63890205/206885336-5b410d82-241c-4847-81e3-a17cd0976240.png)

Visually, this makes it appear that the line numbers are part of the text, which can be confusing for readers.

### Proposal

I would suggest making the line numbers "grayed out" and possibly a smaller font size so it's clear they aren't part of the code.

For example, this is the style used by [PyData Sphinx Theme](https://github.com/pydata/pydata-sphinx-theme):
![image](https://user-images.githubusercontent.com/63890205/206885418-6f0df8a7-c478-437f-bae8-699944812246.png)

I'm guessing there may be some way to accomplish this with custom, user-specific CSS, but I'm not terribly familiar with how this works, and I feel it would be more appropriate to make a change on a package level since this could create confusion for any project using the theme.

**Comment by choldgraf** [comment]
We will soon inherit the new code block coloring from the pydata sphinx theme, and I think this will do the greying-out that you suggest:

https://pydata-sphinx-theme.readthedocs.io/en/stable/examples/kitchen-sink/generic.html#code-with-sidebar

**Comment by nathan-hess** [comment]
> We will soon inherit the new code block coloring from the pydata sphinx theme, and I think this will do the greying-out that you suggest:
> 
> https://pydata-sphinx-theme.readthedocs.io/en/stable/examples/kitchen-sink/generic.html#code-with-sidebar

Thanks for this information!  I'll look forward to that new update.  I'll close this issue since it seems it's addressed already, but feel free to reopen if you'd like to keep it around for task-tracking purposes.
