### ISSUE TITLE
Release needed for already added sphinx5 compatibility (currently 0.3.3)

### ISSUE THREAD

**Issue by consideRatio** [executablebooks/sphinx-book-theme#665]
Can someone help get a release out of this project?

- Sphinx 5 support has already been added in this repo by @AakashGfude https://github.com/executablebooks/sphinx-book-theme/pull/644
- Work done in jupyter-book by @mmcky in https://github.com/executablebooks/jupyter-book/pull/1842 is blocked until a release is made in this repo.
- Current version is 0.3.3, see https://github.com/executablebooks/sphinx-book-theme/releases/tag/v0.3.3.

## Related

- #622
  I argue that a 1.0.0 release should be made rather than 0.3.4 or 0.4.0 - as soon as possible, for example now.

**Comment by choldgraf** [comment]
I've made a pre-release of this today, so we can start to test it out in the jupyter book PR. I say we leave the pre-release for a little bit and then we can make a full release if there are no problems that pop up.

I also opened up an issue with a proposal for 1.0:

- https://github.com/executablebooks/sphinx-book-theme/issues/670

**Comment by consideRatio** [comment]
Thanks @choldgraf, I'd be happy to help with some chores!

**Comment by choldgraf** [comment]
@consideRatio sounds good - I have added you as a maintainer on this repository :-) thanks for offering to help out!

**Comment by jakevdp** [comment]
I tested the 0.4.0rc1 on the documentation build for JAX: https://jax--13906.org.readthedocs.build/en/13906/index.html Did some spot-checks and everything is looking good! Thanks for maintaining this project 😁
