### ISSUE TITLE
Anchor links have incorrect offset from top of screen

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#667]
When you click an in-page link (e.g. an anchor link) the link target is partially blocked by the article header.

This is because we are over-riding the `header-height` here to be 0px:

https://github.com/executablebooks/sphinx-book-theme/blob/8e087097e90c530440a25f724423faf6c99c2c37/src/sphinx_book_theme/assets/styles/abstracts/_variables.scss#L39

The pydata theme is setting `scroll-padding-top` to be relative to this height, which is why setting the height to 0 is causing this to overlap.

**Comment by mathbunnyru** [comment]
A few other things I noted during comparison:

pre-release: https://jupyter-docker-stacks--1855.org.readthedocs.build/en/1855/using/recipes.html
stable: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html

1. In the pre-release version anchers are grey (they are not black). I liked black version better, but it might be my taste.

<img width="351" alt="Screenshot 2023-01-05 at 19 08 23" src="https://user-images.githubusercontent.com/12270691/210813182-0d51e0bd-bfae-495e-985d-ecb225b03927.png">
<img width="341" alt="Screenshot 2023-01-05 at 19 08 27" src="https://user-images.githubusercontent.com/12270691/210813189-a287f75c-74c5-4f0e-99bb-dd42b5265720.png">

2. I liked the text and the centred logo in the left-up corner. Now there is only a logo and it's not centred.

<img width="273" alt="Screenshot 2023-01-05 at 19 12 24" src="https://user-images.githubusercontent.com/12270691/210813355-7f07dd7e-290f-4b53-9150-e2b7b9f12dd1.png">
<img width="262" alt="Screenshot 2023-01-05 at 19 12 28" src="https://user-images.githubusercontent.com/12270691/210813361-1c3c8d73-3fe7-4ddd-b049-b9cb67f4e81e.png">

3. "Search the docs..." and "⌘ + K" are clashing.

4. Italic text in the anchors adds an extra space in the `contents` section. I think it might have happened before, but it's visible now.

<img width="233" alt="Screenshot 2023-01-05 at 19 09 33" src="https://user-images.githubusercontent.com/12270691/210813670-0041af48-db45-4afb-80b9-c3a673102173.png">
<img width="238" alt="Screenshot 2023-01-05 at 19 09 37" src="https://user-images.githubusercontent.com/12270691/210813674-bcadbc73-510c-462d-8219-1778d3af0d95.png">

**Comment by choldgraf** [comment]
this is super helpful, thanks! that's what we have pre-releases for :-)

**Comment by choldgraf** [comment]
In the PR linked above I also fixed the header color change, there are a few others that we'll need to follow up on separately. Could you open issues for them?

- Re: the extra whitespace in the navbar items, that's an upstream issue: https://github.com/pydata/pydata-sphinx-theme/issues/1076
- Re: the logo centering, that is now fixed
- Re: the title not showing up, I'm not sure why that is, can you open a bug issue to track it? That is unexpected.
- Re: `search the docs` clash - I agree it's not the nicest...want to open an issue to figure out what to do about it?

**Comment by mathbunnyru** [comment]
I added two issues for the last 2 problems.
Also added a note that whitespace is quite important in the upcoming release (because it is easily seen and doesn't look nice).

Thanks for all the fixes, it looks much better now.

**Comment by choldgraf** [comment]
> Also added a note that whitespace is quite important in the upcoming release (because it is easily seen and doesn't look nice).

I agree - I just cannot for the life of me figure out how to fix it :-D
