### ISSUE TITLE
The title is missing in the v0.4.0rc1

### ISSUE THREAD

**Issue by mathbunnyru** [executablebooks/sphinx-book-theme#671]
### Describe the bug

The title `Docker Stacks documentation` on the upper left side is missing.

### Reproduce the bug

pre-release: https://jupyter-docker-stacks--1855.org.readthedocs.build/en/1855/using/recipes.html
stable: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html

<img width="273" alt="Screenshot 2023-01-05 at 19 12 24" src="https://user-images.githubusercontent.com/12270691/210813355-7f07dd7e-290f-4b53-9150-e2b7b9f12dd1.png">
<img width="262" alt="Screenshot 2023-01-05 at 19 12 28" src="https://user-images.githubusercontent.com/12270691/210813361-1c3c8d73-3fe7-4ddd-b049-b9cb67f4e81e.png">

**Comment by melund** [comment]
Is this because of the fall back to PyData-Theme options where you need to explicitly set the following to get the title? 
```
html_theme_options = {
    "logo": {
        "text": "My awesome documentation",
    }
}
```
