### ISSUE TITLE
Large tables overflow and create a horizontal scroller

### ISSUE THREAD

**Issue by yafimvo** [executablebooks/sphinx-book-theme#673]
### Describe the bug

**context**
When I use jupyter notebook to print a large table it generates a horizontal scroller on the screen

I expected the page to contain large-width tables

Image:

![image](https://user-images.githubusercontent.com/103026689/211567545-9c4b06df-3dbb-4ec8-a459-9597f9cbf644.png)

**problem**
This is a problem for people using notebooks to generate large tables in their docs because it might affect the readability

### Reproduce the bug

notebook attached

[large-table-html-notebook.zip](https://github.com/executablebooks/sphinx-book-theme/files/10393049/large-table-html-notebook.zip)

```
jupyter-book build --all large-table-html-notebook.ipynb
```

result
![image](https://user-images.githubusercontent.com/103026689/211825654-1f2867ef-89ee-4e5a-b1cd-41cef336c7f7.png)

### List your environment

```
Jupyter Book      : 0.13.1
External ToC      : 0.2.4
MyST-Parser       : 0.15.2
MyST-NB           : 0.13.2
Sphinx Book Theme : 0.3.3
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.13
```

**Comment by choldgraf** [comment]
I believe that this one is now fixed via the pydata theme update!
