### ISSUE TITLE
Long project names/titles no longer wrap in left navigation (version 0.4.0rc1)

### ISSUE THREAD

**Issue by jonascj** [executablebooks/sphinx-book-theme#681]
### Describe the bug

**context**
I was trying out sphinx-book-theme v. 0.4.0rc1 when I noticed that long project names/titles did no longer wrap in the left navigation panel.

![Screenshot from 2023-02-15 13-18-46](https://user-images.githubusercontent.com/3301843/219030063-1f8c9391-0c55-4026-8a4f-f09a46d07e9f.png)

**expectation**
The long name/title should wrap like it did in v. 0.3.3

![Screenshot from 2023-02-15 13-21-04](https://user-images.githubusercontent.com/3301843/219030003-e24bdbed-6ada-4e32-a168-14f86035f898.png)

**bug**
The difference (or bug) seem to be caused by the title-link no longer having the class ``text-wrap``.

v0.4.0rc1
``` html
<a href="#" class="navbar-brand logo">
    <p class="title logo__title" style="/*! white-space: normal; */">Very Long and Complicated Project Name</p>
</a>
```

v0.3.3
```html
<a href="#" class="navbar-brand logo text-wrap">
    <p class="title logo__title" style="/*! white-space: normal; */">Very Long and Complicated Project Name</p>
</a>
```

I am not sure if this is a problem with **pydata-sphinx-theme**, but I think not since the pydata-sphinx-theme has the project title in an element which is the full width of the page instead of a narrow left panel (https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html).

**problem**
This is a problem for projects without logos or short names - like books. 

This issue https://github.com/executablebooks/sphinx-book-theme/issues/624 is somewhat related, or at least adding the class ``text-wrap`` to the left navigation links would likely solve the issue.

### Reproduce the bug

Build a project with a long title such as ``Very Long and Complicated Project Name`` and version 0.4.0rc1 of this theme. Notice how the title overflows the left navigation panel in the generated HTML-documentation (see the previous screenshot).

### List your environment

I did not build with jupyter-book but with Sphinx (on Linux).

Sphinx version: 5.3.0
sphinx-book-theme version: 0.4.0rc1

**Comment by choldgraf** [comment]
good catch, will fix in #677
