### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: toggle-primary-sidebar.html

### ISSUE THREAD

**Issue by AlexanderJuestel** [executablebooks/sphinx-book-theme#719]
### Describe the bug

**context**
When I creating the the documentation page of GemGIS (https://gemgis.readthedocs.io/en/latest/), I have recently started to see an error: `jinja2.exceptions.TemplateNotFound: toggle-primary-sidebar.html.`

**expectation**
No error to occur

**bug**
The creating of the docs fails --> https://readthedocs.org/projects/gemgis/builds/20023049/

### Reproduce the bug

The creating of the docs fails --> https://readthedocs.org/projects/gemgis/builds/20023049/

**Comment by jayaddison** [comment]
Hi @AlexanderJuestel - the earliest failed build that I see with this error is from 2023-03-02: https://readthedocs.org/projects/gemgis/builds/19649141/

That looks like it's fairly soon after v1.0.0 of `sphinx-book-theme` was released (including some breaking changes, most likely).

Have you consulted the [changelog](https://github.com/executablebooks/sphinx-book-theme/blob/master/CHANGELOG.md#v100----2023-03-01) for any relevant items?

**Comment by AlexanderJuestel** [comment]
@jayaddison Thanks for the hint! I will check out the changelog. A temporary solution could be to pin the book theme to an earlier version?

**Comment by jayaddison** [comment]
@AlexanderJuestel it could be, yep - if possible though, I'd recommend trying to find the relevant change that introduced the problem, and whether it's a bug/known-issue.  If so, then it'll be easier to follow along and unpin the version (or to change this theme appropriately when ready to upgrade).

**Comment by AlexanderJuestel** [comment]
@jayaddison One thing that I could find right away is https://github.com/executablebooks/sphinx-book-theme/pull/677/commits/60bcb7df8ea7536d09495223a32261f0dcfd0052#diff-d9e027334fa1c4b5093d44ff026f62f9e4d092fa735da8ffd1e6b96c0f645f3f

However, the changes made to https://github.com/sphinx-doc/sphinx/commits/master/sphinx/jinja2glue.py were not very revealing to me about what could have been broken.

**Comment by jayaddison** [comment]
Ok, thanks @AlexanderJuestel.  The `jinja2glue.py` file seems to iterate through a series of template loaders (each with their own paths configured), and one of those _should_ find and load the `toggle-primary-sidebar.html` file (that exists inside a `components` directory).

Currently I'm looking into the code here to try to figure out whether this additional file path is being considered at load-time: https://github.com/executablebooks/sphinx-book-theme/blob/c2664ddfbe2c3fcfaa819a57835f00ca58346cb9/src/sphinx_book_theme/__init__.py#L191-L198

**Comment by jayaddison** [comment]
A self-correction: I now believe that this is the relevant code to look at: https://github.com/executablebooks/sphinx-book-theme/blob/c2664ddfbe2c3fcfaa819a57835f00ca58346cb9/src/sphinx_book_theme/__init__.py#L259-L261

Perhaps that additional entry in the template path list isn't being retained, for some reason.

**Comment by jayaddison** [comment]
Some more notes:

### Dependency versions
- Downgrading `sphinx-book-theme` to v0.3.3 does allow `gemgis` documentation to build
- Building with v1.0.0 fails due to an unrelated error
- Building with v1.0.0 fails due to the error reported here

So there does appear to be an incompatibility related to v1.x that `gemgis` may need to address (or that may be a bug here).

### Template origin
The `sphinx-book-theme` Sphinx theme depends upon (but does not inherit from?) `pydata-sphinx-theme`.

The [`toggle-primary-sidebar.html` file](https://github.com/executablebooks/sphinx-book-theme/blob/c2664ddfbe2c3fcfaa819a57835f00ca58346cb9/src/sphinx_book_theme/theme/sphinx_book_theme/components/toggle-primary-sidebar.html) is part of `sphinx-book-theme`.

But the error that appears in the build output seems to be in the context of `pydata-sphinx-theme`:

```
Extension error (pydata_sphinx_theme):
Handler <function update_and_remove_templates at 0x...> for event 'html-page-context' threw an exception (exception: toggle-primary-sidebar.html)
```

Why is that?  Could there be a mismatch between the template search paths for the two themes?

**Comment by jayaddison** [comment]
Sorry, @AlexanderJuestel - I've taken more of a look at this, but haven't been able to figure out what the root of the problem is.  As you suggest, limiting the `sphinx-book-theme` version (to `<1.0.0`, or `==0.3.3`, for example) should provide a workaround.

**Comment by AlexanderJuestel** [comment]
@jayaddison thanks for checking, I will try limiting the version and get back to you ASAP

**Comment by AlexanderJuestel** [comment]
@jayaddison Limiting the version to 0.3.3 resolves the issue. Closing this for now.

**Comment by adam-grant-hendry** [comment]
> Why is that? Could there be a mismatch between the template search paths for the two themes?

The template `toggle-primary-sidebar.html` is [defined in sphinx-book-theme](https://github.com/executablebooks/sphinx-book-theme/blob/c2664ddfbe2c3fcfaa819a57835f00ca58346cb9/src/sphinx_book_theme/theme/sphinx_book_theme/components/toggle-primary-sidebar.html), which inherits from [pydata-sphinx-theme](https://github.com/executablebooks/sphinx-book-theme/blob/c2664ddfbe2c3fcfaa819a57835f00ca58346cb9/src/sphinx_book_theme/theme/sphinx_book_theme/theme.conf#L2).

It appears the method [`_remove_empty_templates`](https://github.com/pydata/pydata-sphinx-theme/blob/feb2bc2b7b64620fccdd88ae12fab19bd0c10412/src/pydata_sphinx_theme/__init__.py#L213) is intended for `pydata-sphinx-theme` templates, but will check other templates that derive from it, which is causing this error.

A full traceback is:

```
Traceback (most recent call last):
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\pydata_sphinx_theme\__init__.py", line 224, in update_and_remove_templates
    context[section] = list(filter(_remove_empty_templates, context[section]))
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\pydata_sphinx_theme\__init__.py", line 219, in _remove_empty_templates    
    rendered = app.builder.templates.render(tname, context)
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\jinja2glue.py", line 196, in render
    return self.environment.get_template(template).render(context)
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\jinja2glue.py", line 217, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: toggle-primary-sidebar.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\cmd\build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\application.py", line 353, in build
    self.builder.build_update()
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\builders\__init__.py", line 311, in build_update
    self.build(to_build,
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\builders\__init__.py", line 378, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\builders\__init__.py", line 586, in write
    self._write_serial(sorted(docnames))
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\builders\__init__.py", line 596, in _write_serial
    self.write_doc(docname, doctree)
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\builders\html\__init__.py", line 672, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\builders\html\__init__.py", line 1076, in handle_page
    newtmpl = self.app.emit_firstresult('html-page-context', pagename,
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\application.py", line 481, in emit_firstresult
    return self.events.emit_firstresult(event, *args,
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\events.py", line 117, in emit_firstresult
    for result in self.emit(name, *args, allowed_exceptions=allowed_exceptions):
  File "C:\Users\hendra11\Code\external\poetry_plugin_constrain\.venv\lib\site-packages\sphinx\events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function update_and_remove_templates at 0x000001B8B89F7AF0> for event 'html-page-context' threw an exception (exception: toggle-primary-sidebar.html)

Extension error (pydata_sphinx_theme):
Handler <function update_and_remove_templates at 0x000001B8B89F7AF0> for event 'html-page-context' threw an exception (exception: toggle-primary-sidebar.html)
```

**Comment by adam-grant-hendry** [comment]
I believe a fix would be to remove [`app.config.templates_path` line](https://github.com/pydata/pydata-sphinx-theme/blob/36847fc2a816b10eba51415563832ac10341070b/src/pydata_sphinx_theme/__init__.py#L302) and have both `pydata-sphinx-theme` and `sphinx-book-theme` use the `html_theme_path`, though not sure yet how to set that when writing an extension.

**NOTE:** `sphinx` isn't pointed to the `components/`, `macros/`, `sections/`, etc. subfolders when looking for templates in the `sphinx-book-theme` theme even when the [`pydata-sphinx-theme` `app.config.template_path` line is commented out](https://github.com/pydata/pydata-sphinx-theme/blob/36847fc2a816b10eba51415563832ac10341070b/src/pydata_sphinx_theme/__init__.py#L302):

![image](https://github.com/pydata/pydata-sphinx-theme/assets/59346180/33f133b1-3fe3-4e8b-9950-f0a1c9d932d6)

**Comment by adam-grant-hendry** [comment]
> but is messed up when it gets to the point of prepending explicit template paths:

**Actually**, it appears `sphinx-book-theme` also [appends to the `templates_path`](https://github.com/executablebooks/sphinx-book-theme/blob/216e1bc53605ef0e6820b9019aab3f9354995419/src/sphinx_book_theme/__init__.py#L261C26-L261C26), but what is odd is **_that the `"components"` portion of the path is missing._**

**Comment by adam-grant-hendry** [comment]
It looks like this issue was fixed in [`sphinx-book-theme` PR #566](https://github.com/executablebooks/sphinx-book-theme/pull/566/files#diff-323e2d703544f60dac082d2b47d8b6a2d8e1594eb3b8f49d569f48f768379252R189) precisely how I would have though to fix it: create a `config-inited` event:

```python
app.connect("config-inited", update_general_config)
```

but it looks like it was changed to a `'builder-inited'` event in [PR #691](https://github.com/executablebooks/sphinx-book-theme/commit/9e2bc2f63f2637b44c215209a27cb726354a89bd):

```python
app.connect("builder-inited", update_general_config)
```

This looks like it was a mistake.

**Comment by adam-grant-hendry** [comment]
I can confirm reverting to:

```
app.connect("config-inited", update_general_config)
```

and

```python
def update_general_config(app, config):  # add config argument back
    ...
```

fixes the problem.

**Comment by adam-grant-hendry** [comment]
@AlexanderJuestel @jayaddison You have `sphinx-book-theme` added to `extensions` when it is[ only intended to be added to `html_theme`](https://github.com/executablebooks/sphinx-book-theme/pull/770#discussion_r1379425399). Remove `sphinx-book-theme` from the `extensions` list, and your problem should be fixed.
