### ISSUE TITLE
Not all CSS is applied with latest version of pydata-sphinx-theme

### ISSUE THREAD

**Issue by lucaspcamargo** [executablebooks/sphinx-book-theme#761]
### Describe the bug

When I regenerated my website a bit earlier today...
I expected it to look the same as always.

However, some CSS fails to apply. I see a blueish background color, purple link underlines from pydata-sphinx-theme, and larger icons.

Maybe something changed with the latest version of pydata-sphinx-theme which is breaking the latest version of this theme.

### Reproduce the bug

I believe that regenerating a page with the latest version of pydata-sphinx-theme should be enough to reproduce the issue.

When I add `pydata-sphinx-theme==0.13.3` to my requirements file, as a current workaround, the issue vanishes.

### List your environment

Here is my venv:

```
ablog==0.11.5
accessible-pygments==0.0.4
alabaster==0.7.13
Babel==2.12.1
beautifulsoup4==4.12.2
certifi==2023.7.22
charset-normalizer==3.2.0
docutils==0.19
feedgen==0.9.0
idna==3.4
imagesize==1.4.1
insegel==1.3.1
invoke==2.2.0
Jinja2==3.1.2
livereload==2.6.3
lxml==4.9.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdit-py-plugins==0.4.0
mdurl==0.1.2
myst-parser==2.0.0
packaging==23.1
pydata-sphinx-theme==0.14.0
Pygments==2.16.1
python-dateutil==2.8.2
PyYAML==6.0.1
requests==2.31.0
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==6.2.1
sphinx-book-theme==1.0.1
sphinx-favicon==1.0.1
sphinx-notfound-page==1.0.0
sphinx-sitemap==2.5.1
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
tornado==6.3.3
typing_extensions==4.7.1
urllib3==2.0.4
watchdog==3.0.0
```

**Comment by pietronvll** [comment]
Same issue here for a documentation hosted on Read The Docs. Adding `pydata-sphinx-theme==0.13.3` _before_ `sphinx-book-theme` in the requirements file solves the problem.
