### ISSUE TITLE
PyData theme CSS resulted in unexpected changes to this theme's style

### ISSUE THREAD

**Issue by Gouvernathor** [executablebooks/sphinx-book-theme#765]
Recent changes to the style have made the dark theme's background bluish instead of dark grey, and the hovered links purple instead of blue.
The preceding style was much better so I believe that change should be reverted, or at least an option provided to opt-out and go back to the former colors.

Former :
![image](https://github.com/executablebooks/sphinx-book-theme/assets/44340603/ea7f30b9-ff23-4c1f-b5d3-9b4dca0ac15a)
New :
![image](https://github.com/executablebooks/sphinx-book-theme/assets/44340603/747975de-fab7-4cdb-a2e2-8fb4265423db)

**Comment by Gouvernathor** [comment]
I also wouldn't mind disabling the "Back to top" button spawning in the bottom half of the screen, at lease when you're not on a phone. It's not strictly related to the theme color issue, but I don't want to spam the tracker.

**Comment by choldgraf** [comment]
A lot of these were inherited from the PyData Sphinx Theme, which made these updates to improve the accessibility of the theme in general. I don't think we should revert changes that we know improve accessibility (e.g. color contrast) just because we think they don't look as good, but if we can identify improvements that are equally as accessible, then I'm fine implementing them here.

**Comment by Gouvernathor** [comment]
With the font color remaining stark white, since turning the background from pitch black to dark blue _decreases_ the contrast between them, I don't understand how it _improves_ accessibility,
I can understand accessibility reasons for having the hovered links purple instead of brighter blue, it feels weird since it's a deviation from the standard but if the accessibiliity reasons are solid I guess you have to start somewhere.

For the "back to top" button, I doubt that's related (but I don't think you were saying that).

**Comment by choldgraf** [comment]
I just added some changes to address some of these in #775 - can you take a look there? I think it'll be more productive to make some minor adjustments to this theme rather than to re-litigate the long accessibility discussions that happened already in the pydata theme
