### ISSUE TITLE
Missing whitespace before "Contents"

### ISSUE THREAD

**Issue by MarcinKrupnik** [executablebooks/sphinx-book-theme#778]
### Describe the bug

There is missing whitespace before "Contents" in right sidebar of theme.
In theme page
https://sphinx-book-theme.readthedocs.io/en/latest/
![image](https://github.com/executablebooks/sphinx-book-theme/assets/57331452/462f4a9f-9da4-4d7a-bd7f-a97d61c938cc)
In myst Page:
https://myst-parser.readthedocs.io/en/latest/intro.html
![image](https://github.com/executablebooks/sphinx-book-theme/assets/57331452/2b3ed129-35fb-429d-a628-6d906259d2c1)
When I change theme page link word "latest" to "stable", style works correctly, but i cant do this same in my github pages link.

### Reproduce the bug

Go to: https://sphinx-book-theme.readthedocs.io/en/latest/
See "=Contest" There are missing whitespace
Go to: https://sphinx-book-theme.readthedocs.io/en/stable/
See "= Contest"
Go to: https://myst-parser.readthedocs.io/en/latest/intro.html
See "= Contest"

### List your environment

Sphinx==6.2.1
sphinx-book-theme==1.0.1
myst-parser[linkify]==2.0.0
sphinx_design==0.5.0

**Comment by choldgraf** [comment]
I think this one just got fixed by #775 actuall!
