### ISSUE TITLE
1.1.0rc PyPi wheels missing

### ISSUE THREAD

**Issue by PhilipVinc** [executablebooks/sphinx-book-theme#782]
### Describe the bug

The publish to Pypi run failed 

https://github.com/executablebooks/sphinx-book-theme/actions/runs/6870341669

### Reproduce the bug

```
```

### List your environment

```
```

**Comment by agoose77** [comment]
So it did! Thank you for reporting.

**Comment by choldgraf** [comment]
Ugh, it's two failing tests that arguably aren't important for the release to be useful to people.

One is a bug in the sphinx-theme-builder that makes it impossible to build the wheel on windows machines (but we use Linux to build wheels)

One is a bug in the documentation build somewhere ([link here](https://github.com/executablebooks/sphinx-book-theme/actions/runs/6870341669/job/18685010467)). I think we should just build and push it. I'll try to resolve the docs build and remove the dependency on the windows build.

**Comment by agoose77** [comment]
> One is a bug in the sphinx-theme-builder that makes it impossible to build the wheel on windows machines (but we use Linux to build wheels)

I'm reluctant to put out an sdist that won't build on Windows, so I'm holding until the upstream bug here is fixed. Let me chase that up ...

**Comment by choldgraf** [comment]
Here is the issue I opened in the stb repo:

- https://github.com/pradyunsg/sphinx-theme-builder/issues/46

**Comment by flying-sheep** [comment]
There is a giant pile of buggy old releases being pulled in by 1.0, I’m pretty desperate for having a 1.1.0rc wheel on PyPI.

**Comment by choldgraf** [comment]
@agoose77 doesn't this build failure just mean that people won't be able to *develop* this theme on windows, not that they won't be able to *use* it? If that's the case I suggest we just cut a release as an RC. We can fix the windows but in an RC2.

**Comment by agoose77** [comment]
OK - I was hoping we could just get a proper release done by fixing
upstream so that our sdist's aren't buggy. However, we can make an rc, to
unblock workflows.
