### ISSUE TITLE
Whitespace from quote in collapsed admonition block

### ISSUE THREAD

**Issue by psychemedia** [executablebooks/sphinx-book-theme#786]
### Describe the bug

A quote inside an admonition block is rendered as a blank block element inside a collapsed admonition block (`:class: dropdown`)

<img width="1046" alt="image" src="https://github.com/executablebooks/sphinx-book-theme/assets/82988/6d067312-ebd0-48af-a540-6fd9e04e3219">

### Reproduce the bug

Example in admoniton *A scandalous and unfounded statement*, https://psychemedia.github.io/storytelling-notes/press_gang.html

### List your environment

Jinja2-3.1.2 MarkupSafe-2.1.3 Pygments-2.17.2 accessible-pygments-0.0.4 alabaster-0.7.13 asttokens-2.4.1 attrs-23.1.0 babel-2.13.1 beautifulsoup4-4.12.2 certifi-2023.11.17 charset-normalizer-3.3.2 click-8.1.7 comm-0.2.0 debugpy-1.8.0 decorator-5.1.1 docutils-0.18.1 exceptiongroup-1.2.0 executing-2.0.1 fastjsonschema-2.19.0 greenlet-3.0.1 idna-3.6 imagesize-1.4.1 importlib_metadata-6.9.0 ipykernel-6.27.1 ipython-8.18.1 jedi-0.19.1 jsonschema-4.20.0 jsonschema-specifications-2023.11.2 jupyter-book-0.15.1 jupyter-cache-0.6.1 jupyter-client-8.6.0 jupyter-core-5.5.0 latexcodec-2.0.1 linkify-it-py-2.0.2 markdown-it-py-2.2.0 matplotlib-inline-0.1.6 mdit-py-plugins-0.3.5 mdurl-0.1.2 myst-nb-0.17.2 myst-parser-0.18.1 nbclient-0.7.4 nbformat-5.9.2 nest-asyncio-1.5.8 ou-jupyter-book-tools-0.0.4 packaging-23.2 parso-0.8.3 pexpect-4.9.0 platformdirs-4.0.0 prompt-toolkit-3.0.41 psutil-5.9.6 ptyprocess-0.7.0 pure-eval-0.2.2 pybtex-0.24.0 pybtex-docutils-1.0.3 pydata-sphinx-theme-0.14.4 python-dateutil-2.8.2 pyyaml-6.0.1 pyzmq-25.1.1 referencing-0.31.1 requests-2.31.0 rpds-py-0.13.2 six-1.16.0 snowballstemmer-2.2.0 soupsieve-2.5 sphinx-5.0.2 sphinx-book-theme-1.0.1 sphinx-comments-0.0.3 sphinx-copybutton-0.5.2 sphinx-design-0.3.0 sphinx-external-toc-0.3.1 sphinx-jupyterbook-latex-0.5.2 sphinx-multitoc-numbering-0.1.3 sphinx-thebe-0.2.1 sphinx_togglebutton-0.3.2 sphinxcontrib-applehelp-1.0.7 sphinxcontrib-bibtex-2.5.0 sphinxcontrib-devhelp-1.0.5 sphinxcontrib-htmlhelp-2.0.4 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.6 sphinxcontrib-serializinghtml-1.1.9 sqlalchemy-2.0.23 stack-data-0.6.3 tabulate-0.9.0 tornado-6.4 traitlets-5.14.0 typing-extensions-4.8.0 uc-micro-py-1.0.2 urllib3-2.1.0 wcwidth-0.2.12 wheel-0.42.0 zipp-3.17.0

**Comment by choldgraf** [comment]
I believe this has been fixed in the upcoming release, here's a pre-release for it:

https://github.com/executablebooks/sphinx-book-theme/releases/tag/v1.1.0rc1

Can you double check?

**Comment by choldgraf** [comment]
I'll close this under the presumption that it is resolved, but after you've tried 1.1 if it doesn't work, please re-ping here!
