### ISSUE TITLE
1.1.0rc2 breaks its own styles on ReadTheDocs

### ISSUE THREAD

**Issue by flying-sheep** [executablebooks/sphinx-book-theme#795]
### Describe the bug

**context**
Our most recent build of https://scverse-tutorials.readthedocs.io/en/latest/ has broken CSS.

I suspect it’s because of 1.1.0rc2 being released an hour ago. I see on RTD:

```
Successfully installed accessible-pygments-0.0.4 […] sphinx-book-theme-1.1.0rc2 […]
```

Further info:
- [We set `html_static_path = ["_static"]`](https://github.com/scverse/scverse-tutorials/blob/071c0b2762ba0db2b589748e4e8dd0315c253d02/docs/conf.py#L108)
- When building locally, the issue does *not* appear

**expectation**
CSS paths are constructed correctly on RTD.

**bug**

```html
    <link rel="stylesheet" type="text/css" href="_static/pygments.css?v=80d5e7a1" />
    <link digest="3181d424bc0d3cce17c7b026e09d78c270cea3e2" rel="stylesheet" type="text/css" href="_static/_static/styles/sphinx-book-theme.css" />
    <link rel="stylesheet" type="text/css" href="_static/mystnb.4510f1fc1dee50b3e5859aac5469c37c29e427902b24a333a5f9fcb2f0b3ac41.css" />
    <link rel="stylesheet" type="text/css" href="_static/copybutton.css?v=76b2166b" />
    <link rel="stylesheet" type="text/css" href="/_/static/css/badge_only.css" />
    <link digest="5a5c038af52cf7bc1a1ec88eea08e6366ee68824" rel="stylesheet" type="text/css" href="_static/_static/scripts/sphinx-book-theme.js" />
    <link rel="stylesheet" type="text/css" href="_static/css/custom.css?v=366103d0" />
```

![grafik](https://github.com/executablebooks/sphinx-book-theme/assets/291575/9f972cad-b2b5-4588-8fda-e8a4fa3f2efd)

### Reproduce the bug

Build documentation with `sphinx-book-theme==1.1.0rc2` and `html_static_path = ["_static"]` on ReadTheDocs

### List your environment

Successfully installed accessible-pygments-0.0.4 asttokens-2.4.1 attrs-23.1.0 beautifulsoup4-4.12.2 click-8.1.7 comm-0.2.0 debugpy-1.8.0 decorator-5.1.1 executing-2.0.1 fastjsonschema-2.19.0 greenlet-3.0.2 importlib_metadata-7.0.0 ipykernel-6.27.1 ipython-8.18.1 jedi-0.19.1 jsonschema-4.20.0 jsonschema-specifications-2023.11.2 jupyter-cache-1.0.0 jupyter-client-8.6.0 jupyter-core-5.5.0 latexcodec-2.0.1 markdown-it-py-3.0.0 matplotlib-inline-0.1.6 mdit-py-plugins-0.4.0 mdurl-0.1.2 myst-nb-1.0.0 myst-parser-2.0.0 nbclient-0.9.0 nbformat-5.9.2 nest-asyncio-1.5.8 parso-0.8.3 pexpect-4.9.0 platformdirs-4.1.0 prompt-toolkit-3.0.43 psutil-5.9.6 ptyprocess-0.7.0 pure-eval-0.2.2 pybtex-0.24.0 pybtex-docutils-1.0.3 pydata-sphinx-theme-0.14.4 python-dateutil-2.8.2 pyyaml-6.0.1 pyzmq-25.1.2 referencing-0.32.0 rpds-py-0.13.2 scverse-tutorials-0.0.1 six-1.16.0 soupsieve-2.5 sphinx-autodoc-typehints-1.25.2 sphinx-book-theme-1.1.0rc2 sphinx-copybutton-0.5.2 sphinxcontrib-bibtex-2.6.1 sphinxext-opengraph-0.9.1 sqlalchemy-2.0.23 stack-data-0.6.3 tabulate-0.9.0 tornado-6.4 traitlets-5.14.0 typing-extensions-4.9.0 wcwidth-0.2.12 zipp-3.17.0

**Comment by agoose77** [comment]
Ha, you're too quick for me! Yes, I noticed this too and we've just made a 1.1.0rc3 release. That should fix things?

**Comment by flying-sheep** [comment]
Indeed, thanks!
