### ISSUE TITLE
Default Width is very small

### ISSUE THREAD

**Issue by orsenthil** [executablebooks/sphinx-book-theme#796]
### Describe the bug

**context**

I have this setup

```

extensions = ["myst_parser"]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
panels_add_bootstrap_css = False


html_theme = 'sphinx_book_theme'
html_static_path = ['_static']
```

And my `index.md` file is

```
# Test 1

## Test 2

### Test 3


* Checklist 1
* Checklist 2

```

**problem**

The default width is just small. How can I make sure that default width of the page is not collapsed.

![2023-12-16_19-59](https://github.com/executablebooks/sphinx-book-theme/assets/332330/6bdfb793-c453-405b-9a42-2eecead90011)

### Reproduce the bug

Build a sample test site using quickstart

### List your environment

```
Sphinx==6.2.1
sphinx-book-theme==1.0.1
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
```

**Comment by choldgraf** [comment]
I believe that this should be fixed in the upcoming Release Candidate - I'll close this but if the problem persists after upgrading to > 1.1, please re-ping here
