### ISSUE TITLE
Release version 1.1

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#798]
### Context

We've got an rc3 out for 1.1, and I don't see any issues that have popped up.

### Proposal

 I'd suggest we release 1.1 since there's been a lot of time for feedback and iteration. @agoose77 any objections? If not, could you do this? Or after a day or so if it hasn't happened I'll try to find some time to do it.

**Comment by agoose77** [comment]
No objections! I can mint it now.

**Comment by agoose77** [comment]
It's out!
