### ISSUE TITLE
Content of "On this page" not shown in Safari

### ISSUE THREAD

**Issue by spring-haru** [executablebooks/sphinx-book-theme#80]
I use macOS 10.15.4 Catalina.
In [this link](https://sphinx-book-theme.readthedocs.io/en/latest/notebooks.html), Safari 13.1 does NOT show the content of the **On this page** navigation menu at the top-right corner, whereas Firefox 75.0 and Chrome 81.0 do show it if the mouse cursor hovers over **On this page**.

**[EDIT]**
I also tried Safari on iPad Pro with iOS 13.4.1. The same problem as in Safari on Mac.

**Comment by kyleniemeyer** [comment]
I am also having this issue—both on the book I am building locally, but also on the home page for the project (e.g., https://beta.jupyterbook.org/start/overview.html).

I can also confirm that this does work in Firefox, Chrome, and Opera (latest versions).

**Comment by choldgraf** [comment]
Hmmm - this is difficult for me to test because I don't have a Mac and Safari is only available to Macs, but I will try to figure this out in the coming days! If anybody else can find the right CSS rules to get this working on Safari, please do chime in here!

@AakashGfude any chance you have a mac?

**Comment by AakashGfude** [comment]
@choldgraf unfortunately not. I will ask @najuzilu or @mmcky to test it out. Also, we can subscribe to BrowserStack for such future bugs (looks like they make it free for open source projects?) 
https://www.browserstack.com/open-source

**Comment by AakashGfude** [comment]
@spring-haru is the content shown when **clicking** on `On this page` text in iPad Pro?

**Comment by spring-haru** [comment]
@AakashGfude  nope, unfortunately.

**Comment by choldgraf** [comment]
@AakashGfude amazing - browstack looks like it'll work great. I applied for an account for jupyterbook.org, we'll see how it goes

**Comment by mmcky** [comment]
@AakashGfude https://www.browserstack.com looks great. 
We should set this up for QuantEcon also as we march towards automatic deployment using github Actions. 

cc: @DrDrij have you worked with browserstack

**Comment by mmcky** [comment]
@choldgraf have you used this in `CI` workflows before: https://github.com/gjtorikian/html-proofer

**Comment by choldgraf** [comment]
OK can folks give this a shot again on `jupyterbook.org` and see if it works now on Safari?

**Comment by najuzilu** [comment]
@choldgraf it works great 🎉 
<img width="186" alt="Screen Shot 2020-05-01 at 2 01 44 PM" src="https://user-images.githubusercontent.com/33075058/80781035-4bc81780-8bb4-11ea-8de8-6b700a2ed1a4.png">

**Comment by kyleniemeyer** [comment]
@choldgraf yep, works for me! The menu is static, rather than dropping down when hovering with the cursor, but that works just fine.

**Comment by choldgraf** [comment]
@kyleniemeyer whether the menu is static or not should depend on two things:

1. Is the screen wide enough? On really wide screens the TOC will always show
2. On narrower screens, is there any *margin* content? If not, then the TOC will always show

**Comment by kyleniemeyer** [comment]
Got it—it seems to be working properly then

**Comment by spring-haru** [comment]
Beautifully working in Safari on Mac/iPad Pro! Looks so great!!

**Comment by choldgraf** [comment]
wohoo! thanks all for your patience and help :-)  I'm gonna close this

**Comment by kyleniemeyer** [comment]
Hey @choldgraf, an issue with "on this page" seems to have popped up again, on Safari at least.

In Safari, bringing your cursor over "On this page" results in the menu appearing and then disappearing, before one has a chance to click on anything (or read it really). On Firefox, it seems to have the desired behavior (menu appearing when highlighted, staying until you click or move elsewhere).

**Comment by choldgraf** [comment]
hmmm - OK that is helpful, could you open a new issue about it? This might be finnicky for a little bit as we work out the bugs

**Comment by kyleniemeyer** [comment]
@choldgraf sure thing, should that go in this repo or in the Jupyter Book repo?

**Comment by choldgraf** [comment]
I think it'll probably be in this repo for the fix
