### ISSUE TITLE
Latest pydata theme release seems to have breaking impact on sphinx data theme UI

### ISSUE THREAD

**Issue by fervand1** [executablebooks/sphinx-book-theme#836]
### Describe the bug

Toggle Primary sidebar is not working anymore

Expected:
Toggle button to work like before

### Reproduce the bug

Steps:
1. Setup a sphinx book theme docs
2. Click toggle primary sidebar button
3. Toggle won't work

Expected:
Toggle sidebar button works

**Comment by fervand1** [comment]
Note: If I downgrade to pydata theme to <0.30.0 the UI seems to works fine again

**Comment by calebqcook** [comment]
I've been wracking my brain over this for days until I thought to check if this was a bug... I have this same issue, also reproducible from a clean sphinx-book-theme project.

> Note: If I downgrade to pydata theme to <0.30.0 the UI seems to works fine again

How can I do this in my setup?

**Comment by fervand1** [comment]
@calebqcook I added a wrong version earlier.
pip install pydata-sphinx-theme<0.15.3 that will fix the issue. The latest version that is 0.15.3 causes a break.
Note this is a base theme over which sphinx book theme has been developed

**Comment by bjlittle** [comment]
@calebqcook You'll need to quote the package specification so that (I assume you're using a Linux distro) the `<` isn't interpreted as a file redirection operator by the shell.

So try:
```bash
pip install 'pydata-sphinx-theme<0.15.3'
```

**Comment by tuncbkose** [comment]
I don't know how exactly `pydata-sphinx-theme` affects this, but looking at the browser console when I have the same problem, I see an error that indicates `jQuery` not being present. This change happened in `sphinx==6.0.0` (some note on it [here](https://www.sphinx-doc.org/en/master/changes.html#id262)) and at least at times whenever I can replicate this error, downgrading to `sphinx<6` solved it for me. Presumably `[sphinxcontrib.jquery](https://github.com/sphinx-contrib/jquery/)` would also solve it, though a built-in fix would be nicer.

**Comment by parmentelat** [comment]
@tuncbkose 
imho and following the findings in pydata/pydata-sphinx-theme#1875, I would say the message related to jQuery is a red herring
plus, the release date of sphinx 6.0.0 also seems too old to be linked to the issue

in any case I can confirm that in my setup too, pinning `pydata-sphinx-theme` to `<0.15.3` fixes the problem
