### ISSUE TITLE
"On this page" menu not working in Safari

### ISSUE THREAD

**Issue by kyleniemeyer** [executablebooks/sphinx-book-theme#85]
(migrating from #80)

In Safari, bringing your cursor over "On this page" results in the menu appearing and then disappearing, before one has a chance to click on anything (or read it really). On Firefox, it seems to have the desired behavior (menu appearing when highlighted, staying until you click or move elsewhere).

**Comment by choldgraf** [comment]
Thanks for finding this - Safari is tricky, it seems to behave differently from basically all of the other major browsers  :-/

**Comment by choldgraf** [comment]
Could you give this another shot? I've made some updates to this code and maybe it works now?

**Comment by kyleniemeyer** [comment]
@choldgraf yes, this seems to be working now! 

The behavior now is that the "On this page" is always present with the sections listed; as I scroll down, the section is highlighted as I pass the header. If there is content in the margin, the "On this page" menu collapses as it reaches the margin content, and reappears when you pass it.

**Comment by choldgraf** [comment]
Perfect! Yahoo!
