### ISSUE TITLE
Explore using the iooxa outline component for our TOC

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#88]
iooxa has a nice component for displaying a TOC: https://iooxa.dev/article/outline

perhaps we could use that here for the same effect

**Comment by pradyunsg** [comment]
How would this be different from the current right sidebar?

**Comment by choldgraf** [comment]
well this issue was made in a time when the sidebar was not as nice as it is now :-)  maybe we can close this? OK I'm closing this haha
